== Chapter IV

=== A Few Words Concerning Man in his Fallen Degenerated Estate from God, in Which he Hath Not Power to Keep the Commands of God, Nor his Law, Nor to do Any Work Acceptable to him; but All his Righteousness is as Filthy Rags.

All men by nature are the children of wrath, as it is written, Eph. 2:3,
fallen from God and his power, degenerate plants of a strange vine, Jer. 2:21,
daily bringing forth evil fruit, in which God hath no delight; his heart is corrupted,
his mind is corrupted, and every part and member of his body,
from the crown of the head to the sole of his foot, full of wounds and bruises,
and putrefying sores, Isa. 1:6;
every imagination of his heart is only evil continually, Gen. 8:21.
So that he is a vessel altogether unfit for the Lord`'s use or service,
neither hath the Lord any delight in him in that state, because he is a slave to Satan,
led captive at his will, to dishonour his Maker in all his words and works:
so that all his undertakings and outgoings are to promote Satan`'s kingdom.
He calls evil good, and good evil, puts light for darkness, and darkness for light,
and is void of understanding, as the beast that perisheth.
He is altogether insensible of his Creator, and of his way, truth, and life,
because they are spiritually discerned; being wholly a stranger to the life of God,
and to the covenant of promise, and without God in the world,
in its ways and works of darkness; drawing iniquity with cords of vanity,
and drinking it in, as the ox drinks water, till he fill himself, and vomit it up again.

In this estate he is compared to a dog,
whose nature is to vomit up that which he greedily eats; and to a swine,
whose nature is to wallow in the mire, as most pleasing to his nature,
till he hath fouled himself all over, that he is loathsome to behold.
Even such is man by nature, who wallows in sin and corruption,
till he be loathsome in the sight of the Lord, and fit for no service for him,
till he be washed again. Therefore the Lord cried unto the house of Israel,
Wash ye and make ye clean, put away the evil of your doings, Isa. 1:16,
and then come unto me, verse 18.

In this condition, man`'s wisdom is earthly, carnal, sensual, and devilish;
yet by this he would compass the heavenly mystery of eternity,
and dive into the secrets of the Almighty,
and set up a way of worship of God in his will, and establish a righteousness of his own,
and will pray, read, sing and perform many duties in a hot zeal,
though without understanding the knowledge of God his Creator.
In this state were the Jews,
who killed and persecuted the Lord of life in their darkness and unbelief,
in a righteousness of their own, which was as filthy rags,
and would not cover them from the wrath of the Almighty,
a just reward of all their ungodly deeds, unto whom Christ put forth many parables,
and said, Except a man be born again, he cannot see the kingdom of God, John 3:3. And,
except ye be converted, and become as little children,
ye shall in no wise enter the kingdom of God, Luke 18:17,
though they were whited over as whited walls, yet they were foul and corrupted,
blind and naked; therefore the woe was often pronounced against them;
for all their zeal and profession of Christ and the apostles`' words.

Therefore, Oh natural man! whoever thou be, whether professor or profane,
thy profession and profaneness are alike, while thou art unconverted, unregenerated,
and uncreated again into that image and nature which is from above,
which can do the will and work of God well pleasing to him.
I preach not perfection to thee, but repentance,
I do not say that thou canst keep the law of God,
for then I should belie thee and the Truth also.
I do not press thee to keep the commandments of God,
for thou wilt say with Leonard Letchford it cannot be done.
But this I say to thee, if thou wilt be wise,
thou must first become a fool that thou may be wise; 1 Cor. 3:18,
but this thou canst hardly bear,
thou art so puffed up in the pride of thy heart in what thou performest unto God,
though when thou hast done all thou canst, thou art an unprofitable servant,
as it is written, Luke 17:10, who is to have his portion with hypocrites,
where is weeping and gnashing of teeth forever, Matt. 25:30.

At thy hand God cannot have a sacrifice well pleasing to him;
if thou give thy first-born for thy transgression,
or the fruit of thy body for the sin of thy soul,
it is but as the cutting off of a dog`'s neck, or offering of swine`'s blood,
while thy heart is corrupted through the deceitfulness of sin.
This is that with which God hath a controversy in thee;
and with thee he will not make peace, till this wall of partition be broken down,
for it was that which first made a separation between thy father Adam and him,
which stands against all his seed and race after him;
and not all the offerings and oblations throughout the first covenant,
which stood in outward things, could ever make an atonement,
so as to bring Adam`'s stock into unity with his Creator.

Therefore this is my counsel and advice unto thee, who art in the unconverted state,
alienated from God, and estranged in thy mind from his covenant of life,
who hast any desires in thee to return unto the Lord who made thee,
that he may save thee from the heat of his wrath forever: cease from thy own words,
works and ways, and be not hasty to run, before thy Maker lead thee by the hand,
in the light of his Truth, wherewith Christ hath lighted thee, John 1:9,
which shineth in thy dark heart, 2 Cor. 4:6, so shalt thou not abide in darkness,
but shalt receive the light of life, John 8:12. Hearken unto his voice;
who stands at thy door and knocks, and who would have thee receive him into thy heart,
which is his throne, upon which he must sit as King,
if ever he receive thee into protection with him.
There he must work the Father`'s will in thee,
which is to purify thee throughout in body, soul and spirit,
without which thou canst never be a vessel of honour
to God to set forth his praise and glory in the earth.
His righteousness he must work in thee by his right hand, which must cover thee forever;
and thou must be crucified upon his cross from all thy own righteousness and unrighteousness,
which all spring from the seed of enmity, in which God had no delight,
before thou know the peace of God, which passeth all understanding,
to keep thy heart and mind.

All this thou wilt find true in the day of thy visitation,
however the false prophets may persuade thee to the contrary;
that will deceive thee in the day of the Lord`'s fierce indignation,
when every one shall receive a reward according to his deeds.
This is a hard saying to thee who art yet alive in
the fulness of delight and pleasure in the flesh,
to tell thee of dying to thy own righteousness and unrighteousness,
before thou come to live to God.
This is a bitter cup to thee, of which thou must be willing to drink,
before thou taste of the cup of blessing, which is the communion of the blood of Christ,
1 Cor. 10:16, Thou must suffer with him who died upon the cross,
before thou know the virtue of his resurrection; thou must put off the old man,
with his deeds, before thou put on the new man, Eph. 4:22-24.
Thou must purge out the old leaven of uncleanness,
and the old bottle must be broken, before thou keep a feast of unleavened bread,
1 Cor. 5:7-8, as a passover unto the Lord.

These are the footsteps of the flock,
in which thou must walk before Christ`'s righteousness be thine;
thou must buy the Truth with the loss of all that is contrary to it,
if ever thou truly purchase it, so as to be thine forever.
This is the word of the Lord God unto thee, which must be fulfilled in or upon thee.
Let no man deceive thee, through vain words of such as tell thee,
God looks upon thee not as thou art in sin, but as thou art in Christ.
Oh poor deluded wretch! this is the deceiveableness of unrighteousness indeed,
which would make God as unrighteous as themselves,
to look upon man in Christ when he is not; but in sin and transgression.
Give not heed to such lying vanities, lest thou forsake thy own mercies forever.
For because of these things hath come the wrath of God upon the children of disobedience,
Eph. 5:6, Col. 3:6. Him that saith to the wicked, thou art righteous,
shall the nations curse, and people abhor, Prov. 24:24. I say,
God looks upon thee as thou art; and he will not justify thee in sin,
nor hold thee guiltless in transgression, but will wound the head of his enemies,
and the hairy scalp of such a one as goeth on still in his trespasses, Ps. 68:21.
Therefore return, return unto the Lord by speedy repentance,
and kiss the Son lest he be angry, and thou perish from the way of life;
when his wrath be kindled but a little.
Blessed are all they that trust in him, Ps. 2:12.

I tell thee again, I am not sent to preach perfection unto thee,
but the day of the Lord`'s vengeance and recompense.
I am not to daub thee with untempered mortar, as the false prophets have done many years,
to cry peace to thee in iniquity, to whom the Lord saith, There is no peace,
Isa. 48:22; ch.
57:21. Therefore cease from man, and from spending thy money for that which is not bread,
and thy labour for that which satisfieth not, Isa. 55:2. And if thou art,
or has been feeding among the swine upon the husk, and wallowing in the mire among them,
and satisfying thyself with a profession of the saints`' words outwardly;
as they are written in the letter of the Scripture,
while thou art a stranger to that life in which they lived who gave them forth;
oh this is as chaff to the wheat,
which is the inward possession of the life and righteousness of the Son of God.
Therefore return unto thy Father`'s house, to the light in which God dwelleth,
1 Tim. 6:16, so will he meet thee, and embrace thee, and rejoice over thee,
and satisfy thee with bread enough, Luke 15:17-20,
yea with the fatted calf (his own crucified one)
of which thou shalt feed and never hunger more.

This I was warned by the Lord to lay before all who are yet in Babylon and Egypt,
that they may flee out and escape from her sins, lest they partake of her plagues,
as it is written, Rev. 18:4, for the hour of her judgment is come,
and the execution will speedily follow,
which will leave the wicked neither root nor branch.

Therefore let your laughter be turned into mourning, and your joy into heaviness,
for God hath clothed himself with a garment of vengeance, and with zeal, as with a cloak,
Isa. 59:17; and no unclean thing shall now stand before him.
Howl ye oaks of Bashan, and ye cedars of Lebanon,
the Lord hath laid his axe to your roots, and your strength and tallness must come down.
Your fruit hath been the fruit of Sodom, and your grapes the grapes of Gomorrah;
you have long cumbered the ground, even till it is weary with you,
and is ready to vomit you up; therefore bow yourselves unto the mighty God of Jacob,
before he cut you down, and cast you into the fire of his jealousy forever.
Tremble at the presence of him, whose word is gone forth.
He is the God of the whole earth, and before him all nations are as the drop of a bucket,
Isa. 40:15, who hath measured the waters in the hollow of his hand,
and meted out the heavens with a span,
and comprehended the dust of the earth in a measure, and weighed the mountains in scales,
and the hills in a balance, Isa. 40:12.
He will render to every man according to the fruit of his doings;
therefore while thou hast a little time, prize it,
lest the day of thy visitation pass away,
and the day of wrath come upon thee as a thief in the night, 1 Thess. 5:2.

=== A Testimony Concerning the Spiritual Man, who is Begotten of God, Through the Spirit, by the Immortal Word of God, which Liveth and Abideth forever, and Hath Received the Spirit of Adoption, Whereby he Cries Abba, Father.

As there is a natural man who is corrupted after the deceitful lusts,
so there is a spiritual man, who is born of the Spirit,
and hath the promise of eternal life.
Through the adoption, viz. the redemption of the body,
he is made an habitation of God through the Spirit; in whom God dwells and walks,
according to his promise of old, 2 Cor. 6:16. He walketh in the Spirit,
and doth not fulfill the lusts of the flesh.
In him hath God great delight, and giveth him wisdom, power, strength,
and ability to do whatsoever he commands him,
and he can do all things through him who is his strength, Phil. 4:13.
The commandments of God are not grievous, but joyous to him;
nay they are his only delight, and this keeps him in love and favour with God;
so that he withholds no good thing from him, Ps. 84:11,
but gives him of the abundance of his heavenly treasure.
He feeds him with the heritage of Jacob, even with the finest of the wheat,
and with honey out of the rock, Ps. 81:16,
he opens his breasts of consolation to him, out of which delightsome refreshment comes,
whereby he grows in the beauty of holiness.
In his mouth are the high praises of the Lord, as a two-edged sword in his hand,
through which he executes vengeance upon the heathen, and punishment upon the people,
Ps. 149:7. As the natural man is wise to do evil, +++[+++so the regenerated man]
is wise to resist evil, so that it doth not come nigh unto his house; yea,
though evil pursue the wicked, yet to him there is a tree of life, Prov. 13:21,
upon which he feeds, and lives forever.

He is stout and valorous, even as bold as a lion, Prov. 28:1;
he fears not the swelling of the sea, he is not afraid of the terror of the night,
nor of the arrow that flieth by day, Ps. 91:5; the law of truth is in his mouth,
Mal. 2:6; so that his steps cannot slide.
He calls no man father upon earth, nor any man master below the sun, Matt. 23:9-10;
for he is born of God, and receiveth his law from his mouth;
he is created anew in Christ Jesus unto good works, that he may live in them.
He lives by every word that proceedeth out of the mouth of God, Matt. 4:4;
over him death or darkness hath not power,
but he stands in the glorious liberty of the sons of God.
A free born son and heir of God, and a joint-heir with Christ Jesus, Rom. 8:17,
he grows up in the measure of the stature of the fulness of Christ, unto a perfect man,
as it is written of him, Eph. 4:13, but this is a mystery to the natural man,
even as the wind blows where it listeth, and he hears the sound thereof;
but knows not whence it comes, nor whither it goes, John 3:8,
even so is every one that is born of the Spirit.

Therefore they who are of the flesh, mind the things of the flesh,
and they who are of the Spirit, the things of the Spirit.
And as many as are led by the Spirit of God, they are the sons of God, Rom. 8:14,
but the natural man receiveth not the things of the Spirit of God,
for they are foolishness to him, 1 Cor. 2:14;
but the spiritual man judgeth all things, and he himself is judged of no man, 2 Cor. 2:15.
This is that noble birth which God
hath brought forth in many at this day,
unto whom we preach perfection and freedom from the law of sin and death,
which is the same wisdom which Paul said he preached among them that were perfect, 1 Cor. 2:6-7.
But this the carnal man cannot endure to hear of,
who receives not the things of the Spirit of God, as it is written of him, 1 Cor. 2:14.
Therefore it is no marvel why he cannot receive this doctrine of perfection,
which the holy men of God held forth unto the spiritual
man so plentifully throughout the Scriptures of Truth,
as I have shown before to all,
who with a spiritual eye discern the things of God by which they are only known,
1 Cor. 2:11, but they are foolishness and madness to the sons of Belial.

Whosoever is born of God doth not commit sin, for his seed remains in him,
and he cannot sin, because he is born of God; then saith he,
in this are the children of God manifested, and the children of the devil.
Whosoever doeth not righteousness is not of God,
neither he that loveth not his brother, 1 John 3:9-10.
By this a man will soon see whether
he be a child of God or of the devil,
who would persuade others, that to do good and not to commit sin,
is that which none dares challenge upon the earth,
and that it would be praise to God to say his commandments
cannot be done without sinning or offending;
this cannot be paralleled in all the Scripture.

Therefore, oh! thou begotten of God, who art born again of the water and of the Spirit,
give in thy evidence against this unheard of heresy,
which God will confound with the breath of his mouth,
and with the brightness of his glory.
This is arisen and arising to expel all those fogs,
mists and vapours with which the man of sin hath overspread the earth,
in this long night of darkness and apostasy from the life of God,
wherein +++[+++the false church]
that hath sat upon many waters hath made all nations drunk, Rev. 17:1-2; and 18:3,
and hath sat as queen, and seen no sorrow.
Her ministers have pampered themselves in the fulness of the earth,
and have made merchandize of many through covetousness and feigned words,
2 Pet. 12:3, for these sixteen hundred years and upward,
ever since antichrist went out into the world,
who have continued in the world to this day, 1 John 2:18,
deceiving the nations with the multitude of their enchantments.
But now is the day of the Lord broken forth in clearness again in this latter age,
which hath discovered her skirts with all her merchants,
who is worse than Balaam the son of Beor,
who though he loved the wages of unrighteousness, durst not take it.
Num. 22:18; 24:13. But they love and take it,
and persecute all those who will not give it to them,
as we have a cloud of witnesses standing upon record against them at this day.

=== The Way which Leadeth to the Kingdom of God, Held Forth to All who are Willing to Enter Therein.

As Satan by sin and transgression opened a way into
eternal misery and condemnation from God,
for all who follow and obey him;
so God in his infinite love and mercy by Jesus Christ
hath opened a gate of mercy unto all mankind,
and hath prepared a way of life, peace, and eternal salvation,
that all who are willing to walk in it, may attain thereunto.

This way is called the way of holiness, which the unclean shall not pass over;
but the wayfaring man, though a fool, shall not err therein, Isa. 34:8,
This way is a mystery to all the sons of Adam, and is strait and narrow,
and few there be that find it, Matt. 7:14;
but the way which leads to destruction is wide and broad; and all the unclean, yea,
all the workers of iniquity can walk therein, Matt. 7:13.
There are but these two ways for all mankind to walk in;
the one leads to life eternal, and the other to eternal death.

Now the Lord hath opened my heart a little to show unto every one the way of life,
which is Christ Jesus; John 14:6, and that by which they may be brought into this way,
according as the Spirit of God shall give me utterance.
It is written in the Scriptures of truth, that a woman having ten pieces of silver,
if she lose one, doth light a candle, and sweepeth her house,
and seek diligently till she find it; and when she hath found it,
she calleth her friends and neighbours together, saying, Rejoice with me,
for I have found the piece which I had lost, Luke 15:8-9.
This is a parable of the way of life,
which is to be found within when the candle is lighted; and thy house swept,
which is thy heart, which is foul and corrupted by the enemy of thy soul,
who hath led thee from mountain to hill,
like a lost sheep,--I mean from one high priest to another,
so that thou hast forgotten thy resting place.

Therefore hath the good Shepherd left the ninety and nine in the wilderness,
and is gone after thee who art lost in the mountains,
and will lay thee upon his shoulders, bring thee home, and rejoice over thee, Luke 14:4-5.
And when thou art come in,
thou shalt be fed in a good pasture by the rivers of water, where thou shalt not want,
Ezek. 34:14, and thy soul shall delight itself in fatness and shall live, Isa. 55:
2+++.+++ For the Lord will be thy Shepherd, and thou shalt be established in righteousness,
and great shall be thy peace, Isa. 54:13, and thou shalt not need to say,
Who shall ascend into heaven to fetch Christ from above?
or who shall descend into the deep to fetch him from beneath?
but the word shall be nigh thee, in thy heart and in thy mouth, according as it is said,
Rom. 10:8; Duet. 30:14. This will be a lamp to thy feet, and a light to thy path,
Ps. 119:105, to guide thee in the way of truth and peace,
and will give thee the light of the knowledge of
the glory of God in the face of Jesus Christ, 2 Cor. 4:6.

So let every one search his own heart, and light the candle there,
that he may find the word of faith there to guide him.
This word David hid in his heart, that he might not sin against God,
Ps. 119:11. This is the word of faith which I preach unto thee,
that thou may come to hear and receive it, whereby faith may be wrought in thy heart,
to give thee victory over the world, sin, death, darkness, and the grave,
which have long separated thee from God.
Then shalt thou witness him to be thy Redeemer, even the Holy One of Israel.
But if thou ask me what must lead thee to this Redeemer?
I answer, The law of God which he hath written in thy heart,
according to his promise in the second covenant, Jer. 31:31-33,
which law was the apostles`' schoolmaster to bring them to Christ,
that they might be justified by faith. Gal. 3:24.

This law will be thy schoolmaster to bring thee to Christ,
that thou mayst be justified by faith, and not by the works of the law.
This will be a present teacher with thee at all times and in all places,
and will never let thee do evil,
nor do that to another thou would not that he should do unto thee.
It will bring thee to love the Lord with all thy heart, and thy neighbour as thyself,
as it is written in the law of Moses; yea,
when thou turnest to the right hand or to the left, thou shalt hear a voice behind thee,
saying, This is the way, walk in it, Isa. 30:21.

But thou may object and say, Shall I not go to hear sermons from learned men,
such as are brought up at Oxford or Cambridge?
I say, cease from man,
even from all those who keep thee from the law written in thy heart,
for such have no light in them, Isa. 8:20. Such are blind guides,
and would keep thee from this law which is light, Prov. 6:23,
lest it should discover their darkness unto thee,
and that they may lead thee in blindness and darkness
which lead to the chambers of death, Prov. 7:27.
Thou mayst spend all thy substance upon the physicians,
as the woman had done, and yet was not cured, till she came to Christ, Luke 8:43-44;
and thou wilt not be till thou come to be led to him,
by that which manifests both thy deeds of darkness and theirs also,
who have applied salve to thy wounded soul,
before they have cleansed out thy corrupted ulcers with which thy soul hath been loaded;
so their salve hath taken no impression, nor been availing at all unto thee;
and they have been physicians of no value, Job 13:4,
but thy corruptions have prevailed upon thee till all thy money is spent.
Oh, therefore hearken unto him who stands at thy door and often knocks.
If thou wilt open thy door, he will come into thee, and will sup with thee,
and thou shalt sup with him, Rev. 3:20. Then shalt thou know the supper of the Lord,
even a feast of unleavened bread.

If thou wilt receive him,
he will cleanse thy sores and lance thy wounds like the good Physician,
and reach the living sensible part in thee,
that the corruption hath not prevailed against;
and nothing else he will suffer to remain within, that he may thoroughly cure thee,
and make thee perfectly whole in body, soul and spirit;
and then he will pour in the oil of joy for the spirit of heaviness,
that thou mayst be called a tree of righteousness, the planting of the Lord, Isa. 61:3.

Then shall the light of the moon be as the light of the sun;
and the light of the sun shall be seven-fold, as the light of seven days,
in the day when the Lord bindeth up thy breach and healeth the stroke of thy wound, Isa. 30:26.
Then shalt thou, who hast been deaf, hear,
and thy blind eye shall be opened, and shall see out of obscurity and out of darkness,
Isa. 29:18, and thou shalt increase thy joy in the Lord,
and rejoice in the Holy One of Israel, verse 19.
Then shall judgment dwell in the wilderness, which thou shalt love,
and righteousness in the fruitful field in which thou shalt dwell,
and the work of righteousness shall be peace, and the effect of righteousness,
quietness and assurance forever, Isa. 32:16-17.
Then shall thy soul delight itself in the Lord its Redeemer,
and magnify the name of the God of Israel all thy days.

And thou shalt not need to be taught of thy neighbour or of thy brother to know the Lord,
for thou shalt know him, and be taught of him, and great shall be thy peace,
according to the words of Jeremiah, Jer. 31:34; Isa. 54:13; John 6:45;
and the anointing wherewith he hath anointed thee shall abide in thee,
and thou shalt not need any man to teach thee,
but as the anointing teacheth thee of all things, and is truth and is no lie,
and even as it teacheth thee, thou shalt abide in him, 1 John 2:27.
These things I have written to thee concerning
any that would seduce thee from this inward teacher,
verse 26; that if any come to thy house and bring not this doctrine,
bid him not God speed, lest thou be partaker of his evil deeds; yea, if I,
or an angel from heaven preach any other doctrine, let us be accursed,
and let God give no more increase to our work,
than he hath done to the work of the priests these many years.

Therefore cease from man whose breath is in his nostrils,
and hearken unto him by whom God speaks in these last days, as thou mayst read,
Heb. 1:1, who saith, Learn of me and ye shall find rest for your souls, Matt. 11:29.
He will be a sufficient teacher unto thee in all the ways of righteousness,
and be a wall unto thee in the time of storm, and a shadow in the time of heat,
Isa. 25:4, yea, he will be thy Shepherd,
and spread thy table in the sight of thy enemies, Ps. 23:1-5,
and he will lead thee into green pastures by the rivers of water,
and will restore thy soul to praise and glorify his name forever.

=== The Difference Between the True Gospel and the False, Truly Stated and Clearly Demonstrated; that All People may See and Read which Gospel they have Received and Obeyed these Many Years, Whether the True Gospel, or the False.

The true and everlasting gospel of Jesus Christ the Son of God,
is glad tidings of good things; which are remission of sins,
and reconciliation to God by Jesus Christ, Luke 1:19; Luke 8:1,
which was preached to give the knowledge of salvation
unto all people by the remission of sins, Luke 1:77.
So here it manifestly appears,
that this gospel was preached to give the knowledge of salvation to all people,
which knowledge was only received by the remission of sins.

The false gospel of antichrist the man of sin is sad tidings of bad things,
wherein there is no remission of sins,
but a continual slavery unto sin and Satan all man`'s days,
according as it is and hath been taught by the teachers of this generation,
which is as contrary to the true gospel, as light is to darkness.

The true gospel message is to turn people from darkness to the light,
and from the power of Satan unto God, that they might receive forgiveness of sins,
and an inheritance amongst them that are sanctified by faith in his Son, Acts 26:18.

The message of the false gospel is,
that people can never come from under the power of Satan,
but must have a body of sin as long as they live, which is sad tidings,
and not glad tidings.
For another to pretend freedom to him that hath been
under a tyrant`'s power from his birth,
and take his money as though he would bring him to Christ who would free him,
and yet in the end tell him he must remain under the power of this tyrant all his days;
this is sad tidings to him, who hath spent his money, and is neither redeemed,
nor hath any hopes ever to be while he lives; and such is the false gospel at this day.

The message of the true gospel is a proclamation of liberty and freedom to all captives,
who have been imprisoned in sin and transgression,
wherein the blood of Christ is freely held forth for the remission of sins, Matt. 26:28.

The message of the false gospel is continual captivity in sin,
and never liberty nor freedom from it, as we have seen by many years sad experience.

The true Captain of salvation saith, Follow me, and thou shalt find rest to thy soul, Matt. 11:29.

The false leader saith, Thou shalt never overcome, but be in a continual warfare,
and shall never come to peace nor rest here, which is sad news indeed.

The messengers of the true gospel say,
They were circumcised with the circumcision made without hands,
in putting off the body of the sins of the flesh by the circumcision of Christ, Col. 2:11.

The messengers of the false gospel say, This can never be done,
but men must have a body of sin as long as they live,
which is far different from the other.

The messengers of the true gospel say, Christ shall save his people from their sins.

The messengers of the false gospel say, Christ shall save from the punishment due to sin,
but not from committing sin; which doctrine overthrows the justice of God,
who giveth to every one according to their deeds.

=== To the General Assembly of the First-Born in the Northern Coasts of England, who were the First Fruits unto God, and had First the Joyful Sound of the Everlasting Gospel Published in your Ears, Whereby you were Raised from Death, to Live with the Lord in his Holy Covenant of Life, Wherein his Sure Mercies unto you have been Fully Known and Manifested; Grace, Mercy, Love and Peace, be Multiplied In and Amongst you all.
Amen.

Right dearly beloved, and highly esteemed of the Lord,
unto whom his everlasting love in Christ Jesus hath fully extended,
in which he did appear unto you in an acceptable day,
even when you were enemies unto him, who chose you from among many,
and redeemed you from the kindreds of the earth, that he might manifest,
in and through you, his great power and mighty wonders to his own Israel,
even as he did by Moses his faithful servant in the days of old,
and that you might be a peculiar people unto him,
to sound forth his praises and glory in the earth,
by the brightness of that glorious light and life,
which he hath both raised and brought forth in you,
to be your director in all the ways of righteousness,
never more to stumble nor go astray, but to feed in the fresh pastures of his love,
and to lie down in his pavilion now and forever.

My dear friends, brethren and countrymen,
who are made sharers of that inestimable love of the Father,
the salutation of my dearest love reacheth unto you all in the Lord,
who am of the same stock and root, having tasted of the same bread of life,
by which I am at this day nourished and kept alive in strength and valour,
to tread upon the serpents of the earth, which are many and great,
and to live with God in the Spirit, over all the perishing glory of this present world.
My heart is filled with divine love unto you,
daily wishing your prosperous progress towards the city of God,
that you may neither fall out by the way,
nor your steps slide in the least degree from that holy commandment,
which was at first delivered to you to direct your steps,
and to be a lantern to your feet, it being both steadfast, sure and immoveable.
This hath been our instructor from our youth, even to this day,
by which we were salted and swaddled before we could either stand or go;
in which have been all our fresh springs, as you well know,
who have often received of the same, by which your souls have been replenished,
and your hearts made glad, and often your strength renewed,
so that you have been made to leap for joy of heart,
and to sing praises unto the God of your salvation with a pure heart,
and faith unfeigned.

In this you have stood approved before the Lord willing, ready,
fit and able for any service, which he was pleased to call you unto,
for the spreading abroad of that incomprehensible love which
he had so largely manifested in and unto you;
in which service I with you to this day can set my seal, that his blessing, power,
protection and life have manifestly gone along with us,
to the pulling down of many strongholds, and battering of many high towers,
which are too numberless to relate.
Yea, when he hath led us from one nation to another people,
his bow hath not failed of its strength, but hath wounded the dragon,
and rescued many from his devouring jaws, who are coming up towards Mount Zion,
with songs of deliverance and everlasting triumph upon their heads;
and also to behold that glorious beauty,
which is on the head of the fat valleys in which you dwell and lie down at this day,
who are of the true tabernacle which God hath pitched, and not man;
a spiritual household, an habitation of God through the Spirit,
to live with God in the Spirit, and to remain in the glory of his power forever;
over death, darkness and the grave, and the power thereof,
and to stand with the Lamb upon Mount Zion,
where pleasant hymns and spiritual songs are sung unto God forever.

Now for the full establishing and confirmation of this everlasting righteousness,
which God in Christ Jesus hath so plentifully manifested unto you in so special a manner,
let me, as one of the least among many brethren,
stir up your pure minds by way of remembrance: first,
that you hold fast the profession of your faith,
and steadfastly remain in the exercise thereof towards God and all men;
in this will the Lord make you victorious with him and amongst men,
which is his principal blessing at this day to his own heritage.
Let the spirit of God and of a sound mind dwell in you all,
that the depth of the mysteries of life may be opened in you,
and you swallowed up in the enjoyment thereof,
so will the showers of his love evermore be distilled upon you,
which will keep you fresh and flourishing as the choicest lilies of the Father`'s garden,
among whom he delights to dwell and walk.

Let the zeal of the Lord of Hosts be in you in knowledge and long-suffering,
forgiving one another, as Christ forgave you;
for such a people is the Lord seeking and choosing out of all the nations of the earth,
as you are witnesses at this day.
And when you come together to offer a peace-offering
unto the Lord for the atonement made,
let it be offered with clean hands, and a pure heart,
that the Lord may have respect unto it.
Let your holy assemblies be always kept with fear
and reverence in all places where you dwell,
that you may be a sweet savour unto God, and as lights before men,
and in the Spirit worship God with one consent;
so will you not want his presence amongst you, nor his eternal power to protect you.
And let no rents or divisions stand amongst you in any kind whatsoever,
for they are destructive to the whole body,
and stop the current of life and love amongst you;
so that instead of being a refreshment one to another,
you become burdensome one to another, and that offering is not acceptable with the Lord.

Therefore, if any come to the altar of the Lord,
and consider that he hath aught against his brother,
let him first be reconciled to his brother, that he may offer in the unity,
and not in the enmity, nor in the strife; for God is not the author of confusion,
but of peace, as in all the churches of Christ.
Dwell together in perfect love and unity,
that you may appear unto all to be the children of the Most High;
for some are already turned aside to folly,
and have broken this precious cord by which we are all bound in covenant with God,
and in unity one with another, which hath been our preservation even to this day;
in which we stand a complete body, fitly framed together in the Spirit, having one God,
and one Lord Jesus as head and ruler over all; and being builded, stone upon stone,
we are become a holy tabernacle, in which the Most High dwelleth and walketh at this day,
according to his promise in years past.

And now we set to our seals that he is true,
and all his judgments are according to Truth, and his ways are unsearchable;
he killeth and maketh alive; he casteth down, and raiseth up again;
he cleaveth the hard rocks, and maketh mountains to melt before him;
he openeth the graves, and maketh the dead to arise; he maketh the blind to see,
and the deaf to hear; he causeth the dumb to speak, and to sound forth his loud praises.
His word directeth the simple, and his hand upholdeth the weary soul.
He is a father to the fatherless, and a present help in the time of need.
His hand is not shortened that it cannot save,
neither is his ear heavy that it cannot hear.
He is become the fountain of living mercies to all
who come unto him while he invites them.
He is a buckler and an helmet in the day of battle; he is our life and length of days,
even the same that ever he was to Abraham, Isaac and Jacob,
and all our forefathers who bore testimony of him, unto whose testimony we,
through the same Spirit, seal to the truth of all those things;
by which Spirit he is alone known and worshipped at this day.

Therefore we testify, there is not another that can work redemption for Israel,
neither is there another salvation nor ministration than what he hath already manifested,
in which all who faithfully continue, shall know peace and consolation forever;
for there is not another name, or power, or way, or truth, or life, or righteousness,
than what God hath fully manifested in us as the hope of our glory;
neither is there another ministration of that truth
and life of righteousness ever more to arise,
above or besides this which our eyes have seen;
for this is the seventh and last trumpet that ever shall
sound to summon all to the judgment seat of Christ,
that they may find mercy.
Here is the seventh seal opened,
and the dead raised and judged according to men in the flesh,
that they may be justified according to God in the spirit; yea,
all who do not receive the tenders of his love through the leadings of his own spirit,
shall be blotted out of his remembrance forever.

Blessed are they who hear,
receive and hold fast that testimony which hath been given of the Father and the Son,
without wavering or turning aside from his holy commandment
in this hour of temptation and day of trial,
wherein God will thoroughly purge his floor and refine his gold,
and make up his choice jewels,
which he will hide in the cabinet of his rich treasures forever.
Oh, therefore let none turn to the right hand or to the left, for the mark is before,
unto which all who attain shall receive a full reward.
But if any draw back or start aside from their steadfastness and integrity,
such will lose their reward in this life, and that which is to come,
and shall be clothed with contempt and infamy forever.
For our God is swift in his goings, and will not always be found or entreated,
but only in his own way and time, in which all who have received him,
have found his bountifulness and lovingkindness,
and his manifold mercies over all his works.
Therefore my dearly beloved brethren, be all bold and valiant for the Truth,
that both we, and the begotten of God in these regions of the nation,
who are growing up in his power, may be refreshed in you, in hearing of your stability.
So be of one mind, and live in peace, and the God of peace be with you all.
Amen.

From the place of my outward restraint for the testimony of the everlasting gospel,
being prisoner in the common jail of Horsham in Sussex, by your brother and companion,
called

Ambrose Rigge.

Let this be read with fear and reverence in all the
congregations of God`'s people in the north country.
