== Testimonies of Ambrose and Mary Rigge

[.blurb]
=== Ambrose Rigge`'s Testimony Concerning His Wife

In the year 1664, I took Mary Luxford to wife,
who was the second daughter of Thomas Luxford, and Elizabeth his wife,
of Hurst Pierpoint in the county of Sussex; she was of honest and considerable parents,
who brought her up strictly, according to that religion which they believed to be true,
and she lived in great subjection to her parents.
Though they came to believe and receive the truth before her,
yet she had that reverent respect for them,
that she would not willingly appear before them in
any dress which she knew they did not love;
and was modest and courteous to friends who walked wisely towards her.
But in a short time she and her younger sister, Cordelia,
were willing to go to a meeting, where they were both convinced,
and received the Truth in the love of it,
by which they received power to cast off the unfruitful works of darkness,
and put on the armour of light,
by which they soon became able to quench the fiery darts of the devil,
which were not a few in that day;
yet through all the Lord in mercy preserved them
in faith and patience through many tribulations.

On the 6th day of the seventh month, in the year above said,
we were married in the prison at Horsham,
after I was premunired two years and kept close prisoner,
because for conscience sake I could not swear; where I continued eight years after,
and four months, all which she bore with much patience.
As the Lord, by his immediate hand, brought us together, so he preserved us together,
for the space of four and twenty years, in much love and unity,
as helpmeets one to another.
She was a blessed woman, and loved the Lord and his Truth,
and walked in it to the end of her days.
She hated all evil in word and deed, and walked before the Lord in much innocency,
and loved peace and unity, for she was a woman of a meek and quiet spirit,
and loved righteousness wherever it appeared.
She was naturally attended with many weaknesses of body,
yet was the mother of five healthy children.
She much delighted in reading night and day, so long as she had any strength of body;
and towards her latter end she had a sense of it, and spoke something of it to me,
for she was much spent with a continual consumptive cough.

In the latter end of the tenth month, 1688-9, she was taken sick,
which increased upon her, notwithstanding many remedies which were sought for her.
She bore her sickness with much quietness and patience,
till the 6th day of the eleventh month following, and then departed this life,
like a lamb, in my arms, and went to her eternal rest in the bosom of the Father`'s love,
in which love she delighted to be in her life time.
Her remembrance lives with all who truly knew her; for she was a good example to many,
and left a testimony of her innocency and integrity behind her,
whose reward is now with her: this lay upon me to write concerning her.
The first child she had died, but four are still alive grown up.
We educated them in the Truth, in their younger years, and watched over them in love,
till they knew the power of God in themselves, unto which we recommended them,
by which they have been preserved to this day, to my great comfort.
Many days and years have I, with bended knees, in secret, prayed to God,
before the throne of his grace, to guard them with his power,
from the evil of this world, and to direct their steps in the way of righteousness,
which in a great measure I have hitherto enjoyed;
blessed and praised be the name of the Lord forever.
I am not a little comforted therein; the Lord preserve them to the end of their days,
in faith and well doing.
Amen.

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
Rigate, the 11th of the Ninth month, 1694.

[.blurb]
=== George Whitehead`'s Testimony Concerning Ambrose Rigge

We having for many years been acquainted,
(as he was my countryman and loving friend) we loved as brethren from the first,
after we received the love of the Truth--which he retained;
and being faithful to the Lord, according to his gift,
was made partaker of the gospel ministry and testimony, by the word of eternal life,
and faithfully laboured therein with fervent zeal to promote truth and righteousness;
whereby the Lord made him instrumental in convincing and
converting many souls to Christ and his righteousness.
The Lord gave him not only to believe, and to declare his name and gospel truth,
but also patiently to suffer for the same.

Besides the persecutions he suffered in the commonwealth`'s days, by severe stripes,
etc., his many years`' imprisonment in Horsham jail in Sussex,
after king Charles II was restored to the crown,
doubtless was one of the greatest trials;
yet the Lord greatly supported and strengthened him,
and many other innocent sufferers in those days.

In the year 1672,
a concern greatly fell upon me to have the king moved for the releasement of
many faithful Friends and brethren who then had been long confined in prisons;
as I knew this our ancient friend and brother was, and Thomas Taylor, William Dewsbury,
and many others, throughout England and Wales;
many whereof were under sentence of premunire.

Our friend Thomas Moore, thereupon delivered a paper of mine to the king,
in behalf of the prisoners; and soon after that, I went with him to the king,
and he granted us liberty to come before him and his council,
the next council day in the same week.
Accordingly we were admitted, and appeared before the king and a full council,
where I had liberty fully to plead the innocent cause of our friends in the prisons,
and the reason of their not swearing allegiance to the king;
it being really matter of conscience to them not to swear at all in any case, etc.
The king answered, I will pardon them; that is,
discharge them from the penalties of the laws, and their estates from confiscation,
which had been forfeited by the judgment of premunire.
This was to be done by the king`'s letters patent under the great seal of England,
which I was constrained to follow and solicit,
through the several offices which such letters patent pass, before effected;
which took me up near six months`' time and labour to get thoroughly effected and executed,
so as to release Friends out of prison, and re-convey their estates forfeited.

However, I was truly glad and thankful to God when it was obtained and done.
And so was this my dear friend and brother Ambrose Rigge,
with many more faithful friends and brethren, who had long deeply suffered.
I remember he would often mention the same to me with grateful acknowledgement
of my kindness and industry to obtain that liberty for him and many others,
being above 480 in all, released out of prisons.
He was of a loving and grateful spirit and temper,
and not apt to forget acts of kindness;
knowing how comfortable true love and brotherly kindness are,
and how happy and pleasant a thing it is for brethren to live therein.

He loved unity, peace and concord, and hated strife, divisions and discord,
and was zealous against the sowers thereof.
He truly loved his ancient brethren who kept their dominion in the Truth;
and as he loved union,
peace and concord in the churches of Christ and laboured
for the promotion and increase thereof,
we had sweet society therein, even in true brotherly love and kindness,
blessed be the Lord our God, for his great kindness and love in his dear Son to us.
And as therein we have been sufferers,
and spiritual warriors for his name and truth in his church militant here on earth,
I firmly believe and hope that we shall rejoice and triumph together in Christ,
with his church triumphant in his heavenly kingdom and glory forever.

I was at the funeral of our ancient friend and brother Ambrose Rigge at Rigate,
which was accompanied with a great concourse, and with solemnity,
in which the Lord`'s presence and power did attend us, and bless our assembly.
For he was a man that had obtained a good report,
and left a sweet savour of truth and honesty behind him.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
London, the 25th of the Second month, 1709.
