== Chapter II

[.blurb]
=== Robert Pepys, Priest of Gatton in Surrey, His False Accusations to the Justices at the Sessions Against Ambrose Rigge; a Copy Whereof Follows

This Ambrose is lately come into this parish, from Horsham,
where he was in the prison (as it is reported) seven years for his damnable heresies,
and wicked opinions; and this being a private parish, he thinks to roost here,
and impudently presumes to board and teach youth in his house;
and has at this time twelve or fourteen in his house;
and being a man of parts and learning, does a great deal of mischief in seducing others;
to effecting which, he spares neither pains nor time.
And what Tertullus the orator said falsely and foolishly of St. Paul,
may very truly be said of this man, that he is a plague, a pestilent fellow.
He is justly suspected to be a Jesuit, or one that has kept their conventicles.
And this honourable court is humbly and earnestly requested by the minister and parishioners,
to take special notice of him, as a most dangerous person to the church,
being a ringleader of sects and schisms.

[.blurb]
=== Ambrose Rigge`'s Letter to Robert Pepys

[.salutation]
Neighbour Pepys,

I am credibly informed, that you did greatly instigate the magistrates,
at the sessions in Southwark, against me,
and there affirmed several untruths in a letter above mentioned.
I have reason to wonder why, upon all occasions, when you think you can do me a mischief,
you seek my ruin, who never sought your hurt in word or deed?

If you know that I have in any way trespassed against you,
how can you pray to God to forgive you your trespasses,
when you do not forgive others their trespasses?
And how do you love your neighbour as yourself, who are always,
when you think you can prevail, seeking your neighbour`'s ruin?
If I were in an error in judgment, the course you have taken since I came to Gatton,
is more like to harden me, than to convince me that you are in the way of Truth,
your daily practice is so repugnant to Christianity, and common civility among men.
God Almighty open your eyes that you may see what you are doing,
and whom you are striving against.
I have lived by you peaceably, on my part, these several years,
and served you in what I could, both in health and sickness;
and for which of my good deeds to you do you conspire against me?
the Lord judge between us: it is but my body you can reach; and if you get it,
it will do you little good.

The Jews`' priests stirred up the rulers against Christ and his followers,
under the name of deceivers, and ring-leaders of sects, Acts 24:5.
When they dared not encounter them by spiritual weapons,
then they got them to be cast into prison, by false accusations,
as you and your brethren have done many at this day,
till you have made yourselves a stink to the whole land,
that it is ready to spew you out.
I have often desired your prosecutors to favour you;
but it seems you spur on mine to hunt my soul as much as you can.
Instead of loving enemies, you are for persecuting your friends and neighbours,
whom you could never convince of the least evil, either in life or doctrine,
by the Scriptures, your own professed rule.
Well, you shall go no further than you are permitted from on high;
to all which I have learned to say, "`Your will, O Lord, be done;`" but this know,
"`That it were better for you that a millstone were hanged about your neck,
and you cast into the sea,
than to offend one of the least of them who believe in Christ.`"
Do not covet my vineyard by ensnaring me, lest Ahab`'s reward be your portion.
No more, but that I am a friend to you and all men.

[.signed-section-signature]
Ambrose Rigge.

[.blurb]
=== To the Inhabitants of Gatton, in the County of Surrey, and to All Others Whom it Does or May Concern

[.salutation]
Friends and Neighbours,

As of old, he that was born after the flesh,
persecuted him that was born after the spirit, even so it is at this day, Gal. 4:29,
for such is the implacable enmity of many priests in our age,
that scarcely any who will not put into their mouths and satisfy their covetous desires,
can be secure from the lash of their scandalous tongues and wicked hands,
they being in the way of Cain, and also in the steps of the false prophets of Israel;
Micah 3:5, Crying, Peace, peace, to them who put into their mouths,
and feed them with tithes, gifts and rewards;
but against those who for conscience sake cannot, they even prepare war.
Of this spirit has Robert Pepys, priest of Gatton,
fully manifested himself to be since he came to Gatton, as several can witness;
but more especially since I denied to pay him tithes,
it being no gospel right to any minister, as I am ready to prove by the Scripture.
For this cause did he break forth in a rage, and before several witnesses, said:
If he had leave from the king, he would himself hang ten thousand of us, called Quakers;
and also said,
it would never be well till the Spanish Inquisition was up in England again.
If this be not the spirit of Cain, the murderer, I know not what it is.
But he being out of hopes of effecting this at present,
he sued me in the Exchequer for tithes, and also got me,
my wife and servants put in the bishop`'s court,
because we could not partake of his sacrifice;
and with his own hand wrote many grievous lies and false accusations against me,
to kindle the wrath of the magistrates to destroy me,
as is manifest by his letter before mentioned.

First, that I was in the prison in Horsham, as is reported,
seven years for my damnable heresies, and wicked opinions, etc.
As for my being in prison there above ten years I deny not;
for I suffered there as a Christian for well doing,
of which I have no cause to be ashamed; but damnable heresies and wicked opinions,
I utterly deny.
Let him, or the worst of my enemies, prove the least heresy against me if they can;
till which I shall reckon my sufferings there for righteousness.

Secondly, that I do a great deal of mischief here in seducing others, to effect which,
he says, I spare neither pains nor time.
Let him prove whom I have seduced, and what evil I have done since I came here,
or else this will prove his burden also in the day of account.
The same false spirit that led Tertullus the orator, to call Paul a pestilent fellow,
and a ring-leader of sects,
etc. does now lead him to speak as falsely and foolishly against me;
but he has proved no more against me than Tertullus the orator did against Paul;
but it was ever the manner of that spirit to charge high and prove nothing,
and so it is at this day.

To say that I am justly suspected to be a Jesuit,
or one that has often been at their conventicles, is a most notorious falsehood.
For God is my witness, I never was in any of the Jesuits or Papists conventicles,
and I hope never shall, unless it be to bear witness again their idolatry.
Here let the people take notice by the way, that this priest said,
he would hang so many of us, called Quakers, as is before expressed,
in the presence of several professed Papists, with whom, at that time,
he went into his church, and expressed a great deal of kindness to them,
and said he would do what they required of him;
if they would but speak the word it should be done.
Of this I was an eye and ear-witness,
by which let wise men judge who is nearest of kin to the Papists, he or I? Or whether,
if I were a Papist, I should not have more favour from him, yes or no?

Lastly, he charged me of being a dangerous person to the church.
I suppose he means that church of which he is,
which plainly manifests it to be a false church, and built upon the sand,
which is in danger of falling; for the true church is built upon that Rock,
"`which the gates of hell cannot prevail against.`"
Matt. 16:18

Those things, before expressed, I could have passed by,
and have patiently borne with silence, as to my own particular,
knowing for whose sake I am thus reviled and persecuted,
and all manner of evil falsely said of me;
such things being always the portion of the disciples of Christ from the world:
if it were not for the sake of those who have not had any
long acquaintance with me lest they should believe his lies;
for their sakes chiefly, these lines are written.

And now are Christ`'s words fulfilled, John 16:2,
"`They have cast us out of their synagogues;`" and the priests
especially pretend to do good service in killing us;
and these things they do because they know not the Father, nor his son Jesus Christ:
Therefore all people repent and amend your lives, "`for the kingdom of God is at hand.`"

This, in tender love and good will, is written by him,
who has learned to bless them who curse him;
and to do good to them who spitefully hate and persecute him, who is called

[.signed-section-signature]
Ambrose Rigge.

[.blurb]
=== An Epistle to the People of God, Called Quakers, in the North of England, to be Read in All Their Meetings

Beloved Friends, brethren and sisters, who are inhabitants of my native country,
whom the Lord, in the first breaking forth of his glorious gospel day,
in this latter age of the world, visited with the morning thereof,
the salutation of my endeared brotherly love flows forth, at this time,
to salute you all, with breathing desires to the Lord, for your preservation,
in the faith and fellowship of the gospel of peace; and that grace, mercy and truth,
with all the fruits of righteousness, may abound in and among you all,
that you may be a royal priesthood, and a holy nation; for God has called you thereunto,
that you might be made the first fruits to his praise;
for this end he called you out of darkness into his marvellous light.
This was the precious seed of his kingdom received by you,
by which Christ came to be manifest in male and female, the hope of our glory,
who is made a covenant of light to this northern Island of the Gentiles,
and who is to be God`'s salvation to the ends of the earth.

Of these inexpressible riches, I with you,
in the beginning of the breakings forth thereof,
received and were made partakers of the like precious faith, in which by a Divine hand,
I have been preserved to this day, through many tribulations.
All holy and living praises be given to the excellent name of our God forever,
who has not left us destitute of his mercies,
but has carried us by the right hand of his power, as on eagles`' wings,
through all difficulties, which hitherto he has permitted to be set before us;
so that we can say, our lot is fallen in a good land.

And now brethren, this I write unto you, that your joy may be full,
who keep the word of faith delivered unto you, and stand by faith, in covenant with God,
holding fast your confidence in him without wavering, who is the head of our body,
as living members fitly joined together in the bond of peace and love.
Here we are one another`'s joy in the Lord,
and fellow helpers in the work and service of the Lord in our day,
against Babylon the mother of harlots,
who has adulterated people`'s minds and hearts from God;
and thus has made the nations drunk with her wine,
under every green tree that has sprung up since her reign.
She has prevailed, but her judgment is begun, her torment prepared,
and the cup of indignation is determined of God for her;
for the hour of her judgment is come, and the executioner stands at the door.

Therefore all the servants of the Most High, whom the Lord has redeemed by his power,
from under the power of the beast, abide in him, who is now come for judgment,
that his holy city may be redeemed thereby;
for the Lamb`'s wife is returned out of the wilderness,
and is adorning herself with the white garments of praise for the spirit of heaviness,
which has attended her in the long night of apostasy.
She is putting on her beautiful garments of righteousness,
and is nourishing her children with the sincere milk of the eternal word of life;
and they are grown strong in the Lamb`'s war,
to handle their spiritual weapons against the dragon and his power,
that has long reigned in the hearts of the sons and daughters of men.
They can no more war with flesh and blood,
but bend their bow against spiritual wickedness that has reigned in high places;
and this is the very nature and being of that spiritual life of the Son,
which the gospel day has brought to light.

Thus are the riches of the Gentiles brought, in the better hope and covenant,
than that which was made with Israel after the flesh,
which removed not the veil from their hearts, nor the curse from their tents;
but the Lord is come, who has taken away the veil which was over our hearts,
while Moses was read; this is the Lord`'s doing, by the finger of his right hand;
and it has had a marvellous effect in our day, to the gathering of many sons unto glory.
He has said unto the north, give up, and to the south, keep not back;
and many have heard his voice, and are come forth of the graves of corruption,
and have put on the beautiful garments of righteousness,
and are walking in their ranks and order,
up to the holy mountain of the house of the Lord,
giving heed daily to the instruction of the Almighty, by his grace and Spirit,
who now teaches his people to profit, and guides the meek in judgment,
and gives wisdom and understanding to the simple soul, who has no helper in the earth;
all holy living praises ascend unto him from the living,
whom he has quickened forevermore.

And now, dear Friends and brethren,
as the Lord has made you of the first fruits to his praise,
be all faithful and diligent servants and stewards in your Father`'s house,
and with girded loins attend upon your Lord`'s motion, word and call,
that you may be ready to answer him, in every service he has for you to do;
so shall you partake of the fullness and fatness of his house,
and he will give you your food in due season, and fill your treasures,
that you may have enough to give to them who need.
Of this I am a witness, who came from among you in much poverty of spirit;
but the Lord filled my basket in all times of need,
so that I had bread to administer by him to the hungry,
and water to the thirsty traveller, and enough for myself besides;
and by faith it was renewed every day, and increased with using.
And now I can say, that I have been young, and am now grown old;
yet I never saw the righteous forsaken,
though I have often seen them cast down for a time,
yet has a Divine hand been under their head,
by which they have been supported under all exercises.
The Lord has not allowed any to be tempted beyond what he has given ability to bear,
as their faith has stood in his power, and the word of his patience kept to the end.

This I write unto you that your joy may be increased,
and that you may perfectly trust in the name of the Lord,
and go forth in the power of his might, to war with antichrist,
and the power of darkness, that reigns in the hearts of the children of disobedience.
For the weapons of our warfare are not carnal, neither do we war with flesh and blood,
but against that enemy that has separated men from God,
and to bring to the peaceable Saviour,
who is now come to save men`'s lives from the destroyer.

In this peaceable life all live and walk, as you have had us for example;
that the Divine nature and property of the Truth,
may show itself forth in your lives and conversations, following peace with all men,
and holiness, without which none shall see God.
So shall your lives be pleasant, and your deaths peaceable,
though you may suffer reproach from men for a time.
Be not angry, or troubled at it, but count it your crown and joy in this life,
for the green tree endured greater sufferings, and thereby was made perfect;
"`and the servant is not greater than his Lord,`" nor more free than his Master,
from the woundings of the enemy; so with patience bear his yoke,
that with honour you may wear the crown.

The times and seasons are in the hand of the Lord,
and he disposes of the kingdoms of the world according to the good pleasure of his will,
and who shall say, What are you doing?
A sparrow shall not fall to the ground without his Divine providence.
Therefore, dear Friends,
trouble not yourselves about the transactions and changes among men.
For all those things must be; the world is grown old in iniquity,
and the workers thereof must be cut off;
"`The mouth of the Lord of Hosts has spoken it.`"
Touch not on the right nor on the left with those
dissensions that seem to infest the world,
for the wrath of man shall never work, nor bring forth the righteousness of God.
Neither shall wars with flesh and blood complete true and lasting peace on earth,
but righteousness shall deliver from death; the fruit thereof is peace,
and the effect thereof is quietness and assurance forever.
This is our interest, this is our all, the good old cause which Moses, Abraham,
and all the patriarchs, the true prophets and apostles laboured for in their day,
through the several dispensations of grace and life,
in which God appeared to them--the end and tendency of all was to turn many to,
and bring forth the righteousness of God, which the world, by their wisdom, never knew,
nor does to this day.
And that religion is certainly false, which is either set up,
or defended by destroying men`'s lives.
Therefore touch it not, but in the suffering seed of life let your dwellings be,
so shall you be fortified with the munition of rocks,
into which no destroyer shall enter.

And beware of, and watch against, that evil seedsman,
who would sow division and contention among you.
Crush that in the bud wherever it appears;
and let all private interests give way to the public good,
peace and tranquillity of the church of Christ,
and let all strife and contention cease about words, names or things.
Every post and pillar which God has not raised up will fall,
though it is set by the Lord`'s post; and every plant which he has not planted,
will wither and decay, and come to nothing, before the glorious Sun that is now risen,
which only will nourish, comfort and refresh those plants which stand in the good ground.
For both the good and bad ground have received the seed of the kingdom of righteousness,
and marvel not that it has contrary effects;
for all the parables of the ancient gospel must be fulfilled.
And also all the promises to the royal chosen seed of God,
which brings forth righteousness in all mankind where it grows and prospers,
the yes and amen is witnessed; and the spiritual ministration of life,
is now to be spread over the whole earth,
which will fill it with the knowledge of the glory of God, as the waters cover the sea;
the last and greatest that ever the world shall be visited with,
wherein God alone is known and worshipped, in and by his own Spirit,
by all who receive the manifestation thereof, given them to profit withal.
They alone shall know this heavenly treasure in their earthen vessels,
that the excellency of the power may be of God, and the glory alone be given to him,
who alone is worthy forever.

Here all man`'s inventions, human traditions,
willings and runnings must be laid in the dust; and he must see himself lost,
and not able to move one step towards his eternal felicity, by all his acquired parts,
wisdom and abilities; so the Saviour will manifest himself to him,
in order to redeem him.
For he is come to gather the lost sheep, scattered abroad in the nations,
who have no helper below him in the earth; but the whole need no physician,
who never knew a wounded spirit, nor a broken heart.
They do not know the Saviour come to bind up such, nor to save them,
but to feed them with judgment, and to give the cup of indignation into their hand;
and he will take the cup of trembling out of the hands of his obedient children,
and give it into the hand of those who oppress them.
Therefore my beloved Friends, live in all holy subjection to the Truth,
and follow your Leader, Christ, fully and faithfully,
in that ancient path of righteousness which he has set before you.
So shall the angel of his presence go before you, and be to you a fountain in the way;
for all religion without righteousness, is but as chaff which the wind drives to and fro;
and in a storm into holes and corners;
and none can adorn the Truth further than he walks in the way of righteousness,
the ancient path of Abraham, Isaac and Jacob,
and all the true prophets and believers in the gospel day, towards their eternal rest.

And dear Friends and brethren,
inasmuch as God has caused his glorious gospel day to dawn in your hearts,
walk in the light of the Lamb,
that the salvation of God may be as a wall and bulwark about you;
and your sons may be as righteous plants, growing up in their youth;
and your daughters as polished stones, beautiful to behold,
being clothed with the garments of praise, the robes of righteousness;
then God himself will be their lover.
This will be the glory of our offspring,
and will crown their gray hairs with immortal honour,
if they continue faithful unto death,
and walk in the righteous footsteps of their ancestors;
being girded about with the Truth, and their lamps burning.

This is the preparation of the gospel of peace and reconciliation in our day,
testified unto in the mouths of many witnesses;
and many virgins are now trimming their lamps, and waiting for the Bridegroom,
that they may enter with him into his rest, who have come through many tribulations,
and have now put on their beautiful garments of praises, and hallelujahs,
being made white by the blood of the Lamb,
and have received the oil of joy for the spirit of heaviness.
But in this state let all be watchful, and rejoice with fear and trembling,
that a defence upon all your crowns may be witnessed;
for there is danger in the sabbath-day, as well as in the winter;
and none can be preserved, but as they abide within the munition of the Rock of ages.
For strength, help and preservation are in him,
who is arisen to fan the nations with the wind of his wrath,
who have drank the cup of fornication,
and all the chaff he will consume with the fire of his jealousy,
and waste the nations with his righteous judgments,
that he may "`gather the wheat into his garner;`" for the earth is filled with violence.

But the peaceable Saviour is arising as a glorious Sun to
enlighten the earth with the knowledge of his glory;
and he will gather his sheep from the four corners thereof,
and bring judgment to the Gentiles,
for the recovery and redemption of Zion his beloved city.
Therefore you travellers,
who are coming up to the mountain of holiness where the Lord dwells; look not back,
nor downward to Sodom nor Egypt, out of which you are delivered;
nor have fellowship with the inhabitants thereof,
for they are the unfruitful workers of darkness;
but keep your holy fellowship and unity in the order of the gospel of peace,
in which is your strength, prosperity, growth and increase of life in him,
your holy Head, and in whom you have life, peace and rest forever.

And whatsoever has arisen,
or hitherto appeared to break or hinder our unity in the Spirit of life and Truth,
God has confounded, and it has withered as untimely figs;
and no weapon formed against us here, has or shall ever prosper;
for God will make his spiritual Jerusalem the praise of the whole earth.
"`Blessed are they who keep their habitations within the walls thereof.`"

And, dear Friends, though I have not outwardly seen your faces many years,
I would not have you therefore think that I am dead; for I bless the Lord,
I live by the faith of the Son of God, and my life is hid with Christ in God.
But consider, I have had many years the charge of a considerable family,
beyond many of my brethren, which the Truth engaged me to take care of;
and I have been in eleven prisons in this county, one of which held me ten years,
four months and upward, besides twice premunired, and once whipped,
and many other sufferings too long to relate here; but blessed be the Lord, my labour,
travels and sufferings have not been in vain,
for many have been thereby gathered to the true Shepherd`'s fold,
where they are laid down in rest and peace.

I could rejoice to see your faces,
but cannot bear to travel far by reason of my infirmity;
the harvest is great and the labourers are but few with us;
yet of late some young ones are raised up to be fellow helpers in the gospel testimony,
at which my soul rejoices.
I have lived to see the desire of my heart in measure answered,
and am thereby greatly satisfied,
and hope yet to see the beams of the glorious Sun of Righteousness arise and
break forth more and more in the hearts of the sons and daughters of men,
and the way of holiness opened to them, who yet sit in the solitary places of darkness;
this I long for more than my daily food.
For the earth can never enjoy her sabbaths again,
till the righteousness of faith is established in it;
and nothing short thereof can produce peace on earth and good will to men;
this the Lord has made us witnesses of in our day.
And that the glory and beauty of true Christianity can never
be restored to the nations and kingdoms of the world,
so much now lost and decayed, till they be turned to,
and live the life of righteousness and holiness;
then they will all see the God who made them.
This was the beauty of the ancient gospel Christians,
who were baptized into the death of Christ,
and so were made partakers of his resurrection.
This is the baptism that now saves all the true followers of the Lamb,
in the strait way of self denial.
Here the unclean cannot walk, nor the defiled enter;
it is only open and easy to the redeemed,
whose garments are washed in the blood of the Lamb,
being come through many and great tribulations.

Oh, Friends, walk in the gospel day, and "`love one another,
as God for Christ`'s sake has loved you;`" and let no rent or schism break in among you;
but let the seamless garment cover you all, that your nakedness may not appear to them,
who are without.
Your unity in the Spirit of Truth, is your strength,
which if you keep in the bond of peace, you shall do well.
For the great work and design of the adversary is, in this day,
to break in upon the heritage of God, and break their ranks;
but in vain is the snare laid for them, to whom God has given sight.

And now, dear Friends and brethren,
I once more salute you with the salutation of my endeared love,
which often flows towards you, and commend you to the grace of God,
which is sufficient to preserve you blameless until the coming of our Lord Jesus Christ,
to whom be glory, praise, power and dominion forever.
Amen.

I am your brother and fellow servant, in the labour of the gospel of peace,

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
Rigate, this 16th day of the Tenth month, 1692.

[.blurb]
=== A Visitation of Tender Love From the Lord unto Charles II, King of England, Scotland and Ireland

Let the consideration of these following lines deeply sink into your heart,
for they are things of great importance to you at this day.
There is a people within your dominions, called Quakers,
whom the God of heaven highly esteems, in whose hearts he has placed his holy law,
according to his promise by the mouth of his prophets, which is, and has been,
their schoolmaster and leader unto Christ, according to the testimony of Paul,
his servant.

For their obedience to which law,
this people has undergone many great trials and tribulations,
both before and since your coming into this nation to rule as king,
which they have patiently borne, without avenging their own cause,
till the Lord did arise and plead with their enemies,
which he has done to their confusion and overthrow, even without remedy.
And this poor people were never known to provoke
the worst of their enemies to wrath against them,
unless by their honest conduct before them, coupled with God`'s fear and reverence,
which is of great price in his sight, though not valued in the sight of men;
for which they have suffered deaths often, long and sore imprisonments,
and great spoil of their goods, stoning, stocking, whipping and cruel mockings,
and much more, which is too tedious to mention,
for their due obedience to the royal law of God, and the weighty commands of Christ.
They have been denied the liberty of thieves and murderers, for their loyalty thereunto,
by them who were in authority before your coming in;
which God took occasion to destroy with remediless misery,
as a just reward of their ungodly deeds.
Then he remembered you,
whom he had allowed to be oppressed by the afore-named task-masters,
and did raise you from a low state, in which state when you were low,
and in the sense thereof,
you promised much liberty to these harmless lambs of God`'s fold, saying,
they should not suffer for their religion, so long as they did live peaceably;
and much more, which may be seen abroad in public view.

Yet notwithstanding, their sufferings are much more increased under you, than before,
and you have broken your word and promises to them,
though they have kept faithful and true unto you,
and have not broken the peace of the kingdoms under you, nor any of your just laws,
but have laboured by all lawful means to live a peaceable and quiet life under you,
in all godliness and honesty.
Yet how great is the cry of their oppression in this nation at this day,
from the one end thereof to the other?
They are appointed as sheep for the slaughter,
even while they who work wickedness are set up in high estimation.
All of which the righteous God has regarded, and his soul is greatly grieved every day;
and if these things be not speedily amended,
he will visit you and the whole nation in his hot displeasure; these,
and such like evils, were the overthrow of many great kings in the days of old,
whom when they forgot God and his cause, and oppressed and persecuted his people,
he did blast in their chiefest glory, and laid their honour in the dust.

So in all love and tenderness of heart consider what you have done, and are doing,
and remember your covenants with God and man in your low state,
and let it be in no man`'s power further to charge
you with the breach of your word and promise.
Permit none to be oppressed for conscience sake in your dominions,
that do not disturb the peace of the kingdom,
as you will answer the contrary before the righteous God.
This can never be a good ingredient to to your future security with God or man,
neither will God ever bless you, or prosper your way in anything of this nature;
for his people are his portion which he has called and chosen,
and woe to all their enemies.
He that offends one of them,
it were better for him that a millstone were hanged about his neck,
and he cast into the midst of the sea.
And if any counsel you to vex and scourge the afore-named lambs,
such are your mortal enemies; and if you do hearken and obey them, it will bring shame,
reproach, confusion and desolation unto your crown and dignity.

Therefore be wise, O king, and recollect your memory while you have a day and time,
and consider your former engagements,
and also your father`'s and grandfather`'s charges laid upon you concerning these things,
and let love and mercy establish your throne, that your days may be prolonged.
Be not not high-minded or stouthearted against any;
that will never draw the hearts of your subjects to love you;
and so long as you allow the wicked to tread down the heritage of God,
you shall never have his countenance upon you,
but his displeasure shall attend you in your most secret chamber,
and at last he will give you up to be a prey to your enemies,
even as he has done to many before, who rejected his counsel,
till his wrath sealed the truth of it in their bosoms.
Oh the cry of cruelty and oppression that is everywhere!
What will be the end thereof?
None is now esteemed, but such as can run greedily into iniquity,
and drink it up as the ox drinks water.
The nations are in a flame,
the fire of God`'s jealousy is kindled in every city and town,
even prepared to burn up all his enemies; and the iniquity of rulers, priests and people,
does blow it up day and night, that it cannot long be stayed,
unless it be speedily quenched by tears of unfeigned repentance;
for the hour of God`'s judgment approaches,
and the execution will speedily follow if not prevented.

This in short, I was moved to write unto you in true love,
who am and have been a sufferer under you for the testimony of Jesus; being no enemy,
nor ever was to you, that you may not run upon that which will be your final destruction;
but if you do reject the day of God`'s visitation in mercy to you,
he will take you off in his hot displeasure.
So the Lord open your eyes to see the things that belong to your peace,
before they be hid from you.

This was laid upon me once more to lay before you without flattering titles,
who am one of your suffering subjects, known by the name of

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
This was written the 2nd of the Seventh month, 1662.
