[quote.epigraph, , Ps. 37:18]
____
The Lord knows the days of the upright,
and their inheritance shall be forever.
____

[quote.epigraph, , Heb. 13:7]
____
Whose faith follow; considering the outcome of their conduct.
____

== Chapter I

[.chapter-subtitle--blurb]
A True Relation of the First Manifestation of the Love of God in Christ Jesus unto Me.

To the best of my remembrance, when I was about ten or twelve years of age,
the Lord touched my heart with a sense of my latter end,
which I often deeply considered when I was at the free-school among my school-fellows.
I often thought of my Creator, and of his great work in the creation,
and that to him all must give an account of their deeds, whether good or evil;
yet being daily conversant with my playmates, I was led into looseness and play,
and many youthful pleasures, in the midst of which I was often smitten by the rod of God,
though I knew him not.
Yet one thing did somewhat comfort me,
that I abhorred vain and desperate oaths and drunkenness,
which I saw many were swallowed up with, who were my companions;
for there was a hatred in my heart of such things.
Being brought up to read the Scriptures from a child,
and thinking therein to find something of life;
but being a stranger to Him in whom life was and is,
I was still in darkness and the region of the shadow of death.
Yet I found them declaring of the day of the Lord that should burn as an oven,
wherein all the proud, and all who did wickedly, should be as stubble,
and the day that comes should leave them neither root nor branch, Mal. 4,
and many such places; which I believed were true, and would come to pass.

Notwithstanding I was not so overcome of gross evils,
yet I daily found sin reigning and ruling in me,
and leading me captive into various lusts and vain pleasures,
which became my great burden;
under which I often groaned and cried to the Lord for deliverance.
But being in the kingdom and power of darkness, I saw no way of deliverance,
but still remained under the bondage of corruption.
Then when I could write, I took much delight in writing the priest`'s sermons,
and as I went home got them by memory, so that I had gathered much into my knowledge,
but still remained a stranger to the life of Christ, which my soul breathed after,
and was without God in the world, wandering from mountain to hill,
yet found no rest for the sole of my foot.

In this condition I remained till I was sixteen years of age,
running from one high-priest to another,
expecting to receive that from them which my soul thirsted after,
but still remained unsatisfied.
They were to me physicians of no value,
though they bid me apply the promises and get faith.
Yet both they and I being ignorant of the word of faith, which the apostle preached,
near in the heart, Rom. 10:8, through the hearing of which,
faith comes to be received; I knew not that unto which the promise of life was,
and found that ruling in me unto which the promise of life was not.
So that whatsoever plaster was applied to me while the corruption was not purged out,
was of no value as to my cure; for, from the crown of my head, to the sole of my foot,
I was full of bruises and putrefying sores, so that I was often loathsome to myself.
Yet not knowing how to be healed, I sought further,
and met with some books that did somewhat suit my condition,
which I took delight to read, and gathered a form of prayer,
which I often used in private, with many earnest breathings to the Lord,
that if he had any blessing to bestow upon me on earth,
he would show me his way of Truth.
For I plainly saw that many of the priests were as bad as myself, and some worse,
and so could expect no good fruit from evil trees.
Then I turned from them, and went after others, who were a little more refined,
and thought from them to have more satisfaction, but found none,
but was sensible that my wounds grew more and more putrefied;
and that which the best of them had applied, proved no relief at all to me,
nor proper at all to my distemper.
So then my soul often mourned to the Lord in secret, for the knowledge of his way,
desiring neither riches nor honour in the world;
but that I might know the good Physician, who could make me every whit whole,
which was of more value to me than all the treasures of Egypt.

Though some youthful pleasures prevailed over me,
which kept me above the witness of God in me, yet had I secret reproofs,
which caused sadness in the midst of my joy.
And though I was as a wild heifer, unaccustomed to the yoke,
yet I was always preserved from gross evils, by him whom I now knew to be my strength,
though I had many occasions and provocations thereunto, glory, honour,
and living praises unto the Lord God, and to the Lamb forevermore.

[.blurb]
=== The Way and Manner of my First Coming to the Knowledge of the Truth, and Way of Peace, Which had been the Breathing of my Soul from my Youth

After my long travail in the night of darkness and ignorance,
wherein I had toiled and taken nothing,
it pleased the Lord in his infinite goodness and tender mercy to me and many more,
to send his true and faithful messenger, George Fox, into our parts,
who published the everlasting gospel.
He said we had a light, unto which we did well to take heed, until the day dawned,
and the day star arose in our hearts; which was glad tidings to us,
who so long had sat in darkness and blindness of mind.
This testimony I then both believed and received, not because it was his testimony alone,
but because it was indeed the testimony of the word of God,
which became quick and powerful in me, and sharper than a two-edged sword,
to the cutting down of the man of sin, which had long ruled in my heart;
with which there was a great and long warfare before the strong man was overcome,
that a stronger than he might rule.

Many and strange were his wiles,
and strong was his temptation to overthrow that little measure of faith,
which the Lord had wrought in my heart by hearing the word,
through which I came to have some small victory over him and his power,
by which he had long led me captive at his will; but as I took heed to the word of faith,
which was near in my heart, the day began more and more to spring from on high,
and the day star to appear in my heart.
Then the foggy mists of the night began to vanish away, and the day star went before me,
till it led me to see him, whom I had pierced.
And then a day of bitterness came upon me, and I was in sorrow as a man for his only son,
and judgment began to be laid to the line in me, and righteousness to the plummet;
so that I said in the morning, would God it were evening; and in the evening,
would God it were morning, for fear of the Lord, and for the glory of his majesty,
who was arisen to shake terribly the earth.
But in the midst of all, it was said, "`I will not break a bruised reed,
nor quench the smoking flax, till I have brought forth judgment into victory.`"
In the belief of this, I waited long upon the Lord in the way of his judgments,
until I felt his mercy spring unto me, which was manifested in me.

So then I became as a stranger to my near relations; for my father and mother forsook me;
my friends and acquaintance stood afar off, wondering at me, and I was a hissing to many;
and I was sorely beaten by those who formerly would have hugged me,
because I now feared the Lord, and trembled at his word; yes,
and at the last I was cast out of all which might administer comfort to my outward man;
so that for some time I had not whereon to lay my head.
Then I walked about in solitary places, being compassed with many and sore temptations,
both inwardly and outwardly; in the midst of which, the Lord spoke comfortably unto me,
and said, "`Fear not,
I will be with you and care for you;`" which did refresh my soul and bear up my spirit.
But sometimes looking out at the prosperity of the wicked, my foot had nearly slipped;
and even more so, considering the many troubles that I was compassed with.
But the good Shepherd drew me in again with his crook,
and made me lie down among the sheep of his pasture,
where I found fresh pastures and living streams,
which renewed my strength as the morning; and I became strong in spirit,
and in the faith of the Son of God,
by which I obtained victory and freedom in my own particular,
over that which long had victory over me.

Yet, as I said above, my father and mother stood far from me,
and I became as a stranger to my mother`'s children; but the Lord regarded me,
and had respect unto me, and gave me more and more of his good Spirit to direct my steps,
that my feet did not slide.
Often, when I was alone, temptation was sore upon me, and did strongly beset me;
yet I still did resolve in my breast to follow the Lamb wherever he went;
and whatever sufferings overtook me, I would never deny the Truth,
which the Lord had so clearly manifested to me.
Then I concluded to go to London and take some employment among Friends;
and something was very forward in me so to do; but yet the Lord would not allow me,
but counselled me to stay and wait, until he called me forth.
So I waited a season, and at length the word of the Lord came unto me, which said,
"`You shall go forth into the south to be a witness unto my name,
for which you shall suffer many things; but I will be with you.`"

This seemed hard to me at first; and I could much more willingly have stayed at home;
so I bore and weighed it a pretty while, before I related it to any,
yet never concluding to disobey the Lord`'s word, whatever I suffered,
if I saw him still requiring this of me.
At length I was greatly pressed in spirit day and night, so that neither my sleep,
nor any other enjoyment was pleasant to me,
till I freely gave up to part with all to follow the leadings of the Lord.
When I did freely answer his requirings, I felt his arm stretched out over me,
and the light of his countenance was upon me;
so that the parting with my father and mother, my friends and acquaintance,
with my native country, was little in comparison of that joy which was set before me.

Then was a fellow traveller prepared for me, namely, Thomas Robertson of Westmoreland,
who was made willing to leave his dear wife and tender babes,
to go with me into the Lord`'s harvest.
We took our journey about the time called Easter, in the year 1655,
and through much reproach and hard travel on foot, came to London;
and after a little stay, it was upon us to pass further southward.
So early in the morning we took water, and passed down the Thames, towards Gravesend,
and in the boat were various passengers with us, who perceiving what we were,
did exceedingly scoff, and shamefully entreat us,
till on a sudden a great ship came running with full sail before the wind,
and was near to run over the boat in which they and we were.
This did so terrify them, that their laughter was turned into fear and horror,
which made them quake far more than us, whom before they had reproached under that name.
The danger was so imminent, that the boatman had much ado to save himself;
yet the Lord delivered us, and brought us safely on shore at Gravesend,
and from there we travelled to Rochester;
where it was laid upon us to go to a Baptist meeting,
at which we were apprehended by soldiers, and brought before the governor,
who examined us, and finding we were north countrymen,
said we might pass no further without a certificate, and committed us prisoners.
But there being one of our own countrymen, a soldier in the place,
who gave testimony of our honesty in our own country, we were freed;
but much tempted to go back into our own country again,
for they told us many dangers were before us, if we went forward.
Yet we consulted not with flesh and blood, but went forward in the name and power of God,
till we came to Dover, where there was an open door to us,
and the Lord also opened our mouths to publish the everlasting gospel,
though in weakness, fear, and in much trembling;
yet thereby several were turned from darkness to the light,
and from the power of Satan to God, in order to receive remission of sins,
and an inheritance among the sanctified.

From there we came to Folkstone, where some received us and believed,
and were gathered to God.
And we passed to Hyde and Rumney, where several received our testimony,
unto whom the arm of God was revealed,
through which they were gathered from the barren mountains into the low valleys.
At Lydd we found Samuel Fisher, a pastor of a congregation of the Baptists,
with whom we had discourse, he being a great scholar,
and having formerly been a parish priest,
but one who waited for the coming of the kingdom of God in power.
He received our testimony, and was willing to become a fool,
that he might be made wise to salvation, and from a teacher came to learn,
and so received wisdom and spiritual understanding,
to become a preacher of righteousness, in which he lived and died.

After his convincement we came to Staplehurst,
where we found a great congregation of Seekers, so called,
among whom we had good service; many of them being convinced, with their teacher,
his wife and children, who lived and died in the faith.
The harvest grew so great, and the labourers being few,
we were forced to separate one from the other;
and one of us to take that care and charge which both did before.
But after we had a little cleared ourselves of that county,
it was upon us to pass through the western counties nearly two hundred miles,
to proclaim the acceptable day of the Lord in towns, cities and villages,
which we gave up to do.
Being parted one from the other,
Thomas Robertson was two or three days`' journey before me;
but both of us being as strangers and pilgrims in the earth,
and having none to direct us but the Lord alone,
we were driven to many straits outwardly;
but in all we were supplied with courage and strength
to undergo whatever was laid upon us.

Thomas Robertson passed before me through the county of Sussex,
only I heard of him accidentally near Chichester, at a house by the way side,
at which I called to get a little water to quench my thirst.
The woman began to tell me of a man who called there two or three days before,
whose words gave me to understand that it was my companion.
When I had drank, I passed into the city on the seventh-day at night;
and on the first-day I was moved to go to the Baptist meeting,
where I declared the word of Truth, though with much opposition;
which testimony some received, and some rejected.
But after a little time the mayor of the city, having notice given of me,
sent the constable to bring me before him.
When I came without respecting his person by putting off the hat, he was in a great rage,
and sent for one called a justice; who, when he came, took off my hat himself,
and commanded men to search me, saying, I was a Jesuit, or one come from Rome;
and would have committed me to the Gatehouse forthwith, but the Lord turned their hearts;
so that after some discourse they freed me.
After which I got a meeting at the inn;
so the next morning I left the city and came into Hampshire,
and from there into Wiltshire, and all through the country till I came near to Bristol,
before I saw the face of a Friend.

The strength of my body was nearly spent with travel; but meeting with some Friends,
I was revived and strengthened; and staying there a little space,
I was pressed in spirit to go forward.
I came to Bristol, and from there to Exeter,
where were two brethren of my country in prison; and going to visit them,
Thomas Robertson and I met together again in safety, after our long journey,
and in that city we stayed some small time, declaring the Truth;
but they stopped their ears, and hardened their hearts against truth and us;
so that we shook off the dust of their city as a witness against them,
and came away again for Bristol, where we had service.

From there we came to Reading, and stayed a little season;
and from there we were moved to go to Basingstoke in Hampshire, where,
through some difficulty, we obtained a meeting;
but before the people were all come together, the chief priest and rulers came,
who caused us to be haled out of the meeting, and tendered us the oath of abjuration;
and because, for conscience sake, we could not swear,
they carried us forthwith to prison.
But before they put us into the room, they separated us one from the other,
and searched us, and took away our money, linen,
and ink-horns--then they thought of some way to keep us apart;
but not having two rooms bad enough, they thrust us down together into a low strait room,
and locked us close up,
and appointed two rude men with halberds to watch over us within the prison all night,
and in the morning freed them, and shut us close, and gave a command,
that if any of our friends came but upon the ground, before the prison-door to visit us,
they should be fined.

There they kept us nearly three days before they brought us our money;
in all which time we could not call for any necessaries, because we had no money,
and we could not eat any man`'s bread for naught.
When the people cried out upon them, they brought us our money;
and the jailer would have eight pence a night for a nasty bed which stood in the room;
and when we could not satisfy his desire, he caused it to be taken away.
So we got some straw, and laid upon it all the time we continued there.
The jailer caused boards to be nailed before the window, that we might not see the light,
and at night would not allow us to have a candle or fire.
All of which we bore with patience, till they were weary of their cruelty;
by which several, both in town and country, were convinced of the Truth,
and remained therein.
And there they kept us nearly a quarter of a year, and at their sessions freed us.

When we were clear of the town, we were moved to pass for Southampton,
where the Lord opened a door unto us, and his word was effectual in us,
to the turning of a remnant from darkness to the light, who walk in it to this day.
Thomas Robertson left me, and went to Portsmouth, and gave a testimony there,
after whom I went and stayed near ten days, and had good service.
On the first-day I was moved to go to the steeple-house,
to bear testimony against their worship, at which the priests and rulers were offended;
and on the second day, as I was passing out of town, I was apprehended by soldiers,
and had before the governor, who would have prosecuted me as a vagrant,
but could not find matter enough so to do, but sent me out of town with a constable;
but after a little time I returned again,
and then they received the word of God with gladness,
and a meeting was established there.
With much difficulty I got into the Isle of Wight,
where some were added to the Lord`'s flock,
and the Lord delivered me out of the hands of unreasonable men.
From there I came over into Hampshire, and passed from town to town,
and from village to village; and the Lord was with me,
and made his word effectual in my mouth, to the turning of many to righteousness,
in which they were established.

After I had continued among them for a season, I came into Sussex,
where I had good service, and a great gathering there was to the Truth;
and many received the word of God with joy, and met often together;
in whose meetings God manifested his presence and power in a large measure,
among whom my soul was refreshed.
But after a little time I was moved to go back again into Hampshire,
to water the tender plants there.
When I had done this, I was pressed in spirit to go into Dorsetshire,
to Weymouth and Melcomb-Regis; and there I was moved to go to a steeple-house,
to declare against a hireling priest; for which I was apprehended,
and carried to a nasty prison underground, where I had neither bed, fire,
nor anything to sit down upon but a stone; and a heap of filth was in one corner of it,
and some nasty straw, where seamen had laid in.
There I was kept two or three days; but I could look up,
and see the people in the street, and there I had good service,
and preached the Truth to the tendering of many.
And from there I was sent to Dorchester, to the county jail,
where was a terrible sickness, which some called the plague,
which swept away most of the prisoners.
But the Lord was with me there, and kept me in the hollow of his hand;
so that a hair of my head was not hurt.
There I was kept eleven weeks, where I had very good service for the Lord,
to the convincing and confirming of many in the Truth,
in which they have now found rest for their souls.

When I came to that prison, I found my dear brother Humphrey Smith there,
who took the sickness of the prison, and was very near death,
unto whom I was greatly helpful, for he was not willing to take anything but from me;
but the Lord raised him up again.
Joseph Coale and William Bayly were sent prisoners there also,
but we were all preserved and delivered by the mighty arm and power of God.
And from that imprisonment also the Lord set me free; and while I was there,
preserved me from that raging disease, which swept away many in a small time,
giving me assurance, that a hair of my head should not fall without his notice,
which was fulfilled to the utmost.
For though I was in many dangers of sickness in that prison,
besides the contagious disease; yet I was never better,
nor more healthy than while I was there;
blessed and praised be the name of the Lord forever.

When I was delivered, I went and laboured again in the vineyard of the Lord,
and came to Weymouth and Melcomb-Regis, from which place I had been sent to prison,
and there I had good service for the Lord among his flock.
Being clear of that place, I departed in peace, and came to Corsetown,
in the Isle of Purbeck, where I was resisted,
and by force of armed men kept out of the town, the inhabitants pretending a fear of me,
as I came from among so many infected persons in the prison.
I not being willing to bring any danger among them, departed and came to Poole,
where I was gladly received,
and there I continued a few days in the labour of the gospel,
confirming them who had heard the word of God and believed.
From there I passed to Ringwood, where I found a few who believed the Truth;
among whom I gave testimony of the same, to the establishing them in the faith,
which was begotten in them by the word of Truth.
Then I came to Southampton, where I had formerly laboured;
and I was much refreshed among the plants of God,
who rejoiced and praised God for my deliverance out
of that dangerous prison before mentioned.
I preached the word of God with a ready mind,
and had many large and precious meetings in the surrounding country also;
and the word of the Lord grew, and many came to believe the Truth.

In Southampton I was moved to go to a steeple-house, where one Nathaniel Robinson,
an Independent priest, was speaking a divination of his own brain;
and after he had ended, I desired to be heard a few words in the fear of God;
but he fled and left me to the mercy of his rude hearers,
who with violence haled me out of their synagogue;
and the said Nathaniel Robinson caused the rulers to send me to prison,
where I continued a very close prisoner;
and when some of my Friends came from the country to visit me, they abused them,
and shamefully entreated them at their inn, and in the streets also.
One Edward Southwood, being a soldier in the army,
and having leave from his officer to come to visit me,
they caused him to be apprehended in the inn, and took his arms from him,
and would not allow him to come into the prison to me; but over all their cruelty,
the Lord kept him,
and gave him patience to bear what they were permitted to inflict upon him.
They allowed very few to come to me, yes, scarcely those who were to bring me necessaries.
All of which I suffered till the Lord set me at liberty over all their cruelties.

Then I began again to labour in the Lord`'s harvest, and he was with me,
and gave me power to undergo whatever he permitted to be laid upon me.
I was moved to go into the Isle of Wight,
and purposed to have gone on board at Portsmouth, but was stopped by the governor.
Then I came back again to Southampton, and from there to Hurstcastle,
and there I met with some Baptists, with whom I had a conference;
and understanding where I was to go, after I had got under sail,
they betrayed me to the muster-master,
who caused the master of the vessel to put me ashore again.
So there I was out of all hopes of having any passage;
and was forced to come back through the forest that night in much rain to Limington,
where I procured passage in a boat that went with faggots.

In the night season, and about the 10th or 11th hour, we landed in the Island.
I took up at an inn that night, and in the morning I went to Newport, their chief town,
where the professors were rich and full, and rejected the counsel of God,
and despised his messenger sent to them in tender love.
I declared the word of Truth among them as it was upon me;
but before I passed out of the Island, I was seized on by the soldiers,
and carried to the castle at Cowes, and the governor sent me out of the Island;
but I not being clear, returned again after a little time,
and there was a small remnant gathered, among whom I travelled through many hardships.
In that Island I was imprisoned in a filthy cold prison, in the middle of the street,
in their great town, where I had good service.
And when they perceived that, they put me in another prison, in a back room,
where I could not see the street, nor people come at me, where they kept me some time.
Yet at length the Lord delivered me, and there was a meeting settled.

About that time a law made against vagrants was perversely executed against Friends,
who were taken from their own homes or dwelling places,
by which many innocent men suffered who had good estates;
and some it was said in the very parish where they were born,
if they were taken in another.
Coming to Southampton, where some Friends were put in the house of correction,
I presently going to see them, was apprehended by the officers,
and with great abuse thrown headlong into the cage; and without any further examination,
the mayor granted a warrant to whip me at the whipping post in the market-place,
which was executed by the hangman accordingly in a cruel manner.
After this they threw me across a handbarrow,
and carried me along the streets between two men, and then threw me into a cart,
and drew me out at the gate, in cold, snow, and frosty weather,
without the least refreshment, and so drew me to the next tithing that night;
their warrant requiring me to be carried from tithing to tithing,
till I came at my own parish.

After I was gone, the mayor, whose name was Peter Seale,
threatened that if ever I returned again, I should be whipped a second time,
and burned in the shoulder with the letter "`R`" as broad as a shilling;
the other magistrates would not join with him in the work he had undertaken.
But before his warrant had got me twenty miles, the Lord overthrew it,
and delivered me out of their hands;
and in a little time I was moved of the Lord to go to Southampton again, which I did,
and had several meetings, and no man laid hands on me;
and then in my freedom I went out again, and laboured in the Lord`'s work,
and it was upon me to come to Southampton again.
I had only been come in a little time,
till the constable took me and carried me before the aforesaid mayor,
who was in a great rage, and threatened to execute the rigour of the law upon me;
and in order thereto, sent for a justice of the town, but he being more moderate,
and having no hand in his former proceeding, discouraged him so,
that he was forced to let his work fall, and after much ado he let me go free.
In a little time after he was smitten with a bloody flux,
which all his physicians could not cure, but shortly ended his days in misery;
and the constable, who was his chief agent in his wicked proceedings,
the hand of God fell upon him and his family,
so that he was forced to fly out of the town and died miserably.

I had peace and freedom a considerable time after, till King Charles II was restored;
but in the same year he was crowned,
I was taken upon the road at Petersfield in Hampshire, and there before Humphrey Bennet,
and John Norton, called justices, I had the oath of allegiance tendered me.
And because for conscience sake I could not swear,
they condemned me to the common jail at Winchester, and took my horse from me;
there I continued till the court sessions,
and then was run to a premunire by judge Foster and Tyrrell,
and committed close prisoner, and in the jail suffered many abuses from the prisoners,
by the connivance of the jailer; till the king freed me by proclamation,
and they were made to deliver me my horse again,
and then I travelled in Truth`'s service, in several counties, for a pretty season,
till the spring.

In the year 1662, I was at a meeting, at Captain Thomas Luxford`'s house,
at Hurst Pierpoint in Sussex; and by the instigation of Leonard Letchford,
priest of that place, I was apprehended and carried before Nisell Rivers, Walter Burrill,
and Richard Bridger, called justices, who tendered me the oath of allegiance;
and because I could not for conscience sake swear, they committed me to Horsham jail,
the 28th day of the third month, 1662, where I continued till the assizes,
and before Samuel Brown, then judge, I was premunired.
By the instigation of the aforesaid Leonard Letchford, I was continued close prisoner,
where I continued above ten years, under many sore abuses in the prison,
from several cruel jailers, but the hand of the Lord overtook them,
and cut several of them off while I continued prisoner there.
I was freely resigned up to suffer all the days of my life,
if it was the will of the Lord to allow it, seeing no way of deliverance from man,
in whom I put no confidence; but with a godly confidence,
was resolved to wait in patience all the days of my appointed time.

At length, when I least expected my deliverance, the Lord brought it to pass,
and opened the heart of the king to grant my liberty by patent, under the great seal,
with many more who suffered for the testimony of a good conscience.
In the time of my imprisonment,
the aforesaid Leonard Letchford sued my wife by her maiden name, for tithes of land,
for which he had kept her father prisoner several years, and sent her to prison also;
and at the assizes got a false verdict against her,
and took out an execution against her, with which he sent the bailiffs,
and took my goods that I had bought and laboured for with my hands in prison,
leaving us not a bed to lie upon, nor any other necessaries to assist us in prison,
that they cared to carry away, to the very pot that we borrowed, while prisoners,
to boil our food in; all which I could easily have recovered by law,
when I was freed out of prison; but I freely committed my cause to God,
to whom vengeance belongs.

In a small time, my father-in-law, Thomas Luxford, was freed also,
whom the said Leonard Letchford had kept many years in prison,
who boasted that he had laid us so fast, that the king should not free us.
And if we had but a little liberty granted us, once in a twelve month,
to go to visit our families, he sought out many inventions to have the sheriff fined;
and thereby incensed the jailer to keep us close;
and made many applications to the worst of the justices,
who he thought were most bitter against us, to add affliction to our bonds;
but he lived to see us both freed out of prison to his great torment,
as he expressed through various ways.

The said Thomas Luxford has also suffered many years,
for refusing to send in arms from year to year,
to the value of between twenty and thirty pounds, for which, one year,
they took away his wife`'s bed and bedding, as soon as she was risen out of it,
for one year`'s tax for drums and colours.

After I was freed out of prison at Horsham,
I continued with my family in the town about a year,
and then removed to Gatton in Surrey, where I continued about fourteen years,
where Robert Pepys the priest excommunicated me, my wife and servants,
for not coming to the steeple-house, and afterwards sued me in the Exchequer, for tithes,
and for the value of twenty shillings ran me to a writ of rebellion,
and so to a sequestration, and seized my goods to the value of sixty pounds.
Many other sufferings and exercises I had there, but the Lord was with me,
and delivered me out of them all; and much good service I had in the country there about;
and many were gathered to the Lord, and established in the faith of the gospel.
