== Chapter V

=== To all Rulers, magistrates, Priests and People, who Profess the Scriptures to be their Rule, Throughout the Nation of England; but More Particularly to the Magistrates, Priests, and People of this County of Sussex, who have had Any Hand in Oppressing and Persecuting of them whom God has Sent as Strangers Among them, in Tender Love and Pity to their Souls, to Turn them to Righteousness, Through Which they may See how Far they are From the Practice and Command of the True Christians, Mentioned in the Scriptures of Truth.

Throughout all ages and generations,
he that was born after the flesh persecuted him that was born after the Spirit;
even so it is now, as this last age of ours has fully manifested,
which has brought forth much cruelty and persecution,
that has been inflicted upon many for the answer of a good conscience;
but more especially upon them whom the Lord has called from their own
country to bear witness unto his Truth and righteousness in the earth;
for which testimony alone they have undergone a great
fight of affliction from the chief priests and rulers,
throughout most counties of this nation, as hundreds can witness.

But now I shall unfold the proceedings and dealings of the priests and rulers,
of this county of Sussex, towards me, who came as a stranger among them,
not wronging any man of anything, nor eating any man`'s bread for nothing,
but freely declaring the message of the everlasting gospel among them,
according to the word and command of God unto me,
when he led me from my own country and father`'s house above seven years ago,
much contrary to my own will.
In this testimony the Lord promised to be with me in all my trials and sufferings,
though ever so many and great,
charging me to take no thought beforehand what I should say,
when I was brought before rulers and governors for his name and gospel,
for he would direct me in that hour,
and give me a mouth and wisdom to answer all my adversaries; which promise and word,
I set to my seal, he has fully performed and confirmed to this very hour.
For he never yet has permitted the devil to draw me before any rulers,
or to cast me into prison, without his presence being with me,
and his right hand upholding me, to the confusion of all my adversaries; glory, honour,
and living praises and thanksgiving, be unto him forevermore;
in whose name I perfectly trust, and I hope shall unto the end, whereby I have been,
and am kept safe from the fear of evil.

I shall fully demonstrate unto all sober people,
who have but the least measure of Christianity left in them,
how far contrary to the Scriptures of Truth,
the rulers and priests of this county have dealt with me
for obedience to the word and command of God.
In obedience to this, I came among them as a stranger,
according to the practice of the true ministers of Christ throughout the Scripture,
who vexed and oppressed me contrary to the word and command of God, Ex. 22:21,
who said to Israel, You shall neither vex a stranger nor oppress him,
for you were strangers in the land of Egypt.
For their disobedience to which, the wrath of God arose against his people,
till there was no remedy, even because they mocked his messengers,
and despised his words, and misused his prophets whom he sent unto them in compassion,
as he has done at this day, 2 Chron. 36:15-16. And again,
the Lord warned them not to vex a stranger, saying, If a stranger sojourn in your land,
you shall not vex him, but the stranger that dwells with you,
shall be as one born among you, and you shall love him as yourself, Lev. 19:34.

And Moses said, The Lord does execute the judgment of the fatherless and widow,
and loves the stranger, in giving him food and raiment; and said,
Therefore love the stranger, for you were strangers in the land of Egypt, Duet. 10:18-19.
And, the Lord preserves the strangers,
and relieves the fatherless and widow, but the way of the wicked he turns upside down,
Ps. 146:9. And Christ said to them on his right hand, Come you blessed of my Father,
inherit the kingdom prepared for you, from the foundation of the world.
For I was hungry, and you gave me food; I was thirsty, and you gave me drink;
I was a stranger, and you took me in; who answered, When did we see you hungry,
and fed you?
or naked, and clothed you?
or thirsty, and gave you drink?
or a stranger, and took you in?
Who said, Inasmuch as you have done it unto the least of these my brethren,
you have done it unto me. Matt. 25:34-40.
But to the wicked he said,
Depart from me you cursed into everlasting fire, prepared for the devil and his angels;
for I was hungry, and you gave me no food; I was thirsty, and you gave me no drink;
I was a stranger, and you took me not in; verses 41-43, who answered,
when did we see you hungry, or thirsty, or sick, or naked, or a stranger, or in prison,
and did not minister unto you?
But Christ said, inasmuch as you have not done it to the least of these,
you did it not to me; and these shall go into everlasting punishment,
but the righteous into life eternal, ver. 44-45.

Now if they were to go into everlasting fire, who had not clothed, or fed,
or visited in prison, the least of the brethren of Christ,
what shall become of such as Leonard Letchford of Hurst, and George Vinters of Covcold,
ministers in Sussex, who instead of taking in their brethren when they were strangers,
and feeding and clothing of them, have stirred up the rulers and magistrates,
through their false reports, to send such to prison, as they have done against me?
For the aforesaid George Vinters did raise a report,
that Ambrose Rigge did run away from his wife and children out of Lincolnshire,
and left them to the parish, which was false, as was afterwards proved by many witnesses;
yet by this he incensed the rulers against me, being here a stranger.
In this false aspersion Leonard Letchford of Hurst Pierpoint, did join with him,
and stirred up Nisel Rivers, Walter Burrell, and Richard Bridges,
to send for me by warrant, the 28th of the third month, called May, in the year 1662,
out of my peaceable habitation at Hurst, who forthwith committed me to prison,
with more of my friends, for the exercise of our consciences towards God,
where they kept us prisoners till the assizes.

And then Leonard Letchford appeared against us, and incensed the judge;
insomuch that he fined all my friends, for being met together in the worship of God;
and then said to the judge, One word more to aggravate the matter against Ambrose Rigge,
for which the judge reproved him, but yet he knowing that I could not swear at all,
and being incensed against me,
did cause the oath of allegiance to be tendered me in the court;
and because I could not swear at all,
in obedience to Christ and the apostles`' words and commands, Matt. 5, James 5,
Judge Brown did forthwith judge me to lose all my lands and tenements, during my life,
and all my goods and chattels forever, and to be out of the king`'s protection,
and to be imprisoned during the king`'s pleasure.
Afterwards he sent for the jailer, and gave him a strict charge to keep me close,
in which condition I have continued for the most part this seventeen months,
and my friends who were fined as above,
some of whom have continued prisoners to this day with me, in much patience,
and in many hardships, which have added affliction to our bonds; but in all,
the secret hand of God has upheld us to this day; glory,
honour and praises be unto him forevermore,
whose hand is not shortened to them who trust in his name,
but makes them as Mount Zion that cannot be moved.

In this long imprisonment,
Leonard Letchford has often threatened me with the gallows in word and writing;
and one time some of my friends coming to visit me,
they asked Leonard Letchford if he would come to visit me?
to which he answered, if I were to be hanged, he would come to see it done.
And now of late he has said, if it comes to cutting of throats,
he would cut Thomas Luxford`'s throat and mine.
By which, all people fearing God, may judge whether this man be not a murderer,
who would perform it himself, when he cannot get others to do it for him.
This is the entertainment that Leonard Letchford gives to strangers,
and the love that he has to his neighbour.
But Paul, who was a minister of Christ, said, "`Be not forgetful to entertain strangers,
for thereby some have entertained angels unawares,`" Heb. 13:2.
But instead of entertaining of strangers,
Leonard Letchford and George Vinters persecute them as vagrants;
by which the impartial reader will clearly see how far they act contrary to the Scriptures,
both of the Old and New Testament;
and they may judge whether they are ministers of Christ, or antichrist.

From us who are present sufferers under the cruelty of men in the county jail in Horsham,
whose names are

Ambrose Rigge, Ambrose Galloway, Richard Webb, James Matthew.

Dated about the Eighth month, 1663.

=== A Brief and Serious Learning to Such as are Concerned in Commerce and Trading, who go Under the Profession of Truth, to Keep Within the Bounds Thereof, in Righteousness, Justice and Honesty Towards all Men.

Many days and months, yes, some years has my life been oppressed, and my spirit grieved,
to see and hear of the uneven walking of many, who have a name to live,
and profess the knowledge of God in words;
and also of some who have tasted of the good word of God,
and have been made partakers of the power of the world to come,
and have received the heavenly gift and grace of God, which teaches all, who walk in it,
to deny all ungodliness and worldly lusts; and to live soberly,
honestly and righteously in this present world.
The faithfulness of these, with great reason,
has been expected to God in things of the highest concern,
and to have walked as lights in the world, and in all faithfulness both to God and man,
to have stood as living monuments of the mercies of the Lord,
letting their light so shine before men, that they might see their good works,
both in spiritual and temporal concerns.
So might they have honoured and glorified God in their generation,
and have convinced or confounded gainsayers,
putting to silence the ignorance of foolish men, whereby the worthy name of the Lord,
by which they have been called, might have been renowned through the earth,
and his precious Truth and glory spread to the ends of it,
that many through beholding their good and exemplary conduct in Christ,
coupled with the holy fear of God,
might have desired to lay hold of the skirt of a Christian indeed,
whose praise is not of men, but of God.

These are the fruits which we have laboured and travailed for,
through many and great tribulations, that many might be turned to righteousness,
and that the knowledge of the power and glory of the Lord might cover the earth,
even as the waters do the sea.
God Almighty bears us record, this was and is our only end and design, which,
blessed be the Lord, many are witnesses of, and established in,
to our abundant joy and comfort.
But there are some among us who have not walked humbly with the Lord, as he has required,
nor kept in that low state, either inwardly or outwardly,
which becomes such who are travelling up to Zion, with their faces toward it.

These have launched from the rock which is firm and sure,
into the great sea of troubles and uncertainty, where some have been drowned,
others hardly escaping, and many yet labouring for the shore,
with little hopes of coming at it;
who have not only brought themselves in danger of suffering shipwreck,
but have drawn in others, and have endangered them also,
which has opened the mouths of the enemies of Zion`'s welfare,
to blaspheme his great and glorious name,
and has eclipsed the lustre of the glorious Sun of Righteousness,
both in city and in country.
This is a crying evil, and ought not to go unreproved,
and that with a severe countenance; for God is angry with it,
and will assuredly punish it.

Many have got credit upon the account of Truth, because at the beginning it did,
and does still, lead all who were and are faithful to it, to faithfulness and truth,
even in the unrighteous mammon, and to let their yes be yes, and their no be no,
even between man and man in outward things.
So that many would have credited one that was called a Quaker with much,
and many I believe did, merely upon that account; some whereof I doubt not,
have just cause to repent of it already.
But if truth and righteousness had been lived in by all who profess it,
there had been no such occasion given.
For they who still retain their integrity to the truth and life of righteousness manifested,
can live with a cup of water, and a morsel of bread in a cottage,
before they can hazard other men`'s estates to advance their own.
Such are not forward to borrow, or to complain when in need,
for their eye and trust is to the Lord their preserver and upholder;
and he has continued the little meal in the barrel,
and the oil in the cruse has not failed to such, till God has sent further help;
this is certainly known to a remnant at this day, who have coveted no man`'s silver,
gold or apparel, as God knows, but have and do labour with their hands night and day,
that the gospel may be without charge.

It is so far below the nobility of Christianity,
that it is short of common civility and honest society among men,
to twist into men`'s estates, and borrow upon the Truth`'s credit,
gained by the just and upright dealing of the faithful,
more than they certainly know their own estates are likely to answer;
and with what they borrow reach after great things in the world,
appearing to men to be what in the sight of God and truth they are not,
seeking to compass great gain to themselves,
whereby to make themselves or their children rich or great in the world.
This I testify for the Lord God is deceit and hypocrisy,
and will be blasted with the breath of his mouth, and we have seen it blasted already.

And that estate that is got either with the rending
or with the hazard of rending another man`'s,
is neither honestly got, nor can be blessed in the possession.
For he that borrows money of another,
if the money lent be either the lender`'s proper estate, or part of it,
or orphan`'s money that he is entrusted with, or widow`'s, or some such,
who would not let it go but upon certain good security,
and to have the valuable consideration of its improvement; and, the borrower,
though he has little or no real or no personal estate of his own,
but has got some credit, either as he is a professor of the Truth or otherwise, and has,
it may be, a little house, and a small trade,
it may be enough to a low and contented mind.
But then the enemy gets in, and works in his mind,
and he begins to think of a higher trade, and a finer house,
and to live more at ease and pleasure in the world,
and then contrives how he may borrow of this and the other,
and when accomplished according to his desire, then he begins to undertake great things,
and get into a fine house, and gather rich furniture and goods together,
launching presently into the strong torrent of a great trade,
and then make a great show beyond what really he is, which is dishonesty.
If he accomplish his intended purpose, to raise himself in the world,
it is with the hazard, at least, of other men`'s ruin, which is unjust:
but if he falls short of his expectation, as commonly such do,
then he does not only ruin others, but himself also,
and brings a great reproach upon the blessed Truth he professes, which is worse than all;
and this has already been manifested in a great measure, and by sad experience witnessed.

But the honest upright heart and mind knows how to be abased, as well as how to abound,
having learned to be content in all states and conditions.
A small cottage and a little trade is sufficient to that mind,
and it never lacks what is sufficient.
For he that clothes the lilies and feeds the ravens, cares for all who trust in him,
as is at this day witnessed--praises to God on high; and that man has no glory in,
nor mind out after, superfluous or needless rich hangings, costly furniture, fine tables,
great treats, curious beds, vessels of silver or vessels of gold,
the very possession of which, as says the ancient Christian Clemens Alexandrinus,
creates envy.
Padag.
lib. 2 cap.
3, pages 160, 161.

The way to be rich and happy in this world, is first to learn righteousness;
for such a one was never forsaken in any age, nor his seed begging bread.
And charge all parents that they keep their children low and plain in food, drink,
apparel, and everything else, and in due subjection to all just and reasonable commands,
and let them not appear above the real estates of their parents,
nor get up in pride and high things, though their parents have plentiful estates;
for that is of dangerous consequence to their future happiness.
Let all who profess the Truth, both young and old, rich and poor,
see that they walk according to the rule and discipline of the gospel,
in all godly conduct and honesty,
that none may suffer wrong by them in any matter or thing whatever;
that as the apostle exhorted, they may owe nothing to any man, but to love one another;
for love out of a pure heart is the fulfilling of the law;
which law commands to do justly to all men. He that has but little, let him live according to that little,
and appear to be what in truth he is; for above all God abhors the hypocrite;
and he that makes haste to be rich falls into snares, temptations,
and many noisome and hurtful lusts, which drown many in perdition, 1 Tim. 6:9.
"`And the love of money is the root of all evil,
which while some have lusted after, they have erred from the faith, and pierced themselves through with many sorrows;`" verse 10.

For preventing this growing evil for the time to come,
let faithful Friends exhort such who either live without due care,
spending above what they are able to pay for, or run into great trades,
beyond what they can in honesty and truth manage;
and let them be tenderly admonished of such undertakings.
This will not offend the lowly upright mind; neither will the honest minded,
who through a temptation may be drawn into such a snare and danger,
take any occasion to stumble, because his deeds are brought to light.
If, after mature deliberation, any are manifested to be run into any danger of falling,
or pulling others down with them, let them be faithfully dealt with in time,
before hope of recovery be lost, by honest faithful Friends,
who are clear of such things themselves;
and be admonished to pay what they have borrowed faithfully, and in due time,
and be content with their own,
and to labour with their own hands in the thing that is honest,
that they may have therewith to give to him that needs,
knowing that it is more blessed to give than to receive, Acts 20:35.

And if they hear, and are thereby recovered, you will not count your labour lost;
but if they be high, and refuse admonition, it is a manifest sign all is not well.
Let such be admonished again by more Friends, and warned of the danger before them;
and if they still refuse and reject counsel and admonition,
then lay it before the meeting concerned about Truth`'s affairs, to which they do belong;
and if they refuse to hear them,
then let a testimony go forth against such their proceedings and undertakings,
as not being agreeable to the Truth, nor the testimony of a good conscience,
neither in the sight of God nor man.
This will be a terror to evil-doers of this kind, and a praise, encouragement,
and refreshment to them that do well,
and nothing will be lost that is worth saving by this care: for he that does truth,
whether in spiritual or temporal matters, will willingly bring his deeds to the light,
that it may be manifest to all that they are wrought in God.

These things lay weightily upon me, and I may truly say in the sight of God,
I wrote it in a great cross to my own will, for I delight not, no,
my soul is bowed down at the occasion of writing such things; but there is no remedy;
the name of the Lord has been, and is likely to be, greatly dishonoured,
if things of this nature be not stopped, or prevented for time to come.
Therefore I beseech you all, who have the weight and sense of these things upon you,
let some speedy and effectual course be taken to prevent what possibly we may,
both in this and all other things,
that may any way cloud the glory of that Sun which is risen among us.
And make this public,
and send it abroad to be read in true fear and reverence in all meetings;
and let all concerned be faithfully and plainly warned, without respect of persons,
by faithful Friends, who have the care of God`'s glory,
and his churches peace and prosperity upon them:
so will the majesty and glory of God shine upon your heads,
and you shall be a good savour of life, both in them that are saved,
and in them that are lost.

Written by one who longs to see righteousness exalted, and all deceit confounded.

Ambrose Rigge.

Gatton-place, in Surrey, the 16th of the Eleventh month, 1678.

=== To All the Faithful Flock of God in Suffering, Whether in Prison or at Liberty, in Scorn Called Quakers

The salutation of my endeared love in our Lord Jesus Christ,
the Captain of our salvation, who was made perfect through suffering,
reaches and freely flows forth unto you all,
whom God has counted worthy not only to believe in his Son Christ Jesus,
but also to suffer for his name and testimony,
and has made you living monuments of his tender mercy.
My heart`'s desire and daily prayers to God for you are, that grace and peace,
with faith and love, may be daily multiplied in and among you;
which is the reward of the faithful followers of the Lamb through many tribulations.
This was the path of the just in all ages; he that was born after the flesh,
persecuted him that was born after the spirit; even so it is now.

Therefore, dear friends, be not dismayed at the roaring of the sea,
or at the swelling of the waves, for they are all limited and cannot pass their bounds,
neither can they do more or less, but by the permission of that Divine Hand,
by whom all things were made, and are upheld.
Stand in the faith which works by love, and this will outlast all the wrath of man,
which does not, nor ever did, work God`'s righteousness,
and give you power to bear more than the wicked shall have power to lay upon you;
for in your patience you will possess life and peace, which no man can take from you.
This I have learned through many trials for many years, in long imprisonments,
spoiling of goods and cruel whippings and sore buffetings,
and many inward and outward exercises, yet through all has the Lord delivered.
Yes, and he will deliver them that trust in his name, and make them as Mount Zion,
that cannot be moved;
and not a hair of their heads shall fall to the ground without his consent,
who will now try the faith,
patience and constancy of his people through many tribulations,
that his jewels may appear in their lustre, which he will make up,
and gather his wheat into his garner, and burn up the chaff;
for the reaping and the harvest has been, and the threshing-floors witnessed,
in which many have threshed in hope, but till the winnowing day is known,
the wheat and chaff are not fully separated.
And you also know that the kingdom of heaven has been as a net cast into the sea,
which has taken the bad as well as the good; which when it is full,
the good are gathered into vessels, and the bad are cast away:
even so will it be in this day of the Son of man.

Oh! therefore put on your beautiful garments, you jewels of the Lord`'s house,
and let the girdle of Truth compass your loins; and wash your hands in innocency,
so shall you compass the altar which is within the spiritual temple of the Most High,
which he has built of living stones, elect and precious,
in which there is no need of the outward Jews`' candlesticks or lights,
or the titular Christians`' many candles,
but the Lord God and the Lamb is the light thereof.

I am even constrained to write this unto you in the love of the Father of lights,
that your joy may be full;
for all the suffering of this present world is not worthy
to be valued with the glory that is already revealed,
and to be revealed in them who believe and are found faithful unto death.
There is no summer or harvest without a winter, nor any perfection without suffering;
and the way to enjoy all with the blessing, is to give up all when required of the Lord.
This made the wise man say, "`Cast your bread upon the waters,
for after many days you shall find it.`"
This has been witnessed in our day;
therefore let us trust perfectly in the name of the Lord,
who feeds the ravens and clothes the lilies, as in ancient days, for he gives and takes,
and gives again to the faithful.
This Job witnessed in his day,
whose fidelity to God was manifested through the loss of all his outward substance,
and the affliction of his body; who through faith obtained a good report,
and possessed the promise of the life that then was, and that which was to come.
So did Abraham and all the faithful, in offering up, when required, receive.
This was the way of the flock of God in all ages, in which many are now called to walk,
whom the Lord will try as gold is tried in the fire,
that they may dwell with everlasting burning, and be crowned with dominion over death,
hell, and the grave forever.

Dear friends, look not out at the prosperity of the wicked, for their root is rottenness,
and their blossoms shall fly up as the dust;
"`and the day that comes shall burn as an oven, wherein all the proud,
and all that do wickedly shall be as stubble,
and the day that hastens shall leave them neither root nor branch.`"
The way to have pure dominion over your enemies,
and to heap coals of fire upon their heads, is to do good,
and to pray for them who spitefully use, and hate and persecute you.
This is the very nature of the Truth, which our God in tender mercy, in our day,
has manifested.
Render to no man evil for evil; nor join with, or countenance any who would;
for such know not what spirit they are of.
Christ the Truth is not come to destroy men`'s lives, but to save them, and to give life.
So commit your innocent cause to him, to whom vengeance belongs,
and he will plead your cause with your stoutest adversaries.
No weapon hitherto formed against us has ever prospered, neither shall,
as we keep in that righteousness which God through
Christ Jesus has clearly manifested in us,
being the righteousness of faith, which says, as in ancient days, Go not forth.
This is the riches of the gentiles, which will enrich the whole earth;
and all who receive and walk in it, shall be by it established in lasting peace with God,
though for it we may be reviled, and counted as sheep for the slaughter for a time;
for He who is gone before endured the contradiction of sinners,
and gave his back to the smiter, and his cheeks to the buffeter;
and the servant is not greater than his Lord.

So the God of all mercy possess our souls more and more with quietness and confidence,
that our strength may be made perfect in him, who has all power in heaven and earth,
that we may continue in faith, patience and well-doing unto the end.

I am your brother and fellow-sufferer,

Ambrose Rigge.

Gatton, this 28th of the Twelfth month, 1682-3.

=== The Spiritual Guide of Life, Offered and Tendered to All Mankind, Without Respect of Persons, Age or Sex, to Direct their Feet into the Way of Peace.Or the Inward and Spiritual Grace of God Exalted as Man`'s Only Teacher.

It is the universal concern of all mankind upon the face of the whole earth,
to seek those things which belong to their eternal peace, happiness,
tranquillity and rest with God, when time in this world shall be no more.
Yet such are the wiles and cunning devices of the serpent and adversary of man`'s felicity,
+++[+++who prevailed with Adam and Eve in the beginning
to break God`'s covenant of life made with them]
that he prevails with the generality of their posterity at this day, to slight,
disesteem and undervalue that which should bring their salvation,
and them to the knowledge of the way thereunto,
which is God`'s inward and spiritual grace,
which came to be manifested and known by the second Adam, Christ Jesus, John 1:17.

This is the root, substance, and life of all true religion in the world,
and without it there is none in the earth; for God has given it,
to bring salvation to the ends thereof,
and to be a perfect and sufficient teacher to all mankind, 2 Cor. 12:9.
This was the saints`' teacher in
the gospel administration which brought their salvation, Tit. 2:11.
And till the nations and people in general
come to hear and learn of this inward and spiritual teacher,
they can never be taught to deny ungodliness and worldly lusts,
nor to live soberly and righteously in this present world.
This is the Christ of God, spiritually manifested in mortal flesh,
to destroy the works of the devil, which who does not hear, receive, follow and obey,
can never receive power to become servants or sons of God;
but remain all their days in the gall of bitterness and bond of iniquity,
heaping up wrath against the day of wrath,
and the revelation of the righteous judgments of God,
and their religion and faith are vain and unprofitable.

Thus Christ being manifested, becomes the author of eternal salvation in all who believe,
and is that great mystery which has been hid from our forefathers for many generations.
Where he is received, heard and obeyed, he manifests his strength and power in the soul,
greater than the power and strength of the enemy, and binds the strong man,
who has long kept the hearts of many, and casts him out,
and sets up there his own throne,
and rules till he has put all his enemies under his feet;
and so becomes the hope of glory to the people, Col. 1:27.
And whosoever does not thus receive, hear and obey him,
nor give up thus to be governed by him, cannot be his disciples,
nor receive power from him, to become sons or servants of the living God.
Though they may profess his name in words,
and make a fair show of Christianity in the flesh,
yet the true Christian life they are strangers unto, and without God in the world,
dead in sins and trespasses, and can never be raised out of the grave of corruption,
but as they believe in, and wait for the manifestation of his power,
+++[+++which is only known and manifested by his inward light and grace]
to work all their works in them and for them.

Thus must man be made the workmanship of God,
created again in Christ Jesus unto good works, Eph. 2:10. This is the new creation,
where man receives the image of God, i. e., righteousness,
which was lost in the first Adam.
"`For as the body without the spirit is dead,
so faith without works is dead also,`" James 2:17-20. For by works of righteousness,
brought forth in man by Christ, God`'s righteousness, is saving faith known.
And no man can have true faith in Christ,
who manifests not the works of righteousness in his conduct.
For the fruit and effect of saving faith in man, is an inward righteousness and holiness,
whereby man`'s heart, soul and spirit are sanctified to God,
without which no man can see God.
And man must follow him in the works of his righteousness, and learn of him,
and bear his cross; not one of gold, silver, wood or stone,
but that which crucifies their beloved lusts and pleasures,
without which they can never wear his crown.
For though man by his own power cannot work his own salvation,
yet as he believes in and follows Him whom God has given for a Leader, Isa. 55:4,
and a Commander to his people,
he shall receive power from him to do whatsoever he commands him,
and be saved by him from his sin and transgression; for his name is called Jesus,
because he saves his people from their sins, Matt. 1:21.
And whosoever is not saved by him here from their sins,
can never be saved hereafter by him from the wrath and displeasure of Almighty God,
and that death which is the wages of sin, Rom. 6:28.

Now, the means which God has appointed to bring his salvation to all mankind,
is his inward and spiritual grace and truth which came by Christ Jesus, John 1:17.
This inward teacher as all mankind come to hear and obey,
they through him will be saved, Eph. 2:8.
He has virtue and power to bring forth righteousness in man,
and to work out all unrighteousness.
It is like a little leaven hid in the meal which Christ spoke of, Matt. 13:33,
and will leaven the whole lump of mankind into sincerity and truth,
if it be received and obeyed.
This is the precious pearl, hid in the field which is the world, set in man`'s heart,
Ecc. 3:11, which the wise man digs deep there to find, Matt. 13:45-46,
and having found it, sells and parts with all his lusts to purchase it.
No man can buy it but with the loss and denial of all things contrary to it;
gold will not purchase it, and silver is dross in comparison of it,
the price thereof is above rubies; and therefore the wise man said, "`Buy the truth,
and sell it not,`" Prov. 23:23, Rev. 3:18. No man can truly say,
"`My beloved is mine, and I am his,`" but as he thus buys it,
with the selling of all contrary to it.
This is a hard saying to many, or the most part of mankind, especially the rich,
who have great possessions; and many beloved lusts and pleasures to part with,
which are as dear and near as their right hand or eye. This made the young man, whom Christ spoke unto, Matt. 19:21-22,
to go away from him sorrowful, who had great possessions; upon which the Son of Man said,
"`That a rich man should hardly enter into the kingdom of God,`" verse
23.
And "`it is easier for a camel to go through the eye of a needle, than for a rich man to enter into the kingdom of heaven,`" verse 24.

Here is the mystery of godliness revealed, which the natural man cannot see, or perceive,
for it is hid from the wise and prudent of the world,
and discovered and revealed unto babes and little ones.
The great and proud men of the world are too big to enter the strait gate,
and walk in the narrow way;
the preaching of the cross of our Lord Jesus to them is foolishness,
and they cannot see the strait gate, and the cross which the apostles preached,
and all the true disciples and followers of Jesus Christ took up,
who were crucified to the world, and the world to them, Gal. 6:14.

Therefore lay aside all your imaginary crosses of gold, silver, wood or stone,
they are of no value,
neither is there any virtue in them to crucify one lust that wars in your members;
indeed, though you may carry them in your bosoms,
yet your beloved lusts lie there also unmortified, which every day war against the soul,
and so far prevail, that they bring forth sin in word and deed, which being finished,
brings forth death, James 1:15.

The true cross of Christ is the power of God in all who believe, 1 Cor. 1:18. "`And,
having made peace through the blood of his cross,
by him to reconcile all things unto himself; by him, I say,
whether they be things in earth,
or things in heaven,`" Col. 1:20. That by which
the ancient Christians were crucified to the world,
and the world to them, was the cross of Christ spiritually borne, Gal. 6:14.
But since the Christian life and spirit have been laid aside and quenched,
the knowledge of this cross has been lost, and people have set up an image of it,
and have become strangers and enemies to the cross of Christ,
as the Jews and pharisees were in the gospel day, being without God in the world.

The knowledge of the mystery of God`'s salvation to all mankind upon the earth,
must be opened and manifested by the gift of God, that is, by his grace and spirit,
as it is received and obeyed, "`For as no man knows the things of a man,
save the spirit of a man within him: even so the things of God knows no man,
but the spirit of God,`" 1 Cor. 2:11. With this
spirit within did the prophet Isaiah seek the Lord, Isaiah 26:9.
And with the Spirit of Truth within must all mankind seek the Lord,
if ever they find him and know his work;
for without it the knowledge of God`'s salvation is, and forever will be,
hid from the wise and prudent of the world.
This was the Jews`' blindness, the resisting of the spiritual gift of God, Acts 7:51,
who by their wicked hands stoned Stephen to death,
though they held up the temple worship, the offerings and sacrifices,
yet by resisting the spirit of God in themselves,
they became more blind than he who had an unclean spirit, who said to Christ,
"`I know who you are, the Holy One of God,`" Mark 1:23-24. Matt. 8:29. Yes,
the devil confessed him to be the Son of God, Mark 5:7.

The grand cause of all the error in the world,
is in going from the Spirit of Truth within, the Comforter now sent,
according to the promise of Christ, John 14:16,17,26. This Comforter being received,
heard and obeyed, leads into all truth,
and is a perfect guide appointed of God for all mankind,
to bring to the knowledge of God`'s salvation; and thus to know the only true God,
and Jesus Christ whom he has sent, is eternal life; and all knowledge short hereof,
is earthly and carnal.

Christ within, the hope of glory, has been as a mystery hid from ages and generations,
but revealed in the gospel day, Col. 1:26-27. And thus manifested to the gentiles,
Acts 13:47, that he might be God`'s salvation to the ends of the earth;
when the wise professing Jews rejected him in his outward appearance in the flesh,
to whom he was first tendered.
This inward and spiritual appearance of the Christ of God in our day,
the chief priests and literal and worldly wise professing Christians do oppose and gainsay,
and will not have him thus to rule in the hearts and consciences of his people;
but call the true light, which is his life and spiritual appearance, John 1:4,
a dark lantern, and a natural conscience;
and so make the word and commandment of none effect by their traditional religion,
which is set up in the will and wit of man,
and do every day crucify to themselves afresh the Lord of glory,
and put him to open shame; for every wicked word and deed is as a spear to wound him.

And no man can be a true Christian, who is not baptized into the death of Christ,
Rom. 6:3, that is, dead to sin; this is the true spiritual baptism,
of which John`'s baptism with water was but a figure, type, and forerunner.
Neither is he now a gospel Christian, who is one outward; neither is that baptism,
that is outward in the flesh; but he is a true Christian, who is one inward,
and the one baptism is that of the heart and of the spirit.
For neither baptism, nor unbaptism, as outward, avails anything, but a new creature,
created again in Christ Jesus unto good works to live in them, Eph. 2:10.
This is Christianity in its ancient glory and purity,
which is restored and witnessed by receiving, hearing,
and obeying the inward and spiritual "`grace of God which brings salvation,`" Tit. 2:11.
Of which water baptism is an outward and visible sign,
as it is declared in the book of common prayer now used in England, where they say,
"`That the inward and spiritual grace is a death unto sin,
and a new birth unto righteousness,`" etc.
And till the outward Christians come to hear and obey this inward and spiritual grace,
they cannot know or witness God`'s salvation;
for all without it is but as a shell and shadow, and as chaff to the wheat.
 And as Christ`'s appearance and manifestation in the substance of the gospel ministration,
is inward and spiritual, so is his baptism, and so is his supper, and all his ordinances,
and all who truly "`eat his flesh, and drink his blood, dwell in him,
and he in them,`" John 6:56.
For it is the spirit
that quickens all who are made alive by him, the flesh profits nothing, verse 63.
The words he spoke were spirit and life,
though mysteriously spoken; at which the Jews murmured,
and many of the disciples were offended, verses 52, 60, 61, and looked outward,
as too many do in our day, who neither discern his flesh nor blood,
and so eat and drink their own damnation. Though the children of Israel ate manna in the wilderness
that was rained down from heaven every day,
yet as it was outward, they died, John 6:49.
Therefore it is not the outward bread,
in the gospel dispensation, that nourishes the soul to eternal life,
but the spiritual manna, which is received by the indwelling of the Son of God in man,
and man dwelling in him, verses 56, 57. They who thus eat his flesh and drink his blood,
have eternal life, and he will raise them up at the last day, verse 54.
This is the anti-type, or mystery of all outward types and representations,
even the cup of the New Testament in his blood, in all who spiritually receive it;
for the outward flesh, bread and cup profit nothing as to the soul`'s nourishment;
it is the spiritual, that gives life,
the bread and cup thereof nourishes up to eternal life.

Where Christ is come and risen in the spirit,
his spiritual bread and cup shows his resurrection in the soul.
Here those who are quickened and raised by him,
live by every word that proceeds out of his mouth, Matt. 4:4.
And being thus made partakers of his resurrection,
over them the second death has no power.
This was represented by Moses lifting up the serpent in the Wilderness, John 3:14,
Num. 21:9; so must the Son of Man be lifted up in the soul,
that all who are bitten by the spiritual serpent, may look to him, and be healed.
For though he was made a sacrifice to God for the sins of the whole world,
that through his life and resurrection the whole world might be saved,
yet has no man part in him, or his resurrection,
who is not in this world washed from his uncleanness by him. For the purging, which all true Christian believers own, is by the blood of Jesus Christ,
to cleanse them from their sins, which none can have the benefit of,
but those who walk in the light, 1 John 7:17.
"`For if we say we have fellowship with God, and walk in darkness, we lie, and do not the truth,`" verse 6.
"`But if we walk in the light, as he is in the light,
we have fellowship one with another, and the blood of Jesus Christ, his Son,
cleanses us from all sin.`"

Here is the covenant in which the benefit, virtue,
and efficacy of the blood of Jesus is known and witnessed to this day,
and must be throughout all generations.
Therefore has the true light, or grace of God,
lighted every man that comes into the world, John 1:9, that all might receive it,
and walk in it and so be made living witnesses of the blood
of Jesus Christ to cleanse them from their sins.
If the sons and daughters of men had come to know this,
they need not to have imagined an outward purgatory to cleanse people from their sins;
the blood of Jesus thus known and witnessed is sufficient
to sanctify and make clean in body,
soul and spirit, all who walk in the light;
and thus would God`'s salvation be known and manifested to the ends of the earth.
For as the lightning comes out of the east, and shines to the west,
so is the shining of the Sun of righteousness in the soul of man.
But till the day dawn and the day-star arise in the heart,
the glorious Sun of righteousness with healing in his wings can never be known to arise;
and until this is known and witnessed, all preaching is vain,
and people`'s faith is vain, and they are still in their sins,
and can never be made partakers of his resurrection, nor conformable to his death,
but live and die in their sins, and where he goes they cannot come, John 8:21,24.

Therefore let all be warned,
to take heed to the true light and inward spiritual grace of God,
and give up to the teachings thereof, that they may receive an understanding from God,
to know the mysteries of the kingdom of righteousness,
which are hid from the wise and prudent of the world, who are glorying in brain-study,
human arts and literature, and natural acquirements in the will and wisdom of man.
Through these was divine wisdom never conveyed to any of the sons of men.
True wisdom is the gift of God, communicated to them who love and fear him;
the secrets of the Lord are daily manifested to such,
and they lack not the knowledge of the mysteries of the kingdom of righteousness,
but can declare to others what God has done for their souls,
of what they have tasted and handled of the word of eternal life;
these are able ministers of the New Testament, not of the letter, but of the spirit.

And till the nations and people in general be turned unto, and receive the gift of God,
which he has universally given to all mankind to profit withal,
they can never see the opening of eternal life;
neither can the way thereof be manifested or known by anything short of it;
neither can any man know life by it till he is subjected to it,
and spiritually baptized by it into the death of Christ;
this is the true inward Christian, whose praise is not of men, but of God.
For the true Christian baptism is a death unto sin, and a new birth unto righteousness,
and none are Christians indeed but who are so baptized.
Upon this account said the Son of God unto Nicodemus, "`Except a man be born again,
he cannot see the kingdom of God,`" John 3:3. And again,
"`Except a man be born of water, and of the spirit,
he cannot enter into the kingdom of God,`" verse 5, the spiritual water,
with which the Holy Spirit does wash all true believers,
and bring them into newness of life.
For he is not a Christian that is one outward; neither is that baptism,
that is outward in the flesh; but he is a Christian who is one inward,
and baptism is that of the heart, and in the spirit.
This is the true gospel ministration,
the last and greatest that ever the world shall be visited with.
This has a more excellent glory, than that which stood in meats and drinks,
and carnal ordinances and commandments of men,
and therefore is to remain to all generations, 2 Cor. 3:6-11.

Now all you who are set down in outward visible signs,
and are slighting and neglecting the substance, namely,
the inward and spiritual grace which must bring your salvation,
the enemy has deceived you in keeping you from receiving, hearing, and obeying it,
your sufficient teacher and bringer of salvation. Thus you are ever learning,
and can never come to the knowledge of the Spirit of Truth in yourselves,
which is given of God to lead you into all truth, John 16:13,
the Comforter promised by Christ, John 14:16-17, to abide forever; who he said dwelt with his disciples, and should be in them, verse 17.
This Comforter,
the Spirit of Truth is arisen in our day,
and is manifested in all true believers for this purpose,
to destroy the works of the devil.

But oh! let the outward Christians beware, lest they reject him in his inward appearance,
as the outward Jews rejected him in his outward appearance;
for if they wound and crucify the Spirit of Truth, and of Christ in themselves,
they will be as guilty of his blood, as were the Jews of old.
What slighting, despising, no,
blaspheming against this inward and spiritual appearance of Christ
have the nominal Christians been guilty of these forty years?
How have they buffeted, stoned and imprisoned him in his servants,
for speaking through them?
Indeed, they have crucified him afresh, and put him to open shame by their ungodly deeds,
and hard speeches.

Oh Lord!
I pray you open their eyes,
that they may see him whom they have thus pierced with their sharp spears,
and let a day of mourning and lamentation come over them,
as was prophesied of the house of David, and the inhabitants of Jerusalem,
every family apart, and their wives apart, Zech. 12:10-14.
He is indeed a Comforter to such mourners now,
but cries woe to them who now laugh,
as he did in the days of his flesh to the Jews and Pharisees, Luke 6:25.
For outward Christianity now, where the inward life,
spirit and power of Christ are not received and witnessed,
is of no more value in the sight of God, than were the Jews offerings and sacrifices,
when they were inwardly polluted.
For it is the sacrifice of a broken heart and contrite spirit, which the Lord regards,
Ps. 51:17, and the inward white linen is beautiful in his eye,
and his sons and daughters are all glorious within, Ps. 45:13.
They hunger and thirst after an inward righteousness,
i. e. the righteousness of faith, which says, go not forth, Matt. 24:26.
Rom. 10:8, for the word is near you in your heart,
and in your mouth that you may hear it, and do it. 

This was the word of faith which the true gospel-ministers preached,
beloved and received; and who does not receive this inward word,
cannot know the salvation of God,
for it is the engrafted word that is able to save the soul, James 1:21.
And till the people come to hear and to do this word,
their buildings are upon the sand, and will not stand in a stormy day;
for true and saving faith is obtained and received by hearing this word,
in all who live and stand in it, without which no man can please God, Heb. 11:6.
Thus the ancients received faith, and walked in it,
and did many valiant acts, both in the time of the first and second covenant,
and had victory over the world; yes, they were made more than conquerors over death,
hell and the grave, Rom. 8:37, and obtained a good report,
though they received not the promise, Heb. 11:39.

And now this testimony I must leave to the world,
that God has sent his good Spirit into the hearts of the children of men,
to be their guide, leader and director in all things relating to his kingdom;
and upon the receiving and obeying, or resisting and disobeying this Spirit,
stands man`'s eternal felicity or woe,
for nothing short of it can give mankind the knowledge of the mysteries of God`'s salvation;
and all knowledge without it, is earthly and carnal, and can never give life to the soul.

And therefore all you outside Christians, professors and profane,
who have taken up your rest in an outward profession of God and godliness,
but live in the profane fashions, customs and superfluities of the world,
far beyond those you term heathens, my soul is often bowed down for you,
because you are resisting the appearance of God`'s Spirit, as did the Jews of old.
Through your traditional religion,
which you have received by and from your darkened and benighted ancestors,
you have made the word and commandment of God of none effect,
and have wrought despite against the Spirit of Grace,
and have set down at ease in an outside invented form of godliness,
imitating some things which the holy men of God did in the days of old,
through the leading and dictates of God`'s Spirit.
But this to you is but an image or likeness of a thing in heaven;
and it may be said to you, as it was to Judah in the days of Isaiah the prophet,
Who has required these things at your hands? Isa. 1:12.
Your set days and fasts, your morning and evening sacrifices,
the Lord has no regard unto, but says at this day, as in days past, Isa. 1:16-17.
Jer. 4:14, Wash your hearts from wickedness; the fountain is open,
put away the pride and abominations of the heathen out of your houses and hearts,
and boast not yourselves that you are not as other men; peradventure no common drunkards,
swearers, nor extortioners, nor thieves, nor murderers,
but that you pay the tithe of all you possess, give alms, and often have family duties,
and frequent the church and its ordinances, as you call them.
All this, and much more, if you had it, will not give you acceptance with God,
while your inside is full of rottenness and corruption;
this righteousness exceeds not that of the Scribes and Pharisees,
but is many degrees short thereof.

Arise, arise, this is not your rest, because it is polluted, Micah 2:10.
Shake off your night garments, be afflicted and mourn and weep,
let your laughter be turned into mourning, and your joy into heaviness;
for the Lord is arisen to plead with all flesh, by his sword, and by fire,
and he will leave the outward court to be trodden down of the Gentiles.
He is arisen in his fury as a man of war,
and is disquieting the nations with wars and commotions,
and causing the potsherds of the earth to dash one another to pieces,
that he may make way and room for his own kingdom, rule and government in the earth;
and all who will not that he should rule, he will slay by the breath of his mouth,
and the brightness of his coming.
For Babylon must fall among Papists and Protestants, even that which has been builded up,
whereby to reach to heaven, in the will and wisdom of man:
for it is come in remembrance before the Lord, and great will be the fall thereof;
her merchants shall lament to see her destruction,
when they shall not be able to relieve her.
And the scattered flock of the house of Jacob, God will gather into his own fold, namely,
his power, within whose walls is the well of life,
where all the sheep of his pasture drink,
and here shall none be able to make them afraid,
for the power of God is that universal fold,
into which the gathering of the nations must be.
All who gather not into this power are false shepherds,
and gather to themselves for unrighteous gain;
but the gathering of the people shall be to the Lord, Gen. 49:10,
Israel`'s true Shepherd and leader;
so shall the kingdoms of the world become the kingdoms of God and his Son.

This testimony lay upon me to leave behind to the world,
not knowing how long my days may be therein.

Ambrose Rigge.

Rigate, this 30th of the Third month, 1691.

