== Chapter VII

[.blurb]
=== A General Epistle to All Friends and Brethren, Everywhere; to be Read Among Them in the Fear of God, etc.

My dearly beloved friends, brethren and sisters,
who are made partakers of that precious faith and word of it,
which was once delivered to the saints, and true gospel-believers and witnesses;
by and in which they were sanctified, justified and glorified.

My heart and soul do earnestly breathe to the Lord, that grace, mercy, truth and love,
may be daily increased, and abundantly multiplied, in and among you all;
and that you may be preserved a peculiar people, and royal priesthood,
daily increasing in fruits of righteousness,
as trees of the Lord`'s own right hand planting.
So shall his worthy name, by which you have been called, be glorified by you,
and his high praises be in your mouths, and a two-edged sword in your hands,
to wound the dragon and power of darkness, in all his appearances and transformings,
which are and have been many and various in our day;
so that some stars of heaven have been drawn down to the earth by his power,
and have made great noises at their fall.
But the foundation of God stands sure, and all who have continued upon it,
have been preserved unmoveable, not only through all storms which have arisen in the sea,
but have escaped the baits and snares which have been laid covertly in the earth:
glory and renown ascend to that worthy name,
which has been our tower and safe habitation to this day; Amen, Amen forever.

And now, my dear friends, my life salutes you all, in the love of my heavenly Father,
which daily abounds and flows towards you, from the least to the greatest,
who retain your first love and integrity towards the Lord,
as witnesses for his name upon earth, in testimony and conduct.
You has the Lord chosen to be the first fruits to
the glory of his eternal and honourable name;
keep your vessels sound and clean, that He,
who is the fountain of all fullness and goodness, may daily fill your cups,
to hand forth to the thirsty, as he has filled ours, who went before you.

Oh! my dear brethren and sisters, abide in Him, your heavenly vine;
so shall every spring of life and virtue, that opens in and through you,
water those plants,
which the Lord by the right hand of his power has planted into his likeness,
that they might grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ,
and may be built up together in him a holy habitation, and spiritual household,
to dwell together in unity, as children of one Father:
so shall peace possess your habitations, and prosperity attend your undertakings.
This I have learned in my day, through many tribulations,
which have attended my pilgrimage in this world: in all of which, I have been preserved,
by the mighty hand of God, through faith, to this day.

This I write for your encouragement, who are coming up in the same life and gift of God,
which he has ordained to open life, and the fountain of it,
to all nations and kindreds of the earth;
that his church may be restored to her ancient glory and beauty,
which have been eclipsed and marred,
in this long night of darkness and apostasy that has overspread the nations,
for many generations.
But now she is returning out of the wilderness, clothed with the sun;
and her lovers are gathering to her from many corners of the earth;
and her glory has eclipsed the wandering stars,
and will enrich the world with righteousness; so that peace on earth,
and good will to men,
shall be perfectly restored in all them who are made living members of her.
For so has Christ, her great prince, husband and lawgiver ordained,
that all her members should be holy and without blame before him,
as becomes his household and family.
So walk in him, and follow that path of life, and holy conduct,
which your feet have been turned into, by your ancients and elders;
many of whom are already gone to their rest, where the wicked cease to trouble,
and where the weary are at rest, and the voice of the oppressor is heard no more;
and the rest are following after, clothed with spiritual armour, the helmet of salvation,
and shield of faith;
by which we have all along been able to quench the fiery darts of the devil,
which have been many and great.

And you that are coming after, keep within your armour of light;
so shall the same power sustain you, and carry you, as on eagles`' wings,
through all difficulties which the Lord will yet allow to be set before you,
and will be your rock in the time of storm, and your shadow in the time of heat;
for he is become the rock of our age, as he was to ages and generations before us;
to all who have heard and obeyed his word, against whom no weapon hitherto has prospered.
For God will establish Zion, and build up Jerusalem of living stones,
upon the one foundation stone,
and many shall flock to her gates with songs of praise in their mouths:
for the gathering of the people shall be to Shiloh, the peaceable Saviour,
that his kingdom of righteousness may be established again in the earth,
whereby she shall again enjoy her sabbaths.

For the Lord is arisen to awaken the nation,
and is putting trumpets in the mouths of many, to sound an alarm in his holy mountain;
and many are awakened, and rising out of beds of ease and carnal security,
where they have long laid polluted in their blood,
and are now putting off their night garments,
which have been stained and spotted with the flesh.
And He is now fitting many to be clothed with the
garment of praise for the spirit of heaviness,
that they may be called trees of righteousness, the planting of the Lord.
And many are made to run to and fro,
that divine knowledge and spiritual understanding
of the divine mysteries of God`'s eternal kingdom,
may again be restored; which have been long hid from the wise and prudent of this world,
but are now revealing and revealed to babes and sucklings;
out of whose mouths the Lord will perfect his praise and glory in the earth, which,
in due time, he will replenish with the knowledge of his glory, as the waters do the sea.

And now, my dearly beloved in the Lord, great and small, male and female,
my heart and soul daily breathe to the Lord for you all, in the love of Jesus Christ,
that you may walk worthy of that high and honourable calling, whereunto you are called,
in all humility and godly sincerity, as lights in the world;
so will you be daily baptized into the death of Christ,
and be made partakers of his resurrection; which none can have a part in,
but they who are first baptized into his death.
Such are arisen with him to newness of life,
and are earnestly seeking those things which are above; though they walk on earth,
yet their citizenship is in heaven, having an eye to the recompense of reward;
which no mortal eye has seen, nor can see, neither have entered into the heart of man,
the things which God has prepared for them who love him: but he has revealed,
and is revealing them by his Spirit, to all who walk in it;
for the Spirit searches all things, yes, the deep things of God.

But believe not every spirit, but try the spirits, whether they be of God;
for some false spirits are already gone out, and have embraced this present world.
They went out from us, because they were not of us: for if they had been of us,
no doubt they would have continued with us; their end will be answerable to their works.
But be watchful and circumspect, whose eyes the Lord has opened,
that you may discern the enemy in all his cunning devices, both within and without;
and tried armour has been given you to resist him, if you keep it about you;
without which you cannot be safe from the jaws of him, who goes about as a roaring lion,
seeking continually whom he may devour.
Therefore dwell within that munition of rocks, with which you are surrounded,
and go no more forth; but keep your habitations in the light, where God dwells,
that you may enjoy his presence,
which will daily be an open fountain of life to your souls.
There your bread will be sure, and your water will never fail;
and the Lord will spread your tables in the midst of your enemies,
and bear up your heads through all difficulties.

This I have known, and many years experienced in my day;
by which I was abilitated to give my naked back to the rod of the wicked,
and my head to them who tore off my hair, and my body to bonds, and close confinement,
with other additional sufferings, which many years were my lot in the world;
in and through all which, the Lord carried me with cheerfulness and contentedness,
without the least murmuring.
But the longer I suffered, the easier it was made to me by the Lord.
I was freely given up to suffer all my days, as my enemies said I should; who said, Aha,
aha!
Thus we would have it.
But the Lord disappointed them, and set my feet at liberty over all their heads,
when I least looked for it.
Glory, honour, and everlasting praises be to his honourable name forevermore;
who never fails them, whose dependence is upon him for preservation and deliverance.

And now my dear friends and brethren,
seeing this stormy winter is in a great measure over,
and the Lord in mercy has influenced the heart of this present government,
under which we live, to calmness and tenderness towards us:
let us be humbly thankful to him for it, and further engage the government,
by our peaceable behaviour and deportment, in exercising ourselves,
and as much as in us lies, by all honest and lawful means,
to provoke others to the like acts of piety, justice and righteousness,
which will establish and exalt a nation, and be the greatest glory of the government.
Thus shall our thankfulness and service be manifested to them,
beyond all the flatteries of wicked and ungodly men,
among whom the government is not safe; for such were called, many ages ago,
the plague and pests of human society;
and entailed vengeance upon the places of their residence;
and the greatest enemies the government could have in their midst.
For if righteousness exalts a nation, as the wise king said,
then unrighteousness must debase it, and bring contempt and reproach upon it.

So, dear friends, love the government under which God has placed us,
and seek the safety of it, by walking uprightly in it.
And let prayers, supplications and intercessions be made to God for all men,
especially for all who are in authority over us;
that under them we may live quiet and peaceable lives, in all godliness and honesty:
for this is good and acceptable in the sight of God our Saviour,
who will have all men to be saved, and come to the knowledge of the Truth.

For our Saviour is not come to destroy men`'s lives, but to save them;
not to influence his followers to be unfaithful to
whatsoever government he is pleased to set over them;
but on the contrary, to be subject to every ordinance of man for his sake;
being for the punishment of evil doers, and for the praise of them who do well.
To this end, purpose and intent, was government the ordinance of God.

And now, brethren, seeing the Lord has made us members of one body,
and of one household of faith, let us walk in love one towards another, and be content,
whatsoever station our great Father and Master has placed us in;
that he may delight to dwell with us, and give us our daily bread,
and nourish our souls with the milk of his word, up to eternal life:
this is our interest, this is our all;
that righteousness may be established in the earth, and in every house and family;
the fruits whereof are peace, and the effects thereof quietness and assurance forever.

So shall the true Christian sabbath be restored in the earth again, which has been lost,
in this long and dark night of apostasy,
which has been over the nations and families of the earth,
whereon the false church has sat as a queen, and seen no sorrow;
being decked on the outside with fine ornaments, pleasing to the fleshly eye,
whereby thousands have been enticed into her embraces,
because of the beauty and riches of her golden cup;
having not that eye opened which could see her inside,
as it is full of abomination and filthiness;
but the day and hour of her judgment is come, and more abundantly coming,
when the nations shall buy her merchandize no more;
for she has traded in slaves and souls of men, etc., Rev. 18. But the day is sprung,
which has discovered her skirts, and many see her nakedness,
and will trade with her no more.

The true church is returning out of her wilderness condition,
whose clothing is the Sun of righteousness, white as snow; she is travailing in pain,
for the deliverance of her sons and daughters into
the glorious liberty of the sons of God;
all changeable elements are under her feet: you that can read, may.
She is the true mother of all the faithful, and all her children are free,
walking in white linen, which is the saints`' righteousness;
and are inwardly adorned with the ornament of a quiet spirit,
which in the sight of God is of great price.
Her dwelling is within the munition of that rock,
which the gates of hell cannot prevail against.
The streets of her city are pleasant; in the midst of which is the river of life,
and all her flocks drink at it, which can never be drawn dry.
The bread of her city is of the finest of the wheat;
and her wine is well refined from the lees; which all partake of,
who dwell within her gates; and none can enter therein, who work abomination,
or love and make a lie, though her gates stand open by day.
Oh! my dear friends, who are situated within her walls,
you have a sure and quiet habitation, out of the reach of the dragon`'s power:
keep your habitation, and walk in the light of the Lamb;
by which every trap and snare which the enemy lays in your way, will be seen,
and power given to escape.

Go forward in the name and power of the Lord,
and keep your station in the holy order of life, which God has placed you in;
and with zeal and fervency of spirit, keep your holy assemblies,
both first and week-days, that renewed acquaintance you may have with the Lord,
and the operation of his divine power;
through which we have been often renewed in the spirit of our minds,
and preserved through all storms that rose in the winter.

And now many being come to the sabbath-day, there is as much need to watch,
and frequently to pray for the preserving hand of
the Lord of the sabbath to sustain and uphold us,
as ever.
For the crown is at the end of the race; which none can obtain,
but who continue to the end, in faith, patience, and well doing.
Oh! look not back at the glory of the world, and covet not the friendship of it,
which is enmity with God; and whosoever will be a friend of the world,
is an enemy of God.

But endure their hatred with a quiet mind, and have a special care it be for well doing;
and then their reproaches will be of more worth than all their treasures,
and as so many seals and witnesses of the day of your redemption:
for it is the suffering seed that must inherit glory and immortality with the Son,
when days in this world are ended.

And walk inoffensively among the sons and daughters of men, in all gravity and humility,
sobriety and temperance; that it may be known that you are taught by the grace of God,
and saved by its virtue and power, from the pollutions of the world,
and all the defilements of the flesh: for to this end did it appear unto you,
in an acceptable day.

And let young men and women have a care how they look out at the glory of the world,
where is the lust of the eye and the pride of life, which are not of God,
lest they be ensnared with them;
as were the young men of the Hebrews with the daughters of Moab,
which brought a plague upon Israel of old, by which twenty-four thousand fell.
These things were written for our learning, that we should not tempt God,
as some of them tempted him, and were destroyed.

And wait upon the Lord in faith and patience,
and he will give you whatsoever is needful for you, in his own due time;
and that with a blessing added.
This I have learned by long and good experience,
and recommend it to you as a brotherly caution,
not to seek lawful things by unlawful means; for that is not good in the sight of God.
But let the lamp of righteousness go before you, in all outward undertakings,
by which all snares which may be laid in the way, may be avoided,
and you preserved in the dominion of that life and power,
which subdues all things which are not of God.
And be not lifted up into high-mindedness, if the world`'s riches increase upon you;
for it is not always a sign of the favour of God.
And be not cast down when they are taken away;
for it is not always a sign of his displeasure, but may be for the trial of your faith,
patience and constancy in him, whose hand gives and takes away,
according to the good pleasure of his heavenly will;
unto which all his true-born children truly and patiently submit, and say,
"`Your will be done in earth, as it is done in heaven.`"

And walk in Him, your heavenly head, you who are elders, fathers and mothers of families,
as examples of gravity, temperance and modesty;
and be careful and watchful over your children, in their young and tender years;
and beware of letting them alone, without due and loving reproof,
for the least appearance of evil, in word or deed;
for so is the will of God concerning you,
to whom he has given power in their younger years,
to restrain every appearance of evil in them.
For they are of your loins, and you must be accountable for their evils, till they know,
and be made sensible of the Spirit of Truth in themselves; which,
when they come to the knowledge of, and by you are recommended thereunto,
if they turn aside therefrom, either to the right or left hand, you are so far clear,
and their miscarriages will lie at their own door; and their reward will be,
as those who know the Truth and do it not, to be beaten with many stripes.

There is a great obligation on parents,
to bring up their children in the nurture and admonition of the Lord,
the next to thankfulness for the gift of them; for they are blessings to parents,
when they grow up in the fear and wisdom of God,
and a crown of rejoicing to their gray hairs.
This I know by experience:
glory to God on high! who has not left me destitute of his mercy in my old age,
and has given me to see, in a large measure, the travail of my soul in my young years.
He called me by his grace, near the first dawning of the gospel day in our age,
from my father`'s house,
and inclined my heart to inquire after and first seek the kingdom of God and his righteousness,
with a promise to add all other things necessary.
This I have witnessed to be fulfilled to this day; having neither poverty nor riches,
but enough to sustain me, according to my soul`'s desire;
that I might not make my testimony for the Lord chargeable to any:
which has been fully answered to this day;
praises to his worthy and honourable name forevermore.

And you, brethren, who are called and chosen of God to minister his living word,
and made stewards in his house, of his manifold gifts; let your conduct in every respect,
be as becomes the gospel of peace; that it be not blamed, nor its glory eclipsed,
through any uncomely behaviour, either in the sight of friends or enemies:
this will crown your ministry with many jewels.
And be not chargeable, or difficult,
nor more than needs be troublesome to them to whom you minister.
So shall your ministry have room in the hearts of many;
and you be instruments in the hand of our great Master, to turn many to righteousness;
having the promise of God for your reward, to shine as the stars forever and ever.
The consideration of this has overbalanced all my sufferings,
and made them sweet and pleasant to me, in my long pilgrimage in this world,
from the beginning.

And let none be lifted up with their gifts,
or appear in any lordliness over the flock and heritage of God; but in love, charity,
and brotherly kindness, you who are strong, bear the infirmities of the weak;
considering that our great Lord bore all our infirmities,
and took upon him the form of a servant;
and his servants are not greater than their Lord.

My dear brethren, a word to the wise is enough: my brotherly love flows, as a fountain,
towards you all at this time; earnestly desiring,
that our ancient love and unity may be daily increased and renewed among us:
so shall we be firm and strong against all opposition,
both by the world and false brethren.
"`For, from among ourselves have men arisen, speaking perverse things,
to draw disciples after them;`" but they shall not proceed much further,
nor their weapons prosper;
but their folly shall appear to all whose eyes are kept single.

For God will prosper his work and spread his name in the earth;
and many shall yet come to behold the rising of the Sun of righteousness in their hearts;
for so shall the gospel day spring to all nations,
and the ministration of the spirit of life in Christ Jesus,
shall exceed in glory all that ever went before it,
and shall enrich the gentiles with righteousness,
and be the last and greatest that mankind shall be visited with;
by which the knowledge of the power and glory of God, in due time, shall cover the earth,
as the waters do the sea.

Therefore, my beloved friends and brethren, press forward up to your holy city,
without fainting and weariness; and so run, that you may obtain:
and you will always find the Lord an open fountain in the way,
who will daily refresh your souls, and make you as a watered garden.
The Lord God of all our mercies be with us all,
and bless and prosper his work in our hands, to his eternal praise,
and our mutual joy and comfort forever.
With the renewed salutation of my true love to you all, I am

[.signed-section-closing]
Your ancient friend and brother,

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
Rigate in Surrey, the 4th of the Fifth month, 1702.

[.blurb]
=== A Testimony to True Christianity, etc.

The great and everlasting God who created heaven and earth, the sea,
and all that is therein, by his word; also created man in his own image,
which is righteousness and holiness; and brought forth woman, of his bone and flesh,
and breathed into their nostrils the breath of life, so that they became living souls.
He gave them the possession of life, the very tree of it,
with intent and purpose that they might live with him, by it,
in the beauty of his holiness forever; and might enjoy communion and fellowship with him,
during their continuance upon the earth, in his covenant of life made with them.
But they breaking his covenant, by giving ear to the serpent`'s subtlety,
death entered upon them, and reigned over them, and over all, in the fallen state.
Death reigned from Adam till Moses, by whom he added the law,
because of their transgression, which was to continue upon them till the seed, that is,
Christ, came; who was to bruise the head of the serpent, which had prevailed over them,
and had power to destroy that death, which by sin had got dominion over them.
And this is that Christ of God, who in our day is manifested in spirit,
to destroy the works of the devil,
and to restore all mankind into that perfection of holiness, in which they were created.

And all who truly receive him, in his spiritual appearance, and give up to follow him,
in the strait and narrow way of holiness,
to them he now gives power to become sons and daughters of God;
who not only have received the spirit of adoption, but are given up to walk in it,
by which they are able to call God Father; being made sons and daughters of God,
by following the leadings and dictates of his spirit, and begotten by his immortal word,
which lives and abides forever.
These are of that birth which can call no man father, or master, on earth;
and yet are servants of all, for Christ`'s sake, their heavenly Prince of peace,
of whom they have learned to be meek and lowly,
and their souls are entered into rest with him, where the wicked cease from troubling,
and the weary are at rest, and where the voice of the oppressor is heard no more.

And he has broken, and will yet go on to break,
the covenant which many have made with death, i. e.,
to be subjected to the reigning power of it, so long as they are on earth;
and the agreement that they have made with hell, to be under the servitude of sin,
and bondage of corruption, all their lives,
and never to be freed from sin and corruption all their days,
as thousands are seduced to believe.

Hereby the coming, suffering, death, resurrection and ascension of Jesus Christ,
our complete Saviour and Mediator, are made void and of none effect;
and the blood of his cross counted a vain thing; which is a great offence against God.
For, first, his coming and manifestation was to take away sin, 1 John 3:5.
"`Little children, let no man deceive you:
he that does righteousness is righteous, even as he is righteous,`" verse 7.
"`Whosoever abides in him, sins not: whosoever sins,
has not seen him, neither has known him,`" verse 6.
"`He that commits sin,
is of the devil; for the devil sins from the beginning.
For this purpose the Son of God was manifested,
that he might destroy the works of the devil,`" 1 John 3:8. "`Whosoever is born of God,
sins not; for his seed remains in him: neither can he sin, because he is born of God.
In this are the children of God known, and the children of the devil:
whosoever does not righteousness, is not of God,
neither he that loves not his brother,`" 1 John 3:9-10.
So they who plead for sin to continue in their mortal bodies during life,
do oppose the benefit of his coming and manifestation, which was to take away sin,
and to finish transgression, 1 John 3:5, Heb. 9:1,26 Tim. 1:15, Dan. 9:24,
and consequently of the benefit of his suffering, death, resurrection,
and ascension into glory; he being a perfect sacrifice for sin, and a Mediator,
who has power to destroy him that had the power of death, that is, the devil,
Heb. 2:14:
"`and deliver them who through fear of death were all their lifetime subject to bondage,`"
verse 15.
"`Who ascended far above all heavens,
that he might fill all things: and he gave some, apostles; some, prophets; some,
evangelists; some, pastors and teachers; for the perfecting of the saints,
for the work of the ministry, for the edifying of the body of Christ.
Till we all come in the unity of the faith, and of the knowledge of the Son of God,
unto a perfect man,
unto the measure of the stature of the fullness of Christ,`" Eph. 4:10-13.

Thus they magnified him, who were true witnesses of the power of his death,
and virtue of his resurrection and ascension, by which they obtained victory over death,
darkness, and the power of the grave; and were made more than conquerors,
through him that loved them, Rom. 8:37. And gave thanks to God,
who had given them victory through Jesus Christ, and triumphed over death,
and the sting of it, which is sin, 1 Cor. 15:55-57.

Secondly, those who believe that men must carry about with them a body of sin,
while on earth, do, as to themselves,
make the circumcision and baptism of Christ of no effect,
repugnant to the apostle`'s testimony, Col. 2:10-11. "`You are complete in him,
who is the head of all principality and power: in which you are circumcised,
with the circumcision made without hands;
to the putting off the body of the sins of the flesh, by the circumcision of Christ.
Buried with him by baptism, wherein also you are risen with him,
through the faith of the operation of God,
who has raised him from the dead,`" Col. 2:10-12. And also John,
though a minister of water baptism, yet testified of Christ,
that "`he should baptize them with the Holy Spirit and with fire:
whose fan is in his hand, and he will thoroughly purge his floor +++[+++mark thoroughly]
and gather his wheat into his garner;
but the chaff he will burn with unquenchable fire,`" Matt. 3:11-12.
Here is a thorough separation,
the wheat from the chaff;
Christ`'s baptism leaves not a body of sin in them who are baptized with it:
for as "`many as were baptized into Christ, were baptized into his death;
they were buried with him by baptism into his death;
that like as Christ was raised up from the dead by the glory of the Father;
so also they should walk in newness of life.
Knowing that our old man is crucified with him, that the body of sin might be destroyed,
that henceforth we should not serve sin,`" Rom. 6:3,4,6.

Thirdly, they who plead for the continuance of sin all a man`'s days,
have made the blood of Christ of no more value than the blood of bulls and goats,
offered in the first covenant, sprinkling them that were unclean,
and which sanctifies as touching the purifying of the flesh.
But how much more shall the blood of Christ, who through the eternal Spirit,
offered himself without spot to God,
purge your consciences from dead works to serve the living God? Heb. 9:13-14.
Here was an inward purging of the conscience from death and dead works,
by virtue of the blood of Jesus.
Here is the antitype of Moses, sprinkling the people under the law,
with water and the blood of calves and goats, with purple wool and hyssop;
who sprinkled the tabernacle with blood, and all the ministering vessels, saying,
"`This is the blood of the Testament which God has appointed unto you,`" Heb. 9:19-21.

For if the blood of bulls and goats could have taken away sin,
there had been no need of another sacrifice: but finding fault with them, he says,
"`Behold, the days come, says the Lord,
when I will make a new covenant with the house of Israel, and with the house of Judah;
not according to the covenant that I made with their fathers,
in the day when I took them by the hand, to lead them out of the land of Egypt.
Because they continued not in my covenant, I regarded them not, says the Lord.`"

"`For this is the covenant that I will make with the house of Israel; after those days,
says the Lord, I will put my laws in their minds, and write them in their hearts;
and I will be to them a God, and they shall be to me a people.`"

"`And they shall not need to teach every man his neighbour, and every man his brother,
saying, Know the Lord; for all shall know me, from the least to the greatest,`" etc., Heb. 8:8-11.

Here is known the blood of sprinkling, which speaks better things than that of Abel,
and which is able to cleanse from all sin, and sanctify throughout in body,
soul and spirit; ending all the offerings and sacrifices of the law and first covenant,
which could not make the comers thereunto perfect, as pertaining to the conscience, Heb. 9:9.
And therefore could not continue, but was annulled,
for the weakness and unprofitableness thereof;
being but shadows and types of the spiritual sprinkling,
sanctifying and purifying of the heart and conscience, by the blood of Jesus,
the Lamb without spot,
who by "`one offering has perfected forever those
who are being sanctified,`" Heb. 10:14.

Fourthly, they who plead for a body of sin, for term of life,
make the circumcision of Christ of no value, and Paul,
that great minister of the true gospel, to bear a false testimony, etc.
He said to the Romans, who were baptized into the death of Christ,
which is a death unto sin; "`Knowing this, that our old man is crucified with him,
that the body of sin might be destroyed,
that henceforth we should not serve sin,`" Rom. 6:6. "`There is, therefore,
now no condemnation to them which are in Christ Jesus, who walk not after the flesh,
but after the spirit: for the law of the Spirit of life, in Christ Jesus,
has made me free from the law of sin and death,`" Rom. 8:2.
"`For while you were servants to sin,
you were free from righteousness; but now being free from sin,
and made servants unto God, you have your fruit unto holiness,
and the end everlasting life,`" Rom. 6:20,22.
Fifthly, they who do not believe a freedom from sin on this side the grave,
make the promise of Christ to the Jews that believed in him, of none effect, who said,
"`If they continued in his word, then were they his disciples indeed;
and they should know the Truth,
and the Truth should make them free,`" John 8:31-32.
"`And if the Son (who is the Truth) make you free, then you are free indeed,`" verse 36.

This freedom, by the Son,
is obtained by none but those who are given up to follow him and obey his word,
to whom he gives power, not only to be servants, but sons of God:
neither can any stand fast in this freedom, but as they are daily supported by his power,
in whom their freedom stands; this made the apostle exhort the saints,
who were born of the free woman by promise,
to "`stand fast therefore in the liberty with which Christ has made them free,
and be not entangled again with the yoke of bondage,`" Gal. 5:1. And to the Hebrews,
"`Forasmuch as the children were partakers of flesh and blood;
he also himself took part with them,
that through death he might destroy him that had the power of death, that is the devil.
And that he might deliver them, who through fear of death,
were all their life time subject to bondage.`"

Now a body of sin, all the life long, keeps the soul in bondage;
from which bondage the Son of Man is come to deliver.
For the creature was made subject to vanity, not willingly,
but by reason of him who has subjected the same in hope.
Because the creature itself also shall be delivered from the bondage of corruption,
into the glorious liberty of the children of God.
For we know that the whole creation groans and travails in pain together, until now,
Rom. 8:21-22, that is, till the work of deliverance by the Son of God was known,
who was, and is able to save to the uttermost, all who come to God by him;
seeing he ever lives to make intercession for them, Heb. 7:25.
So he was and is a perfect Saviour to save his people,
disciples and followers from (mark, not in) their sins, Matt. 1:21.

Sixthly, they who deny perfection in this life, make the command of Christ of no force, Matt. 5:48.
His command was to living men, not dead: Be perfect,
as your heavenly Father is perfect.
Now if this perfection is not attainable, the lip of Truth would not have commanded it;
whose commands were ever just, and not grievous, 1 John 5:3.

Seventhly, they who do not believe perfection in holiness on this side the grave,
have undervalued, and not truly believed, Christ`'s prayer, John 17:23, I in them,
and you in me, that they may be made perfect in one;
and that the world may know that you have sent me, and have loved them,
as you have loved me.
And also Paul`'s testimony to the Corinthians,
And my speech and preaching was not with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power.
That your faith should not stand in the wisdom of man, but in the power of God.
Howbeit we speak wisdom among them that are perfect; yet not the wisdom of this world,
nor of the princes of this world, that come to naught, 1 Cor. 2:4-6.
And in his second epistle, he exhorted them to press on to perfection, 2 Cor. 13:11.
And the same apostle, writing to the Ephesians, speaks thus of Christ;
He that descended, is the same also that ascended up far above all heavens,
that he might fill all things.
And he gave some, apostles; some, prophets; some, evangelists; and some,
pastors and teachers: for the perfecting of the saints, for the work of the ministry,
for the edifying of the body of Christ.
Till we all come in the unity of the faith, and of the knowledge of the Son of God,
unto a perfect man, unto the measure of the stature of the fullness of Christ, Eph. 4:10-13.

Now these gifts are all void, and of none effect,
with those who do not believe any perfection to be witnessed in this life.
It is a manifest token they know nothing of them, nor the work of the true ministry,
nor the gradual steps of all true gospel believers, towards the perfection of holiness,
in the sight of God, which all true followers of Christ are pressing forward to obtain,
through the power and efficacy of the life of Jesus,
which is brought to light and manifested in mortal flesh, in our day,
through the gospel of our Lord and Saviour Jesus Christ,
which is a gospel of glad tidings; i. e. deliverance from the slavery of sin and Satan,
and perfect redemption, reconciliation and salvation, brought near to every man`'s house,
to be wrought in man by Christ, God`'s great workman.
This all who truly believe in him are living witnesses of; being made his workmanship,
created in Christ Jesus unto good works, that we should walk in them;
according to Eph. 2:9-10. They only who are true witnesses of this work,
can praise the Lord, being made living members of that body, of which Christ is head,
ruler and lawgiver.
They are not of this world, as he is not of this world;
neither seek the honour or preferment of it; but are as strangers and pilgrims in it.
And though they are on earth, yet their citizenship is in heaven;
having the seal of the Spirit of God, bearing witness with their spirits,
that they are the sons and daughters of God.

This is the effect and fruit of the true gospel day,
wrought and brought forth in all them who walk in it to the end.
These are not tossed to and fro with every wind of doctrine, through the sleight of men,
and cunning craftiness of those who lie in wait, for their ungodly gain, to deceive;
but are born of that elect seed, into which no deceiver can enter;
and walk in the light of the Lamb, according to the prophecy of John, Rev. 21:23-24,
wherein is no night or shadow of death.
These have the white stone, and a new name, which no man knows but he who has it;
and are clothed in white linen, which is the Lamb`'s righteousness,
put upon them by him who has wrought it in them; having oil in their own lamps,
and are ready to enter with the bridegroom, whenever he calls.

But let those consider of it who have not oil in their own lamps,
but are forced to go to them that sell;
that they may read how such were entertained by the heavenly Bridegroom,
Matt. 25. "`Then shall the kingdom of heaven be likened unto ten virgins,
which took their lamps, and went forth to meet the bridegroom.
And five of them were wise, and five were foolish.
They that were foolish took their lamps, and took no oil with them:
but the wise took oil in their vessels with their lamps.
While the bridegroom tarried, they all slumbered and slept.
And at midnight there was a cry made, Behold the bridegroom comes; go out to meet him.
Then all those virgins arose, and trimmed their lamps.
And the foolish said unto the wise, Give us of your oil; for our lamps are gone out.
But the wise answered, saying, Not so; lest there be not enough for us and you:
but rather go to them that sell, and buy for yourselves.
And while they went to buy, the bridegroom came;
and they that were ready went in with him to the marriage: and the door was shut.
Afterwards the other virgins also came, saying, Lord, Lord, open to us.
But he answered and said, Verily I say unto you, I know you not.`"

Now these were accounted virgins, and knew their duty in their life time,
which was to have oil within, to keep their lamps always burning to be ready to enter,
whensoever their soul`'s bridegroom came.
But the foolish did not, yet were sensible they needed it, when the bridegroom came,
and so went to buy of them that sold.
But oh! while they were gone, the door was shut,
and they could not enter the marriage-chamber.
Oh! dread and fear this, all you who are gone out to buy,
lest the door of entrance be shut against you forever.

Eighthly, they who plead for sin and imperfection to remain,
during all the days of their lives, have thereby, to themselves,
subverted the testimony of John, the beloved disciple, 1 John 4:17:
Herein is our love made perfect, that we may have boldness in the day of judgment;
because as he is, so are we in this world; +++[+++mark, in this world.]
He did not say, welcome death to make us perfect,
as some imperfect workmen have done of late;
attributing more power and virtue to a winding-sheet, than to the blood of Jesus Christ,
repugnant to the testimony of the saints and true believers, who in their day testified,
that if they walked in the light, as God is in the light,
they had fellowship one with another, and the blood of Jesus Christ, his Son,
cleansed them from all sin, 1 John 1:7. This John spoke in the faith,
which the believers were growing up into; which afterwards they witnessed,
as I have noted above.
Ninthly, they who say, they cannot be made clean in this world,
have no share in those blessings which Christ pronounced, Matt. 5:8:
Blessed are the pure in heart, for they shall see God: and,
Blessed are they who do hunger and thirst after righteousness, for they shall be filled, verse 6.

Now none can be filled with righteousness, or witness a pure heart,
while a body of sin remains; neither can any be made partakers of the living faith,
which purifies the heart, 1 Pet. 1:22, Acts 15: 9, 1 Tim. 1:5,
while they continue in the sin and unbelief, that they cannot be made pure in this world, etc.
And if not in this world, it highly concerns every such, while they have a day,
to consider when or where they shall be made free and fit to enter the kingdom of heaven,
where no unclean person can come, Eph. 5:5, Isa. 38:18,
neither can death nor the grave praise the Lord,
nor they that go down to the pit hope for his Truth.

[.discourse-part]
_Objection:_
But the great objection and plea, that many in our day have, is that in John,
where he says, If we say that we have no sin, we deceive ourselves,
and the Truth is not in us, 1 John 1: 8, supposing, that neither he,
nor any of the holy men of God, either did,
or ever was to know a better state and condition, than continuing in sin all their days;
which is a great mistake, and of dangerous consequence, as all may see,
who read 1 John 3:2-9: Beloved, now are we the sons of God,
and it does not yet appear what we shall be: but we know that when he shall appear,
we shall be like him; for we shall see him as he is.
And every man that has this hope in him, purifies himself, even as he is pure.
Whosoever commits sin transgresses also the law: for sin is the transgression of the law.
And you know that he was manifested to take away our sins, and in him is no sin.
Whosoever abides in him sins not: whosoever sins has not seen him, neither known him.
Little children, let no man deceive you: he that does righteousness is righteous,
even as he is righteous.
He that commits sin is of the devil; for the devil sins from the beginning.
For this purpose the Son of God was manifested,
that he might destroy the works of the devil.
Whosoever is born of God does not commit sin; for his seed remains in him:
and he cannot sin, because he is born of God.
In this the children of God are manifest, and the children of the devil.

And 1 John 4:17, Herein is our love made perfect,
that we may have boldness in the day of judgment: because as he is,
so are we in this world.

Here was perfection witnessed by them in this world, being made more than conquerors,
through him that loved them, Rom. 8:37.

And Paul writing unto the Romans, says; That as sin has reigned unto death,
so grace might reign through righteousness, unto eternal life, by Jesus Christ our Lord.
What shall we say then?
Shall we continue in sin, that grace may abound?
God forbid.
How shall we, that are dead to sin, live any longer therein? Rom. 5:21.
and 6:1.

And writing to the Ephesians, about the state of the church,
he exhorted husbands to love their wives, even as Christ loved his church,
and gave himself for it; that he might sanctify and cleanse it,
with the washing of water, by the word,
that he might present it to himself a glorious church, not having spot, or wrinkle,
or any such thing; but that it might be holy and without blemish, Eph. 5:27.

This is the church of the first-born, which Paul testified of to the Hebrews,
who were come unto mount Zion, and unto the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels;
to the general assembly and church of the first-born, which are written in heaven,
and to God the Judge of all, and to the spirits of just men made perfect, Heb. 12:22-23.

And Jesus said unto his disciples, Behold,
I give you power to tread upon serpents and scorpions,
and over all the power of the enemy, and nothing shall by any means hurt you.
Notwithstanding in this rejoice not, that the spirits are subject unto you,
but rather rejoice because your names are written in heaven.
Here was perfect freedom to the church, who were made partakers of that precious faith,
which then was delivered to them, by which they had victory over death,
hell and the grave, and were made a habitation of God through the Spirit: Eph. 2:19-22.

They were far from pleading for the continuance of
sin during the whole course of their lives,
as many in our days are doing; who though they profess Christ in words,
yet in works deny him, which is a sort of atheism;
and so their works give their words the lie; for it is not words, but works,
that manifest true faith, James 2:14,17-18,
20-25.
For as the body without the spirit is dead, so faith without works is dead also, verse 26.
They who are out of that faith which purifies the heart,
and gives victory over the world,
and do not believe any victory on this side of the grave, their preaching is vain,
and their faith vain, and they are yet in their sins; and what is worse,
will not believe any freedom from sin in this world.
Christ is not king, governor and bishop in the souls of such;
neither have they part in him, who is the resurrection and the life,
because not washed and sanctified by him; for he said to Peter, if I wash you not,
you have no part with me, John 13:8-10.

[.discourse-part]
_Objection:_ But I have heard some affirm, that God allows sin, in the dearest of his children,
to keep them humble.

This is a doctrine of antichrist, and has not the least footing in the Holy Scripture,
neither was ever heard of among the worst of the Jews`' false prophets,
that ever I heard or read.
For if sin be the cause of humility, Christ came in vain,
who was the perfect pattern of humility, in whom was no sin,
neither was guile found in his mouth, 1 Pet. 2:22.

But it is the power of God that delivers man from sin,
and keeps him in a daily humble frame of mind and spirit,
to be preserved through faith to the end of time.
This made Paul, when his departure drew near, not boastingly, but humbly to say,
I have fought a good fight, I have finished my course, I have kept the faith.
Henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge shall give me at that day; and not to me only,
but unto all them also that love his appearing, 2 Tim. 4:6-8.
He had not the great work of salvation
and victory to do at his departure out of the world;
but witnessed it done, and boldly testified it to Timothy, as some of his last words.

And Peter, when near his departure out of the world, having magnified the power of God,
through which they had escaped the corruption that is in the world through lust,
exhorted the saints to give diligence, to make their calling and election sure, 2 Pet. 1:4-10.
This could not be made while sin remained in their mortal bodies;
an end therefore was to be witnessed while they were on earth;
for king Hezekiah had before testified,
that the Lord had delivered his soul from the pit of corruption,
and cast all his sins behind his back.
For the grave cannot praise you, death cannot celebrate you;
they that go down into the pit cannot hope for your Truth, Isa. 38:17-18.
Now if death cannot celebrate the name of the Lord,
nor the grave praise him, as above, what a deplorable condition are they left in,
who are persuaded to believe, that they must have a body of sin till death,
and can never be made free on this side the grave?
I leave this to God`'s witness in all consciences deeply to consider.

And further, I desire all who are for the continuance of sin during life, to discover,
if they can, by the Holy Scripture,
when and where men and all mankind shall be thoroughly cleansed from it:
whether before death, at, or after it, between death and judgment;
seeing that no unclean person, nor covetous man, who is an idolater,
has any inheritance in the kingdom of Christ, or of God, Eph. 5:5. And John,
in the Revelation, testified, concerning the heavenly city,
that there shall by no means enter into it, anything that defiles,
or causes an abomination or a lie;
but they who are written in the Lamb`'s book of life, Rev. 21:27.

[.discourse-part]
_Objection:_ But some have objected and said,
that if people be thoroughly cleansed from sin on this side the grave,
they need no Mediator or advocate, etc.

The consequence is unjust, and falsely deduced.
There is need of Christ as Mediator and advocate for all mankind,
for whom Christ prays or makes intercession,
and that is both for transgressors and saints;
for the unsanctified and for the sanctified; for the first, that they may be sanctified;
for the last, that they may be preserved and kept from the evil:
therefore there is need of Christ as advocate for all mankind.

[.discourse-part]
_Query:_
In what state may persons have the real benefit of Christ`'s mediation and intercession,
in order to receive forgiveness and salvation?

[.discourse-part]
_Answer:_ In a state of need thereof, and true desire thereafter;
and when they do not harden their hearts unto willful sinning.
Christ makes intercession for men, while they have a day of visitation,
wherein his Spirit strives with them.
But as his Spirit will not always strive with men, if they persist in rebellion;
so Christ will not always intercede for them.
There is a sin unto death (or a willful sinning till
death) for which there is no pardon obtained by sacrifice,
advocate or mediator; seeing the apostle to the Hebrews says, If we sin willfully,
after we have received the knowledge of the Truth,
there remains no more sacrifice for sin: but a certain fearful looking for of judgment,
and fiery indignation, which shall devour the adversaries, Heb. 10:26-27.

But there is a sin, not unto death, concerning which, John wrote to the little children,
saying, My little children, these things write I unto you, that you sin not;
and if any man sin, we have an advocate with the Father, Jesus Christ the righteous, 1 John 2:1.
For this sin, there is an advocate and mediator.
If any man see his brother sin a sin which is not unto death, he shall ask,
and he shall give him life for them that sin not unto death, etc.

Here the benefit of Christ`'s mediation and intercession,
being our advocate with the Father, is received, and not slighted or frustrated;
for he said, The Son of man is as a man taking his journey into a far country,
who left his house, and gave authority to his servants, and to every man his work,
and commanded the porter to watch.
Watch therefore, for you know not the day nor hour when the master of the house comes;
at evening, or at midnight, at cock-crowing, or in the morning:
lest coming suddenly he find you sleeping.
And what I say unto you, I say unto all, Watch: Mark 13:34-37.
Now there is no state on this side the grave, above a watchful state;
for though the enemy is cast out of the house, that is, the heart,
and it be swept and garnished; yet for lack of watchfulness and circumspection,
the enemy takes to him seven other spirits, worse than himself,
and they enter in and dwell there,
and the latter end of that man is worse than the first.
When the unclean spirit is gone out of a man, he walks through dry places, seeking rest;
but finding none, he says, I will return unto my house from which I came, Luke 11:24-26.

Upon this account the apostle Peter exhorted the saints, to be sober and vigilant;
because, said he, your adversary, the devil, as a roaring lion, walks about,
seeking whom he may devour; whom resist, steadfast in the faith;
knowing that the same afflictions are accomplished
in your brethren that are in the world.
But the God of all grace, who has called us unto his eternal glory by Christ Jesus,
after that you have suffered a while, make you perfect, establish, strengthen,
settle you, 1 Pet. 5:8-10.

And Jude the apostle said, The angels that kept not their first state,
but left their own habitation, he has reserved in everlasting chains, under darkness,
unto the judgment of the great day, Jude 6. This was written not to be imitated,
but to excite watchfulness in all who are come to be made a habitation of God,
through the Spirit, that they may keep their habitations,
and go no more forth to them who say, lo, here is Christ; or lo there.
Yes, if they shall say unto you, Behold, he is in the desert; go not forth: Behold,
he is in the secret chambers; believe it not, Matt. 24:26. For Christ within,
the hope of glory, is the portion of all who are not reprobates concerning the faith,
2 Cor. 13:5-6.
He dwells and walks in his temple; and his sheep hear his voice,
and follow him, John 10:27-3, but a stranger will they not follow.

But the sure habitation, and safe resting place, is the name of the Lord;
the righteous runs into it, and is safe: Prov. 18:10. Here no devourer can come,
nor ravenous beast enter; and those who continue to the end therein, in faith,
patience and well-doing, have immortality and everlasting life,
being living witnesses of the eternal purpose of
God in sending his only begotten Son into the world,
i+++.+++ e. to finish transgression, and to make an end of sin,
and to bring in everlasting righteousness, according to the prophecy of Daniel: Dan. 9:24.
Such have the benefit of his coming, and of his death,
resurrection and ascension, and know him their Mediator,
to make intercession to the Father for them, day and night: John 17:6-11,
that they may be preserved from all sin.

Perfection of freedom from sin in this world, can never be witnessed by any,
but by them who receive Christ, as the Father has given him,
with faith and full assurance,
that he is both willing and able to finish transgression in every soul, and to bring in,
and fill it with everlasting righteousness, in place and stead thereof;
and to save to the uttermost all who obey him, and come to God by him.
And by his obedience, all who follow him therein to the end, are sanctified and purified,
and shall be glorified with the glory which he is pleased to give them;
and so are made his jewels, fit to be gathered into his treasury forever.
These are witnesses of the end of their faith, even the salvation of their souls;
and able to put their seal to the benefit of the coming, suffering, death,
resurrection and ascension of Christ, their mediator and advocate:
and therefore perfection and freedom from sin must be believed,
and pressed after in this life, or else it can never be truly known or attained unto;
nor the benefits of the coming, death,
resurrection and ascension of Christ Jesus received.

Therefore, woe to that grand enemy of mankind,
who has blinded the world from seeing and believing
those things which belong to their everlasting felicity;
but persuades them, and overpowers them to spend their days in vanity,
and to go down to the grave with sorrow, and die in their sins and pollutions,
as Christ told the Jews, John 8:21-24: If you believe not that I am he,
you shall die in your sins; and if you die in your sins, where I go, you cannot come.

Now the outward Jews, who would not believe him in his outward appearance,
and therefore shut the door of entrance into the kingdom of God against themselves,
died in their sins, not believing the benefits of his coming, offering, resurrection,
or ascension.
So let the outward Christians now beware, lest by rejecting,
and not receiving him in his inward and spiritual appearance,
they shut the door of entrance into the kingdom, against themselves;
and give up to be captivated under the power of sin and Satan all their days;
for God will not be mocked, neither will his Spirit always strive,
nor offer itself to give knowledge of the secrets of God to mortals:
but the day of their visitation will come to an end; and then they shall cry,
and he will not hear; and seek death, and shall not find it.

For the great God of Israel has sent his only begotten into the world,
in his spiritual appearance, to fulfill the law, and to finish transgression,
and to bring in everlasting righteousness; and all who will receive him,
and give up to follow him in the regeneration,
he will give them power to become the sons and daughters of God;
and give them the spirit of adoption, to enable them to cry, Abba, Father;
they are not of the world, even as he is not of the world,
therefore the world hates them.

And now let all who believe no better than that they must be under
the bondage of corruption all the days they have to live on earth,
seriously weigh and consider, when or where they shall be made free,
seeing no unclean person can ever enter the kingdom of God: Eph. 5:5.
And let the learned rabbis resolve them, if they can;
for it highly concerns them, that their day may not end, before their work be done,
and the night come upon them, wherein no man can work.

It is not the profession of Christianity, but the work of it in the soul,
that renders mankind good and acceptable in the sight of God.
I shall only set down a few,
among the many testimonies which were given by the ancient primitive Christians,
many ages ago, left upon record to this day.
Clemens of Alexandria gave this short account of them:

[.embedded-content-document]
--

No man is with us a Christian, or accounted truly rich, temperate and generous,
but he that is pious and religious; nor does any further bear the image of God,
than he speaks and believes what is just and holy;
so that in short is the state of us who follow God.
Such as are our desires, such are our discourses: such as are our discourses,
such are our actions: such as are our actions, such is our life:
so universally good is the whole life of Christians.
Certainly none were greater enemies to a naked profession,
and the covering of a bad life, under the title of Christianity.
Do any live otherwise than Christ has commanded?
it is a most certain argument they are no Christians,
though with their tongues they ever so smoothly profess the Christian doctrine;
for it is not merely professors, but those who live according to their profession,
that shall be saved;
as Justin Martyr declared before the emperors.--[.book-title]#Primitive Christianity, Part 1. c. 4.#

--

[.embedded-content-document]
--

Let no man +++[+++says Basil,]
impose upon himself with inconsiderate words, saying, though I be a sinner,
yet I am a Christian; and I hope that title shall be my shelter.
But hearken sinner, all wicked men shall be bundled up together,
and in the great day of divine vengeance shall be indifferently thrown into those
merciless and devouring flames.--[.book-title]#Primitive Christianity Part 1. fol. 82. c. 4.#

--

Now was corruption creeping into the profession of Christianity;
but the upright among them saw it, and gave an early testimony against it;
but yet it was not grown to that height of presumption,
to plead for the continuance of a body of sin all their days;
that came in by degrees afterward,
in the midnight of darkness and apostasy from the life of Jesus,
our complete Saviour from sin.

Out of this corruption, the pope sprung, who assumed the honourable title of Christian,
and high father, or father of fathers therein: but falling later in the apostasy,
the church was overwhelmed with more corruption, and set up those things,
which the more pure and primitive Christians decried and abhorred;
which are too large to mention here.

Being under the bondage of corruption, and ignorant of the power of God,
and the sufficiency thereof, to deliver the soul from the pit of corruption in this life,
the false church concluded that all mankind must
carry about them a body of sin all their days.
Then did the enemy step in with another delusion, more subtle than before,
and put them upon an invention of a purgatory, or a place of cleansing from sin,
between death and the day of judgment,
which there is not the least colour in the Holy Scriptures to justify.
But the nobility of the people`'s understandings being clouded with darkness,
this was received among them for orthodox, and is to this day among thousands, who err,
not knowing the Scriptures, nor the power of God.

And now, my dear friends and countrymen, into whose hands this may come,
let moderation and the fear of God attend you in the reading of it; as the love of God,
and a heart of compassion towards you, have attended me in the writing of it.
That notwithstanding the subject matter herein contained has been written by some before,
yet I could not be clear, not knowing how short my time may be in this world,
but leave a testimony also of the coming of our Lord Jesus Christ, in spirit,
in this latter age of the world, to work his Father`'s will in every soul,
which is sanctification, and redemption from sin, death, darkness,
and the power of the grave; of which, in my little measure,
I have been an eye witness many years;
not proposing any outward benefit or advantage to myself in writing it;
but the good and wellbeing of mankind,
that they may come to the knowledge of the Truth
by which they may be made free and be saved,
through faith in the Son of God, while they live; and that they may see,
and be made partakers of the benefit of the spiritual
appearance and work of the Just One;
of which all the prophets, from Moses, bore testimony.

His coming, in these latter days, has discovered the workings of Satan,
in the long and dark night of apostasy, which have been over the world,
since the apostles`' days, with all unrighteous deception;
wherein the false church has decked herself with pretences to the jewels of the true,
and has sat as a queen, arrayed in fine outward garments,
pleasant and delightful to the outward eye; and also her golden cup,
engaging to the carnal mind and affection; and her temple, like those which Origen,
the ancient Christian, testified against among the Egyptians:

[.embedded-content-document]
--

When you approach
their sacred places, they have glorious groves and chapels,
temples with goodly gates and stately porticos,
and many mysteries and religious ceremonies; but when once you are entered,
and got within their temples, you shall see nothing desirable there, etc.
But like the woman, which John testified of, who was arrayed in purple,
and scarlet colour, decked with gold and precious stones and pearls,
having a golden cup in her hand, full of abominations, and filthiness:
and upon her forehead is written,
"`Mystery, Babylon the Great, the Mother of Harlots, and Abominations of the Earth,`"
Rev. 17:4-5.--[.book-title]#Primitive Christianity Part 1. p. 1.#

--

Nevertheless, many have been in love with her, delighting to drink of her cup,
who could not see her inside.
But now the great Searcher of hearts is come,
and the flying roll of his wrath is entering,
and will more and more enter into the house of the thief,
and into the house of the false-witness-bearer, who say, Thus says the Lord,
and the Lord never spoke to them, and shall destroy it,
with the stones and timber thereof: the mouth of the Lord of hosts has spoken it,
and it shall come to pass in its season: Zech. 5.

But Zion, which has been as a widow forsaken, shall become as a fruitful hill,
and shall no more be called desolate, nor forsaken,
but shall put on her beautiful garments;
and the Lamb and his followers shall dwell there, where shall be no night,
or shadow of death; and Jerusalem shall be a quiet habitation,
salvation shall be for walls and bulwarks, and the entrance thereof praise;
there is no temple there, but the Lamb, henceforth and forever.

Written with a heart of love and compassion to the souls of people everywhere,
that they may know the seed of God to arise, and bring forth righteousness in them,
by a lover of all mankind.

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
Rigate in Surrey, the 22nd of the Tenth month, 1702.
