== Chapter VIII

=== The Gospel of our Lord Jesus Christ Witnessed Unto, etc.

The true and everlasting gospel is glad tidings, namely, deliverance, redemption,
and reconciliation of all mankind to God again.
It is the power of God to salvation, to everyone that believes, Rom. 1:16,
in and by which Christ is manifested in mortal flesh,
to ransom mankind from the bondage of corruption into the
glorious liberty of the sons and daughters of God:
Rom. 8:21, perfectly fulfilling the prophecy of Isaiah concerning Christ:
Isa. 42:6-7, The Lord has called you in righteousness, and will hold your hand,
and will keep you, and give you for a covenant to the people,
and for a light to the Gentiles; to open the blind eyes,
and to bring out the prisoner from the prison, and them that sit in darkness,
out of the prison house.

The proclamation of this gospel, is peace on earth, and good will to men, Isa. 52:7,
and 66:12, Luke 2:14, in our day, as in ancient days; wherein Christ,
the Prince of peace, is manifested in his spiritual appearance,
to destroy the works of the devil, and to be the same saviour, deliverer, and redeemer,
as ever he was.
His gospel is the same in its divine property,
bringing forth the same fruits and effects in every soul, who believes and obeys it,
which the Holy Scriptures bore testimony of in ancient days,
that was then brought forth and effected by Christ, the power and wisdom of God,
in mankind, who received and gave up to follow him, the captain of their salvation.

Here is an end of all outward war, fightings and bloodshed; the Prince of our peace,
in his spiritual appearance and work, being not come to destroy men`'s lives,
but to save them; and to give his life a ransom for many: Matt. 20:28, Mark 10:45, Luke 9:56.

So that the ancient prophecy of Isaiah is here again fulfilled,
The wolf and the lamb shall feed together, and the lion shall eat straw like the bullock;
and to the serpent, dust shall be his food:
they shall no more hurt nor destroy in all my holy mountain, says the Lord: Isaiah 65:25.

All true gospel believers are come to be living witnesses
of the fulfilling of this in our day,
who are made to love enemies; and if they hunger, to feed them; and if thirsty,
to give them drink; according to the ancient gospel precept, and the command of Christ: Matt. 5:44.
And also his minister`'s exhortation to the Romans, Dearly beloved,
avenge not yourselves, but give place unto wrath; for it is written, vengeance is mine,
and I will repay it, says the Lord.
Therefore if your enemy hungers, feed him, if he thirsts, give him drink;
for in so doing, you shall heap coals of fire on his head: Rom. 12:19-20.

The true ministers of this gospel have their commission from God alone,
and are not made by the will and wisdom of man,
but by the revelation of Jesus Christ in them,
according to Paul`'s testimony to the Galatians; I certify you, brethren,
that the gospel which was preached of me, is not after man;
for I neither received it of man, neither was I taught it,
but by the revelation of Jesus Christ: Gal. 1:11-12. These are commissioned of God,
to turn people from darkness to light, and from the power of Satan, unto God;
that they may receive forgiveness of sins,
and an inheritance among them which are sanctified by faith in Christ Jesus;
according to Paul`'s testimony before king Agrippa: Acts 26:18.

The fruit and effect of their ministry, is a holy life, and godly conduct,
which is of great price in the sight of God.
These have received freely, and do minister freely; coveting no man`'s silver, gold,
or apparel; neither are they lords and masters over God`'s heritage,
but examples of self denial to the flock; being servants to all for Christ`'s sake,
and minister in the ability that God gives, be it less or more.
These gather not to themselves, but to Christ, the great Shepherd and Shiloh,
sent of God, according to Jacob`'s prophecy before his death;
i+++.+++ e. The sceptre shall not depart from Judah, nor a law-giver from between his feet,
until Shiloh come; and unto him shall the gathering of the people be: Gen. 49:10.

There is another grand fruit, which the true and everlasting gospel brings forth, namely,
charity, which is the bond of perfection: Col. 3:14. The marks of which are,
it suffers long, is kind, and envies not; does not parade itself, is not puffed up,
nor behaves itself unseemly, seeks not its own, is not easily provoked, thinks no evil;
rejoices not in iniquity, but rejoices in the Truth; bears all things, hopes all things,
endures all things: 1 Cor. 13.

These virtues many are made living witnesses of,
by the appearing and springing of the true gospel day,
as they have given up in faithfulness to walk in it;
to them there is no occasion of stumbling; the sun is before them,
and they see no shadow or variableness in their habitation;
neither can darkness come in their way; but they walk in the light of the Lamb,
within the walls of God`'s salvation: Rev. 21.

All these, and many more blessed effects,
has the gospel of our Lord Jesus Christ brought forth in many souls,
by his coming and most glorious manifestation, in this latter age of the world,
wherein all the prophecies of him from Moses, are fulfilled and fulfilling.
And many shall yet come to the brightness of his rising,
and shall shake off their night garments, and put on the armour of light;
and the knowledge of the power and glory of God shall be perfectly restored,
from the least to the greatest; and Christianity shall shine over the earth,
in its ancient beauty and glory,
which has been eclipsed in this long and dark night of apostasy,
wherein the true gospel has been hid for ages.
But the darkness is past, and the true light now shines.
Honour and everlasting praises ascend unto his name, who, in an acceptable day,
visited us.
When we lay polluted in our blood, and no eye pitied us, he had compassion on us,
and said unto us, live; and his word quickened us, and became a light to our feet,
and guided them into the way of holiness, which alone leads to everlasting life.

=== The False Gospel, (or Another Gospel Than That the Apostles Preached,) Which is Sad Tidings, Witnessed Against.

This gospel, though it has many of the words of the true,
yet its fruits and effects are diametrically different:
for here is no freedom or deliverance from sin and corruption, till death comes;
as if that were its redeemer, and a winding sheet, its deliverer;
always till then slavery, and no freedom or victory: like a false,
evil and discouraging captain, who shows his soldiers a great enemy,
and bids them go to fight against him, but tells them beforehand,
they shall never overcome him so long as they live on earth.
Neither do such show them how they shall come to the true captain,
who would put upon them his whole armour of light,
whereby they might be abilitated to quench all the fiery darts of their enemy,
and gain perfect victory over him, and be made more than conquerors,
so that thousands have given themselves over to be conquered; some after one manner,
and some after another.
Here has the unrighteous deception entered the sons and daughters of men for many ages,
since the true gospel-day was hid from them.

The trumpeters of the other gospel have given an uncertain sound,
so that few or none have prepared themselves to war with their soul`'s enemy,
but have given up themselves to be subjected by him at his will;
and so he led them captive into various lusts and vanities,
which have drowned many in perdition; so that the leprosy of sin,
has overspread the nations, till the earth is filled with violence,
and the dark corners thereof are full of the habitations of cruelty:
so that peace on earth, and good will to men, are much lost, and few lay it to heart.

The false church has long made the nations drunk with her wine,
and adulterated their hearts and minds from God,
and placed them in the earth and earthly vanities, and fading pleasures;
yet in this state will pretend to worship God, and give orders for set forms,
according to the times;
but extend no further than outward observations and bodily exercise, which profit little:
Luke 17:1,20 Tim.
4:8. So that all their days such continue and remain unprofitable servants,
who have no promise but to be cast into outer darkness,
where are weeping and gnashing of teeth: Matt. 25:30.

O! let all deeply and weightily consider these things, and lay them to heart,
before it be too late, and repentance be hid from their eyes!
Which God grant, through Jesus Christ our Lord, Amen.

Ambrose Rigge.

Rigate, the 7th of the Eleventh month, 1702-3.

=== A Further Account of the Benefits of True Christianity, by the Spiritual Appearance of Christ.

The primary and fundamental principle of true Christianity, is the gift of God,
through which he will open the fountain of eternal
life to all the sons and daughters of men,
who will hear and receive him.
This gift is Christ in us, the hope of glory:
the mystery which has been hid from ages and generations,
but is now manifested to us Gentiles, a covenant of light: Col. 1:26-27, Isa. 42:6.
He is now preparing many temples to dwell and walk in;
out of which he has and will cast all the buyers
and sellers of things relating to his Father`'s kingdom,
that they may be made houses of prayer, who before were dens of thieves,
and merchant-places of the souls of men; and bind the strong man, i. e. the devil,
and spoil his goods, which are all unrighteousness, sin and iniquity,
with which he has filled many temples, where the money-changers and receivers are,
and have been: but now he is preparing, and will prepare and cleanse them,
that they may be fit for him to dwell and walk in, according to his promise: 2 Cor. 6:16.

And as in his outward appearance he went into the outward temple at Jerusalem,
and cast out all them who bought and sold,
and overthrew the tables of the money-changers, etc., Matt. 21:12-13;
even so now in his inward and spiritual appearance, he will sanctify his temples,
and make them houses of prayer.
When first we came to the knowledge of this gift, we were made witnesses of this work,
which no other man could do.

He brought us to know and witness the first principle of his doctrine, which was,
repentance from dead works, (mark) from, not in, dead works:
so that the ungodly man and woman began to forsake their ungodliness,
and the unrighteous, their thoughts, and to return unto the Lord our God,
who then had mercy upon us, and did abundantly pardon,
according to his promise by the mouth of his servant the prophet: Isaiah 55:7.

This is repentance unto salvation, not to be repented of, 2 Cor. 7:10,
being the fruit and effect of godly sorrow: but the sorrow of the world works death,
and not repentance from dead works;
whereby mankind are made capable to serve the living God,
and to attain to true faith towards him, which works up the soul into love to him,
and all his commandments, and the doctrine of baptisms, and the resurrection of the dead,
and eternal judgment.

The next great gift of God, is true and living faith in his Son,
to all them who truly receive him,
to whom he gives power to become his sons and daughters.
This faith purifies the heart, Acts 15:9, and works righteousness in the soul by love,
and leads up into the new creation in Christ Jesus unto good works,
that we may live in them.
In Jesus Christ neither circumcision, nor uncircumcision, avails anything;
but this faith, which works by love: Gal. 5:6. Which faith is a mystery,
held in a pure conscience, void of offence towards God and men, and overcomes the world,
within and without: John 5:4. Without which it is impossible to please God: Heb. 11:6.

Till men and women come to receive this faith, which stands in the power of Christ,
and of his resurrection, their preaching is vain, and their faith vain,
and they are still in their sins.

This faith was once delivered to the saints,
by which they were made more than conquerors, through him who loved them: Jude 1:3.
Rom. 8:37.

This faith, in those who receive it, brings forth works of righteousness, i. e. love,
peace, joy, meekness, patience, temperance, obedience, faithfulness.
Love to God, and our neighbour; yes, love to enemies, brotherly-kindness,
and all the spiritual and temporal fruits of righteousness,
which it once brought forth in the saints and gospel believers, to whom it was delivered.

And we say, with the apostle James in his day, as the body without the spirit is dead,
so faith without these works is dead: James 2:17, to the end.
The same faith, through Christ`'s spiritual appearance in our day,
is now restored to the saints, and true gospel believers;
by which we stand witnesses against all false and dead faiths,
which bring not forth the fruits and works of righteousness, nor work by love,
nor give victory over the world; but leave the soul in death and darkness;
and the fruits there brought forth, are unholiness, intemperance, strife, debate,
contention, theft, murder, adultery, bloodshed, and all uncleanness and ungodliness,
which has made the world as a wilderness, full of briars and thorns, and beasts of prey.

Another great benefit, which springs from the fundamental principle of Christianity,
i+++.+++ e. the gift of God, is the true and spiritual knowledge of the doctrine of baptisms, etc.

First, the preparing baptism, being that of true repentance,
which John preached in the wilderness, to gather the Jews out of it,
and to open and prepare the Lord`'s way.
But his outward baptism, as it was with a decaying element and temporary,
it was to decrease, as the minister of it testified: John 3:30.
And it gradually decreased, according as the great apostle testified,
and thanked God he had used but little of that baptism, 1 Cor. 1:14-17,
being not thereunto sent, but to preach the gospel.

But the sprinkling children`'s faces with water,
and signing them with the sign of the cross in their foreheads,
waving John`'s baptism to adult persons, or believers, is a human tradition,
and has not the least footing in holy writ.
And this is our belief and doctrine, as to the elementary baptism.

But the saving baptism is that of Christ, with the Holy Spirit and fire:
this baptism sanctifies and purifies the heart, washing the inside;
whereby men and women are made indeed members of Christ, yes, clean members of his body,
children of God, and heirs of eternal life; being thereby joined to the Lord,
and made one spirit: 1 Cor. 6:17. Here is the new creature witnessed,
upon which the apostle laid the weight of the whole matter, Gal. 6:15,
and upon which the profit and spiritual advantage and benefit of both baptisms,
in their respective season, are known; though the first decreased,
the latter is increasing, to the end of days.
Whereby a daily death unto sin, etc. is witnessed,
and a new birth unto righteousness obtained, by all true and spiritual Christians;
being baptized by one spirit into one body, of which Christ alone is the head: 1 Cor. 12:13.

This baptism restores Christianity into its pristine glory and beauty,
which is holiness and righteousness, without which none shall see God,
to their eternal comfort: Heb. 12:14.

The baptizer with this baptism, has his fan in his hand, which John,
the elementary baptizer, had not; and will thoroughly purge his floor,
and gather his wheat into his garner; which John could not,
and therefore was not to continue, by reason of death.
So much in short for the doctrine of baptism, which has been taught us by Christ,
now in his spiritual appearance in our day.

Another great benefit and advantage we have received by the coming of Christ in spirit,
is true faith of the resurrection of the dead, under its several considerations:
the first and greatest, is Christ, who is the resurrection and the life: John 11:25.
Him has God raised to be Lord both of the living and the dead,
Rom. 14:9,
to be King and law-giver in the hearts and consciences of all his sons and daughters,
in all spiritual things, relating to the kingdom of his Father.
All judgment is committed unto him,
that he may give eternal life to as many as obey and follow him, who have a part in him,
by being washed from their sins and pollutions by him;
over such the second death has no dominion or power.
These are they who follow the Lamb in the regeneration,
whose garments are washed in his blood, being baptized into the likeness of his death,
and thereby made partakers of the power of his resurrection.

These being raised by his power out of the grave of sin and pollution,
which defiled all mankind in the first Adam; such are risen with him,
and seek those things which are above; as the apostles exhorted the Christians,
to set their affections on things that are above, and not on things that are below: Col. 3:1-2.
These have part in the first resurrection, Rev. 20:6,
and are priests of God and of Christ, and shall reign with him forever and ever.

Concerning the resurrection of the dead:
seeing we believe that Jesus died and rose again; we also sincerely believe,
that there shall be a resurrection of the dead, both of the just and unjust.
They shall come forth that have done good, unto the resurrection of life;
but they that have done evil, unto the resurrection of condemnation: John 5:29,
And as to the resurrection of bodies; God gives a body as it pleases him,
and to every seed his own body.
There is a natural body, and there is a spiritual: Howbeit that was not first,
which is spiritual, but that which is natural, and afterwards that which is spiritual;
see the holy apostle`'s explication in this case more at large:
1 Cor. 15. And as the seed, or generation of the righteous,
who are born of the incorruptible seed, which is the word of God,
shall come forth in their glorious body, like unto Christ`'s; Phil. 3:21,
so the tares, the seed or generation of the wicked one,
shall contrariwise come forth in their own proper bodies,
to receive their just judgment and condemnation:
for the Lord knows how to deliver the godly out of temptations,
and to reserve the unjust unto the day of judgment, to be punished: 2 Pet. 2:9.

These things we sincerely believe, and in measure understand, by the Spirit of Christ,
our high priest and minister, being spiritually manifested in our mortal flesh,
to destroy the works of the devil, and to finish transgression,
and bring in everlasting righteousness; and so reconcile all mankind to God again,
who are enemies to him, by wicked works.

Another great benefit and advantage we have reaped and received,
by the coming of our Lord Jesus Christ in Spirit, in order to a future glory,
is the true and saving knowledge of the table of the Lord;
where we are made partakers daily of the nourishing
virtue of the body and blood of Christ,
as we daily dwell in him, and he in us.
He testified to the Jews,
to put an end to the many scruples which they had concerning his flesh and blood,
i+++.+++ e. He that eats my flesh, and drinks my blood, dwells in me, and I in him:
as the living Father has sent me, and I live by the Father, so he that eats me,
even he shall live by me: John 6:56-57. This they could not understand,
but strove among themselves, saying, how can this man give us his flesh to eat?
Having only an eye to his visible flesh: then, to draw them off from that, he said,
It is the Spirit that quickens, the flesh profits nothing;
the words I speak unto you, they are spirit and life, verse 63.
This is beyond all the Jewish passovers,
eatings and drinkings, types and shadows, which he put an end to,
by the offering of himself, he being the anti-type and substance of them all:
and his flesh and blood, spiritually eaten and drunk by them who dwell in him,
and he in them, is life eternal to all such.
But to give carnal and worldly-minded men and women bread and wine before dinner,
whose eyes are not opened to discern the Lord`'s body, and call this a supper,
or sacrament, has not the least precept or example in the Holy Scriptures.

This we have learned in the deep,
whose faces the Lord has turned to the Sun of righteousness;
we cannot turn back to follow shadows, the spiritual manna being our bread and life;
and from our spiritual rock proceeds our water of life,
by which we are daily nourished up to eternal life,
that we may hunger and thirst no more; having living bread in our own houses,
and a well of living water, springing up to eternal life: John 4:14, and 6:50-51. This,
in short, I was willing to testify to this particular also.

All other weighty principles of the doctrine of our Lord and Saviour Jesus Christ,
which he preached in the days of his flesh, and are expressed in the Holy Scriptures, we,
by virtue of his coming in Spirit, have embraced, owned,
and freely received and vindicated, through many tribulations;
of which I have had not the least share; in and through which,
a divine hand has upheld me to grey hairs--and hope so to continue to the end of my days:
that so God over all, through his dear Son Jesus Christ, our only Saviour, Mediator,
and Redeemer may be glorified; by whose power alone I have been preserved,
to whom I give the praise, both now, and hope I shall forevermore.

Ambrose Rigge.

Rigate in Surrey, the 24th of the Twelfth month, 1702-3.

Postscript.--Forasmuch as many brethren have taken in hand,
to set forth and declare in word and writing,
of the power and coming of our Lord Jesus Christ in spirit,
and of his glorious day and wonderful works, which he has wrought in many hearts,
since the working of Satan, with all deceivableness of unrighteousness,
in the past long night of darkness and apostasy from the
purity and glory of the true and ancient Christian faith,
doctrine and principles, and have asserted, and to this day vindicated them,
against all opposition, which has not been little, nor from small or few hands:

I also, having been early an eye and ear witness of those things,
which have been testified of, in and by the mouths of many living witnesses;
and well knowing, through long and large experience, all those ancient doctrines,
which my brethren, in scorn called Quakers, have vindicated, to be true, sound, orthodox,
and fundamental; I could not be clear, before I leave this world,
but leave this short testimony in writing,
which I have often and many years declared in word; which all opposition,
both from the world and false brethren, could not overthrow;
in which by the assistance of the Almighty, I hope to continue,
to the finishing of my testimony.
Amen.
Hallelujah says my soul.

=== A Treatise Concerning the Internal Word and Spirit of God, etc.

In the beginning God made man upright, and gave him wisdom,
knowledge and understanding of life, light and glory, in which, while he continued,
he delighted in the sight and presence of him who created him,
and gave him life and being.
Then he knew no evil, but the presence of God was with him,
and the tree of life planted for him, and he knew his Creator, God, who made him.
But of all the creation which hitherto the Lord had made,
there was not found a helpmate for him,
therefore the Lord caused a deep sleep to fall upon man,
and took one of his ribs and made woman.
They were both innocent in his sight,
till the serpent tempted the woman to break the covenant of life,
which God had made with them, by which they came to know evil,
and were deprived of the knowledge of life;
and death and darkness got dominion over them, being driven into the earth,
and made slaves to sin, and captives in the kingdom of darkness,
and therein ignorant of the chiefest good.

But it pleased the Lord, in infinite mercy,
to promise Christ under the name of the seed of the woman, Gen. 3:15,
to redeem them from that slavery and bondage of corruption
into which they were fallen by transgression.
And because of the wickedness of men before the flood, the Lord said,
my spirit shall not always strive with man, for that he also is flesh:
Gen. 6. When the Lord gave to Israel his laws, adding the law upon them,
till the fullness of time was come, that the seed Christ was to be manifested;
he gave them also, with his statutes and judgments which he set before them,
his good spirit to instruct them, and give them knowledge of his mind and will,
Neh. 9:20, in all the statutes and judgments which the Lord then set before them.
While they obeyed and followed these,
they always had his divine secret upon their tabernacle,
and knew the angel of his presence to go before them
in all their undertakings for his name and glory,
and no enemy could stand before them, nor was any blessing withheld from them.
The Word and Spirit of God was very near unto them, even in their mouths and hearts,
that they might hear and do it, Duet. 30:14, and was the only guide of life,
and ground of obedience in all acceptable performances
to God in all ages and generations of the world,
and brought forth a ministration both of the law and prophets.

Jacob, by this spirit, prophesied of the coming of Christ,
long before the law was given by Moses: Gen. 49:10.
The sceptre shall not depart from Judah,
nor a law-giver from between his feet, till Shiloh come,
and the people shall be gathered unto him.
This was fulfilled in the coming of the Just One,
of whom all the prophets from Moses bore testimony: Acts 10:43.

Balaam became a great example of God`'s displeasure,
who erred from the spirit of the Lord, and loved the wages of unrighteousness,
though he dared not take it, nor could curse Israel;
but informed Balak of a way to ensnare their young men,
which brought a sore plague upon them, and kindled the wrath of God against Balaam,
that he became a sooth-sayer,
and was slain among the Midianites by the children of Israel,
according to the commandment of God: Josh. 13:22, Num. 31:8.
But while the children of Israel kept the word of the Lord,
and were instructed by his Spirit, in the time of Moses and Joshua,
and from Joshua to Judah, and in some of the prophets`' times,
their affairs both spiritual and temporal prospered,
and no enemy was able to stand before them.

By the Word and Spirit of God, Joseph interpreted Pharaoh`'s dream,
which none of the magicians could, Gen. 41,
for which he was advanced to high dignity in Pharaoh`'s kingdom.

And Elihu said, I am full of matter, the spirit within me compels me.
Behold my belly is as wine which has no vent, and as new bottles that break;
therefore will I speak, that I may be eased, I will open my lips and will answer: Job 32:18-20.

And David said, I have hid your word in my heart, that I might not sin against you:
Ps. 119:11.
This word was a lantern unto his feet, and a light to his path, verse 105.
And he prayed God to direct his steps in it, verse 133.
O send out your light and your Truth; let them lead me,
let them bring me unto your holy hill, and to your tabernacles: Ps. 43:3.

But in Judah they set up prophets, but the word of the Lord was not in them,
and therefore they prophesied lies in the name of the Lord,
and he gave them up to be destroyed by the Chaldeans:
Jer. 5. For from the least of them to the greatest, everyone was given to covetousness;
and from the prophet, even to the priest, everyone dealt falsely.

But in all the righteous generations from the very creation,
in the several dispensations and ministrations in which they lived;
before the Scriptures were given forth,
the root and ground from which they performed their several services to God,
was the Word and Spirit of God.

Noah, by the word of the Lord before the flood,
was instructed to walk in the way of righteousness and pleased God,
and so was saved from the flood by the ark, for he was a preacher of righteousness:
Gen. 7:1; 2 Pet. 2:5.

And Abraham, by the Word and Spirit of God, received the covenant of circumcision,
Gen. 17, and by the direction thereof left his father`'s house and his country,
and went into the land of Canaan, believing the promise of God,
that his seed should inherit it, though he had not so much in possession,
as to set his foot upon;
and offered up the son of his old age at the word and commandment of God,
of which by the Spirit of God he had perfect knowledge
before the Scriptures were given forth.

The prophet Isaiah said, With my soul have I sought you in the night, yes,
with my spirit within me, will I seek you in the morning: Isa. 26:9.

And when the Lord restored Israel from among the heathen,
where he permitted them to be driven for their iniquities;
he promised to give them a new heart, and to put a new spirit within them,
and to cause them to walk in his statutes, and keep his judgments, and do them:
Ezek. 36:26-27, and 37:14.

And Daniel, the prophet, had the Spirit of the holy God, and light,
wisdom and understanding in him, by which he interpreted the hand-writing on the wall,
that appeared before Belshazzar king of Babylon,
which all the wise men of Babylon could not understand, or interpret: Dan. 5:11.
and 6:3.

And in the gospel ministration,
the Spirit of Truth is universally tendered to all mankind,
to be the ground and cause of the true and saving knowledge of God,
and of his Son Jesus Christ, whom to know is eternal life: John 17:3.

And Paul testified to the Corinthians, as it is written, eye has not seen, nor ear heard,
neither have entered into the heart of man,
the things which God has prepared for them that love him.
But God has revealed them unto us by his Spirit, for the Spirit searches all things, yes,
the deep things of God: 1 Cor. 2:10-9.
Here that great apostle gives preeminence to the Spirit of Truth,
beyond outward literature, though he had a great share of it, in searching all things,
yes, the deep things of God.
And Christ said to the Jews, all things are delivered unto me of my Father;
and no man knows the Son but the Father, neither knows any man the Father but the Son,
and he to whom the Son will reveal him: Matt. 11:27.
So the root and ground of the divine knowledge of God,
and the things of his kingdom, is by the revelation of the Son of God in man,
by his Spirit of grace, life and Truth, in the true gospel day.
The same gospel day having visited us, has brought, forth the same testimony,
so that whosoever attempts to search into the divine
mysteries of the deep things of God`'s kingdom,
and does not first receive the Spirit of Truth, and give up to be governed thereby,
and let it be the key in his hand and heart to open the door thereunto,
but climbs up and seeks to accomplish it some other way, is a thief and a robber,
and shall never find nor be able to unfold the secrets of the Lord,
which are only manifested to them who fear him: Prov. 3:32.
They are hid from the worldly wise and prudent,
that the more they increase in earthly knowledge,
the further they are from the depths of God`'s wisdom.

On this account, Christ said, Strive to enter in at the strait gate, for many,
I say unto you, will seek to enter in, and shall not be able: Luke 13:24.
But the spirit of man, which is the candle of the Lord,
being lighted by the Lord, searches the heart of man, Prov. 20:27. Ps. 18:28,
and discovers the deceit and desperate wickedness thereof,
which none can know without it: Jer. 17:9-10. It manifests every evil thought,
word and deed, which the enemy of man`'s soul suggests to him,
and gives knowledge and understanding of the danger of it,
and in faith and patience waiting in it for strength to resist all evil,
it gives power and victory over it, so that none who loves the light,
and believes and walks in it, does complain for lack of power to resist the devil,
and all his assaults, temptations, and works of darkness.
But as many as thus receive Christ, the true light,
to them he gives power to become the sons and daughters of God, John 1:12,
and gives them the sight and knowledge of the door of entrance into his eternal kingdom,
and leads them by the right hand of his power thereunto; though strait is the gate,
and narrow is the way that leads to life, and few there be that find it;
for wide is the gate, and broad is the way that leads to destruction,
and many there be that go in thereat: Matt. 7:13-14.
So that whosoever does not give up to follow Christ,
the light of the world, can never enter in at the strait gate,
nor receive power to become the sons and daughters of God;
but are always complaining for lack of power to resist the devil,
and to do the will and work of God, which is man`'s sanctification.
Such have not yet received Christ as he is given of God, to be a Saviour to all mankind,
from sin and the power and prevalency of it; but count him a hard master,
who gives not sufficient power to do whatsoever he commands.

Such make him more unjust, as far as in them lies, than the evil one,
for he gives his servants full power to do his work, which is sin and iniquity;
so there is no complaint for lack of power to sin in thought, word and deed,
but his servants drink it in, as the ox drinks water, and commit sin with greediness,
without any complaint for lack of power to effect it.
Oh! beware of this unjust and blasphemous opinion, or rather delusion of the wicked one,
for it has led many to destruction,
by not improving of that talent which the great Lord
of heaven and earth has committed to them,
which is his Spirit,
a manifestation thereof being given to every man to profit withal: 1 Cor. 12:7.

And though he seems now to have taken his journey into a far country,
yet he has delivered his goods to his servants, to everyone talents,
according to his own pleasure, one at least to everyone,
which at his coming he will require with advantage, i. e.,
the improvement of it in his absence; and who answers him herein shall have the sentence,
of "`Well done, good and faithful servant, enter into the joy of your Lord.`"
But if any should neglect the improvement of this talent,
and hide it in his earthly heart, and say to his Master, when called to an account,
"`I knew you to be a hard man, who reaped where you sowed not,
and gathered where you had not scattered seed, and I was afraid,
and hid my talent in the earth.
Behold, there you have what is yours,`" etc.: Matt. 25:21-25,
Oh! what was the dreadful sentence he received?
You evil and slothful servant, you ought to have improved my talent;
and he commanded it to be taken from him and given to him who had improved his talents,
and of five had made other five; and yet more terrible!
"`Cast the unprofitable servant into outer darkness,
where is weeping and gnashing of teeth forever:`" verse 30.

Oh! dread and fear the great God, you who are sporting away your precious time,
and eating, and drinking, and rising up to play, and feasting, and rioting with gluttony,
and in words and hard speeches,
beating your fellow servants who are improving their
talents in the time given them of their great Master.
The manifestation of the Spirit is given to every man and woman to profit withal,
some after one manner, and some after another,
according to the divine wisdom of the Giver; some more, and some less, but a part to all,
which ought to be improved by all in their lifetime, and not resisted and quenched.
For this was the ruin of that great people the outward Jews, Acts 7:51,
and made them less sensible of the coming and power of Christ,
than were the unclean spirits, who confessed that they knew who the Son of God was,
saying, "`Let us alone, what have we to do with you, Jesus of Nazareth?
Have you come to destroy us?
I know who you are,
the Holy One of God:`" Mark 1:24. But the chief
priests and scribes of the Jews knew him not,
but said he had a devil, John 7:20,
and also that he cast out devils by Beelzebub the prince of the devils: Matt. 12:24.
But if they had received the good Spirit of God,
which was given of the Father to instruct them,
by it they would have known the power of his coming, and the virtue of his life,
which was given to ransom them and all mankind from darkness and the power of the grave.
This life was and is the light of men, John 1:4,
and enlightens every man that comes into the world, verse 9.
With and by this light is the true and saving knowledge of God received,
2 Cor. 4:6, and by no other way or means whatsoever, for God is light, 1 John 1:5,
and manifests himself by and through his Son; and also whatsoever things are reproved,
are made manifest by the light, for whatsoever makes manifest the deeds of darkness,
is light, given of God to lead out of darkness, and the ways and works thereof:
Job 29:3, Isaiah 55:4. The light gives not only knowledge,
but direction to walk in the way of righteousness,
which alone leads to everlasting rest and peace with God: Isaiah 32:17, Prov. 8:20.
This is the way in which Abraham, Isaac,
and Jacob walked to their eternal rest, even the way of holiness,
which the unclean cannot walk in, but it is prepared for the wayfaring men, who,
though fools, shall not err therein.
No lion shall be there, nor ravenous beast shall walk therein, nor be found there;
but the redeemed shall walk there, and the ransomed of the Lord shall return,
and come to Zion with songs and everlasting joy upon their heads,
and sorrow and sighing shall flee away: Isaiah 35:8-10.

But as it happened to the outward Jews in their day,
who by resisting and quenching the measure of God`'s Spirit given them,
whereby they might have seen and known Christ,
in his appearing in that body of flesh in all things like unto man, sin excepted;
even so has it happened in our day, to the outward and nominal Christians,
who by resisting and quenching the Spirit of God given them,
are ignorant of the power and coming of our Lord Jesus Christ in spirit,
and cannot receive him, nor the testimony given of him by his servants,
but say as the mockers whom the apostle Peter warns the saints of,
who walked after their own lusts in the last days: Where is the promise of his coming?
For since the fathers fell asleep, all things have continued as they were.
Revelation is ceased, and nothing now to be depended upon, or expected,
but outward literature acquired by man`'s wisdom, and the letter of the Scriptures,
which the chief priests and scribes of the Jews had,
and thought to have eternal life in them, but would not come to Christ the light,
and so shut up the kingdom of heaven,
and all divine knowledge and understanding of the
things appertaining to the kingdom of God,
from the sons and daughters of men; and will neither enter themselves,
nor willingly allow them that would: Matt. 23:13.

But the root of divine knowledge is springing in many hearts,
and the true light is shining out of darkness in many souls,
to give the light of the knowledge of the glory of God in the face of Jesus Christ;
and this treasure we have in earthen vessels,
that the excellency of the power may be of God, and not of us: 2 Cor. 4:6-7.

And the ancient doctrine of our Lord and Saviour Jesus Christ, is renewed again,
with living thanksgiving to God,
who has hid the secrets of his kingdom from the wise and prudent of the world,
and has revealed them by his Spirit, unto babes and children, who are taught of him;
and has chosen the foolish things of the world to confound the wise,
and the weak things of the world to confound the things which are mighty;
and base things of the world which are despised, has God chosen;
and things which are not, to bring to naught things that are;
that no flesh should glory in his presence.
This was the Lord`'s choice in the ancient gospel day: 1 Cor. 1:26-29.

Now this knowledge which is given to the weak and ignorant,
by the revelation of the Son of God in spirit, is saving, and gives life eternal,
to them who in faith and hope wait for it, and continue in it to the end;
and such can tell others what the Lord has done for their souls,
even what their hands have handled, and how they have tasted of the word of life,
and what their eyes have seen.
Such wait low at the feet of Jesus to hear his gracious words,
that they may speak what their ears have heard, and publish what their eyes have seen;
such gather not people to themselves, nor for their own gain and interest,
nor seek their own glory; but turn people to Christ,
the great shepherd and bishop of their souls, that they may hear his voice,
and follow him, that he may give unto them eternal life, according to his word: John 10:27-28.

But the world`'s knowledge puffs men up into pride, mastership,
and lordship over God`'s heritage, and such are not examples of meekness,
humility and self-denial to the flock,
but like the scribes and pharisees which Christ cried woe against,
who loved the chief places at feasts, and to have the chief seats in the assemblies,
and greetings in the markets, and to be called of men rabbi, i. e. master: Matt. 23:5-6.
Mark who these are in our day, and know them, not by their words,
but fruits, for that gives the true knowledge of them, to whom the woe now is,
as Christ said: Matt. 7:15-16. And they who increase in the world`'s knowledge,
increase sorrow: Ecc. 1:18.

But he who would have true wisdom, and saving knowledge, must attain thereto,
by waiting and continuing in the fear of God, which is the beginning of it;
Prov. 9:10: and depart from pride, arrogancy, and every evil way and work: Prov. 8:13.
This is the way to seal and confirm it to every soul;
true wisdom and knowledge cannot be gotten for gold, the price thereof is above rubies.
This little legacy I am willing to leave to the world,
which I have had long experience of, in my pilgrimage in this life,
that the root and ground of divine knowledge,
and spiritual understanding of the things of God`'s kingdom,
is near unto every man and woman, that they may go no more after them who say,
lo here is Christ, and lo there.
For many deceivers are, and for ages have gone out into the world,
who though in words they profess Christ`'s name,
and seem to have great veneration for him, yet in works deny him,
and will not that he shall rule in their hearts and consciences,
or be followed and obeyed in all things, calling him Lord and Master,
and yet do not his commandments.

These keep people learning all their days,
and yet the saving knowledge of the Truth is still hid from them,
and so freedom by it is never obtained, but such live under the bondage of corruption,
and die in their sins, for lack of receiving the word of the kingdom, the word of faith,
which is near in their hearts, and giving up to obey it.
This Moses testified unto, many ages and generations ago, Duet. 30:14,
saying to the house of Israel, the word is very near unto you,
even in your mouth and in your heart, that you may do it.
And David hid this word in his heart, that he might not sin against God, Ps. 119:11,
and it became a lantern to his feet, and a light to his path: Ps. 119:105.

And all along in the true prophets`' days, the word of the Lord was in them,
i+++.+++ e. Christ, whose name is called The Word of God, Rev. 19:13,
by which they prophesied of his coming into the world: Isa. 7:14;
Behold a virgin shall conceive and bear a son, and they shall call his name Emmanuel,
or God with us, which name can agree to none, but to him that is both God and man;
to which agrees the prophesy of the prophet Isaiah.
And the apostle, writing to the Romans concerning the righteousness of faith, etc.:
"`For Moses describes the righteousness which is of the law,
that the man which does those things shall live by them.
But the righteousness which is of faith speaks in this way, Say not in your heart,
Who shall ascend into heaven?
(that is, to bring Christ down from above:) Or, Who shall descend into the deep?
(that is, to bring up Christ again from the dead.) But what says it?
The word is near you, even in your mouth, and in your heart: that is, the word of faith,
which we preach:`" Rom. 10:5-8, John 8:31-32,
by which freedom and redemption is obtained, according to the testimony of Jesus Christ,
when on earth.

And before he ascended to the Father,
he promised unto his disciples to send the Holy Spirit, which is the Spirit of Truth,
which should guide them into all truth: John 16:13. This was,
and is the true guide of life, doctrine, and conduct, to all true gospel believers,
and will so continue to the end, to all who truly receive it, and walk in it,
to whom there is no condemnation: Rom. 8:1.
For the true gospel ministration is a ministration of the Spirit,
and its commands are spiritual, which no carnal man or woman, in that state,
can perceive or know; for they are spiritually discerned and received,
being included in the true and spiritual worship of God the Father,
in his Son Christ Jesus: John 4:23.

Therefore we say, with the apostle to the Ephesians,
who were grown up to the life and spirituality of Christianity, There is one body,
and one Spirit, even as you are called in one hope of your calling; one Lord, one faith,
one baptism, one God and Father of all, who is above all, and through all,
and in you all: Eph. 4:4-6.

And to the Colossians, when he instructed them concerning meats and drinks,
or in respect of a holy day, or new moon, or sabbath day; he said,
which all are a shadow of things to come; but the body is of Christ.
Therefore, if you be dead with Christ from the rudiments of the world, why,
as though living in the world, are you subject to ordinances, (Touch not; taste not;
handle not;
which all are to perish with the using;) after the commandments and doctrines of men?
which things have indeed a show of wisdom in will worship and humility,
and neglecting the body etc.: Col. 2:20-23.

Now they being come to the anti-type of all shadows, types and figures,
which were for a time allowed to be practiced in the first covenant,
though they did not disallow them in their time and place;
yet they witnessed an end of them, exhorting the saints to purge out the old leaven,
that you may be a new lump, as you are unleavened;
for Christ our passover is sacrificed for us: therefore, let us keep the feast,
not with old leaven, neither with the leaven of malice and wickedness,
but with the unleavened bread of sincerity and truth: 1 Cor. 5:7-8.
Here was that feast which ended,
and was the substance of all the Jews`' feasts, which were many and great,
in remembrance that the Lord passed over the doors of the Hebrews,
when he destroyed the Egyptians,
where the blood of the paschal lamb was sprinkled upon the lintel, and the door posts,
according to the commandment of Moses: Ex. 12:22-23.
And Christ the paschal lamb offered himself once for all,
that he might bear the sins of many,
in that body wherein he finished the work his Father gave him to do on earth,
which the Spirit of Truth, in our day, has given us the true knowledge,
and sincere esteem of; and also, that he is come again in Spirit,
to sprinkle our hearts with his blood; and if we keep within,
the destroying angel sent of God to smite the Egyptians, will pass over our houses.

This was typified by the outward passover, a feast often kept by the outward Jews,
who had the outward circumcision, temple and offerings; and yet were ignorant of Christ,
the true Christian passover,
whose blood had sprinkled the hearts and consciences of all true believers,
that the destroyer could not enter into their houses.
Thus was salvation brought about them, for walls and bulwarks,
according to the testimony of Isaiah the prophet: Isa. 26:1.
And the church began to put on her beautiful garments,
and no more to be called desolate or forsaken; for her stones were living,
built up together a spiritual household, a habitation of God, through his Spirit,
in which they worshipped him, and kept his ordinances; the true church,
her bread was living, and her wine well refined; her bishop and high priest was Christ;
her beauty was holiness, the beautiful garment, the Lamb`'s righteousness,
and crowned with glory and immortality.

This was her state in the ancient gospel day: but,
after the spirit of antichrist prevailed, and men forsook the Lord,
the fountain of living waters, and hewed to themselves cisterns that would hold no water;
then the false church began to clothe herself with a glorious outside,
and sat as a queen, having a golden cup in her hand, full of filthiness;
so that she prevailed with the potentates of the earth, and made them drunk with her cup;
by which their hearts and minds were adulterated from God.
The great dragon, that old serpent, called the devil, being cast down into the earth;
the beast rose out of the sea, that had seven heads and ten horns,
and upon his heads the name of blasphemy.
And another beast rose out of the earth, which had two horns like a lamb;
but he spoke like the dragon, and exercised all the power of the first beast,
and caused them who dwelt on the earth to worship the beast, and to receive his mark,
both small and great, rich and poor, bond and free;
and deceived them that dwelt on the earth,
by the great wonders that he was permitted to work in the sight of the beast.

The dragon persecuted the true church, and cast a flood of water out of his mouth,
after the woman, that he might cause her to be carried away with the flood;
but the earth helped the woman, and opened her mouth, and swallowed up the flood.
Then was the dragon wroth with the woman, and made war with the remnant of her seed;
and the beast that arose out of the sea made war with them, and overcame them;
and power was given him, over every kindred, tongue and nation;
and all that dwelt upon the face of the earth worshipped him,
whose names were not written in the book of life of the Lamb,
which was slain from the foundation of the world.
Here darkness, and the power thereof, gained victory in the earth for many generations;
but a refuge for the true church was prepared in the wilderness,
where she was to be preserved, till the words of God were fulfilled,
and she has continued as a desolate widow for many generations.
But now she is returning, and putting on her beautiful garments, clothed with the sun,
and crowned with stars, which shine in the firmament of the Lord`'s power,
being mysteries of the heavenly Jerusalem, whose children are free,
begotten by the immortal word of life, and born of the immortal seed,
to be heirs of an incorruptible inheritance that fades not away;
and the eyes of many are opened, and yet will be opened, to see and behold her beauty;
for the Lamb is her husband, king and law-giver;
and the nations of them who are saved must walk in his light,
and the kings of the earth shall bring their glory and honour to it: Rev. 21:23-24.
The glory and honour of the Gentiles shall be brought unto it, verse 26.

And whoever would attain to the true and saving knowledge of God,
and be saved from the wrath to come, must come to the light of the Lamb,
with which he has enlightened them, and walk in it,
which discovers the deceit of their hearts, and every evil thought, word and work,
before it is brought forth into action.
In it is power to resist the devil, in all his temptations and assaults;
and whoever believe in it, believe in Christ, and are children of God,
according to Christ`'s word: John 12:36, John 1:12, Rom. 8:14. For God is light,
and dwells in it, and the light dwells with him: Dan. 2:22, Ps. 36:9, and 43:3,
and 97:11, and 104:2, and 118:27. Isa. 2:5, and 42:6, and 49:6,
and 60:3. Micah 7:8-9, Luke 2:32, Acts 13:1,47 Tim.
6:16, 1 John 1:5.

This light is God`'s day, every soul by it may see its Saviour and deliverer,
out of the bond of iniquity, and house of darkness; in which, while men live and walk,
though the light shine ever so clear, they cannot comprehend it, nor know the way of it,
nor understand the paths thereof, neither have any benefit by it,
in order to their salvation: John 24:13.
This is the light the apostle Peter
exhorted the gospel believers to take heed unto,
saying, we have a more sure word of prophecy,
(than that voice which was heard in the holy mount,) unto which you do well to take heed,
as unto a light that shines in a dark place, till the day dawn,
and the day star arise in your hearts; 2 Pet. 1:19.
Here the gospel day was to spring, and the day star to appear,
in all true believers in the light, with which everyone is enlightened,
that they may take heed to it; so shall the true gospel day dawn,
and the day star arise in their hearts, from generation to generation.

And blessed be the Lord, the gospel day now shines, and the darkness is past with many,
who are engaged to watch and be sober, having put on the breast-plate of righteousness,
and the shield of faith, and helmet of salvation, and the sword of the Spirit,
or spiritual sword, which is the word of God,
by which they are able to resist the enemy of their souls,
and to quench his fiery darts within and without.
The Lord is their shield and buckler, who trust in him, and depend upon his protection;
they never meet with disappointment from him, but always return victors; glory,
honour and living praises be unto his eternal and honourable name forevermore.

But many are ready to object and say, that false spirits and prophets are now come,
according to Christ`'s words to his disciples: Matt. 7:15-17,
Beware of false prophets, which come to you in sheep`'s clothing,
for inwardly they are ravening wolves: you shall know them by their fruits, etc.
Now let all seriously consider, that he spoke to his disciples then in being,
many ages ago; that they should come to them,
and that by their fruits they should know them, i. e. the false prophets;
and the apostle John said to the little children in his day,
You have heard that antichrist shall come, even now are there many antichrists;
whereby we know it is the last time: they went out from us,
for they were not of us: 1 John 2:18-19.
And again in his 4th chapter, Beloved, believe not every spirit,
but try the spirits whether they be of God,
for many false prophets are gone out into the world: 1 John 4:1. Christ had said,
they should come, as above; and John said they were come,
and that they went out from them, because they were not of them,
else they would have continued with them.
I have declared above,
what bloody fruits they have brought forth in the world since they went into it;
which are obvious to every judicious eye, like briars and thorns,
of which no grapes can be gathered;
and have made the world as a wilderness full of wild beasts, and beasts of prey,
to this day.
Many false prophets are now in the world,
who through covetousness with feigned words are daily making merchandize of people,
such as the apostle Peter speaks of, 2 Pet. 2:1, but the day has discovered them;
glory to God on high, peace on earth, and good will to men.

Blessed be the Lord:
the Spirit of Truth is come which Christ promised that when he went to the Father,
he would send, John 16:7-14: I tell you the truth;
it is expedient for you that I go away; for if I go not away,
the Comforter will not come: but if I depart, I will send him;
and he described the fruits of the Spirit of Truth.
First, he should reprove the world of sin.
This every sinner on earth may witness to; that when he sins,
he is reproved within himself by the Spirit of Truth.
Secondly, he will reprove the world of righteousness and of judgment,
which everyone who is in the world`'s righteousness may seal unto,
being but as filthy rags: Isa. 64:7. This is that outside righteousness,
which the scribes and pharisees had; which Christ cried woe against:
Matt. 23. This righteousness the Spirit of Truth, now received by man,
does reprove and judge,
being not the righteousness of faith which first cleanses the inside.
Thirdly, and when he is come, even the Spirit of Truth, he will lead you into all truth:
of this there are many witnesses at this day, who have received the Spirit of Truth,
and given up to walk in it; it has led them into all Truth, and out of all untruth.
Fourthly, he shall glorify me, for he shall take of mine, and show it unto you.
There are thousands who can seal unto this, at this day,
who can and do glorify God in their bodies and spirits,
by virtue of that spirit they have received from him.

So we believe not every spirit, but try the spirits and prophets,
what fruits they bring forth, by the Spirit of Truth and the Holy Scriptures,
which we believe were given by divine inspiration; and are profitable for doctrine,
for correction, and for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished to every good work, 2 Tim. 3:16-17,
and do see and certainly know that those are false spirits and prophets,
who bring not forth fruits of holiness and righteousness in their lives and conversations.
Nor do they turn people to righteousness, or from the evil of their ways;
but keep them forever learning, that they may be ever paying,
and yet never savingly come to the knowledge of the Truth, to be made free,
as Christ said to the Jews: John 8:31, If you continue in my word,
then you are my disciples indeed; and you shall know the Truth,
and the Truth shall make you free.
The Lord God open people`'s eyes,
that they may see and know the things that belong to their peace with God,
before it be hid from their eyes.
Amen.

This being the desire, and fervent prayer,
of him who would have all men come to the knowledge of the Truth, and be saved,
called among men,

Ambrose Rigge.

Rigate in Surrey, the 8th of the Fifth month, 1703.

=== The Song of a Solaced Soul

Mount up, my soul, on contemplation`'s wing.

And sound high praises, to thy Heavenly King:

Who hath destroyed death; that he may be

Forevermore a Saviour unto thee.

Therefore to live is Christ, to die is gain,

That thou with Him, forever mayest remain.

In perfect triumph, over death and hell.

In those sweet mansions, which no tongue can tell.

So while on earth thou dost continue here.

Mind thy Redeemer, with continual fear;

Who will preserve thee, to thy finishing day,

From sin to death, and every evil way,

Then will God`'s secrets ever thee attend,

And crown thy head with laurel in the end.

by Ambrose Rigge.

Written at Rigate in Surrey, the 4th of the Eighth month, 1703.
