name: pdf-previews

on: [push]

jobs:
  pdfpreview:
    name: pdf-previews
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      PRINCE_BIN: /home/runner/bin/prince-books
      CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
      CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
      CLOUD_STORAGE_ENDPOINT: ${{ secrets.CLOUD_STORAGE_ENDPOINT }}
      CLOUD_STORAGE_KEY: ${{ secrets.CLOUD_STORAGE_KEY }}
      CLOUD_STORAGE_SECRET: ${{ secrets.CLOUD_STORAGE_SECRET }}
    steps:
      - name: debug
        run: |
          curl -s https://flp-assets.nyc3.digitaloceanspaces.com/actions/prince-books-20191125-ubuntu18.04-amd64.tar.gz > ~/prince.tar.gz
          tar -xvzf ~/prince.tar.gz -C ~ > /dev/null
          printf "$HOME\n" | ~/prince-books-20191125-ubuntu18.04-amd64/install.sh
      - name: do a js thing
        uses: friends-library/friends-library/actions/pdf@actions
      # - name: upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: moved
      #     path: ~/moved.pdf
