name: pdf-previews

on: [push]

jobs:
  pdfpreview:
    name: pdf-previews
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      PRINCE_BIN: /home/runner/bin/prince-books
    steps:
      - name: debug
        run: |
          curl -s https://flp-assets.nyc3.digitaloceanspaces.com/actions/prince-books-20191125-ubuntu18.04-amd64.tar.gz > ~/prince.tar.gz
          tar -xvzf ~/prince.tar.gz -C ~ > /dev/null
          printf "$HOME\n" | ~/prince-books-20191125-ubuntu18.04-amd64/install.sh
      - name: test
        uses: friends-library/friends-library/actions/pdf@actions
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/work/_actions/friends-library/friends-library/actions/actions/pdf/artifacts/pdf-action/howdy.pdf
